---
title: "Background on Fraternities"
output: pdf_document
bibliography: references.bib
linkcolor: blue
---

# Background on Fraternities

A fraternity, in the context of universities, is defined as a men's student organization formed chiefly for social purposes having secret rites and a name consisting of Greek letters. Fraternities are a ubiquitous, and longstanding tradition in the United States. They maintain a presence at 800 universities across the US [@hechinger_true_2017] with the oldest fraternities forming in the mid 1800s (IFC website). 

Fraternities consist of students from families of higher-than-average educational attainment and income; they are predominantly white, and prior research has linked fraternity membership to increases in graduation rates [@routon_impact_2014], income [@mara_social_2018], and GPA [@debard_greek_2011]. However, members spend approximately 2 more hours partying than nonmembers [@routon_impact_2014], and sorority^[A sorority is the female counterpart of fraternities.] members, who socialize frequently with fraternity members, have been found to consume alcohol with greater frequency, delay assessments of threat, and have significantly higher rates of drugging victimization than non-sorority members [@lasky_binge_2017; @franklin_sorority_2016]. 

This paper focuses primarily on a group of fraternities known as the Interfraternity Council (IFC), a group of fraternities that consist of over 4 million alumni and more than 380k undergraduate members across the US which, according to their creed, "exist to promote the shared interests and values of our member fraternities: leadership, service, brotherhood and scholarship" [@hechinger_true_2017]. IFC fraternities differ from professional development fraternities in that they exist mainly for social purposes and are typically the largest fraternity presence at a university. More importantly, IFC fraternities are the fraternities subject to moratoriums in the sample.

To become a member of an IFC fraternity, prospective members must apply during recruitment events that take place in the fall or spring semester (or both). Once a chapter and prospective member jointly accept membership, the new member (the "pledge") must abide by the chapter’s guidelines. Figure \ref{fig:sigmaalpha} shows an example of the overarching rules within the chapter, Sigma Alpha Epsilon–one of the oldest and largest fraternity chapters across the US that has initiated over 336k members [@hechinger_true_2017]. Each member must maintain a GPA over a certain threshold, pay an initiation and semester fee, attend chapter ritual events and meetings, be involved in one additional campus or community organization, and complete service hours. Upon membership, pledges may be invited to live within the fraternity house,^[Not all universities have fraternity houses on their campus property, and not all fraternity chapters have houses at every university they are affiliated with.] which can reside either on or off campus. However, chapter houses are not managed by university-housing, and hence, fraternities have been found to be the most reliable source of alcohol for first-year undergraduates [@mara_social_2018]. 




