---
title: "Conclusion"
output: pdf_document
bibliography: references.bib
linkcolor: blue
---


# Conclusion

Fraternity moratoriums are effective for reducing university-wide alcohol offenses. While alcohol offenses remain relatively stable on weekdays during moratorium periods, the large decreases occur on Friday through Sunday - days where college partying is most frequent. These decreases are not driven by differences in reporting nor are they the result of a more general decline in alcohol offenses over time. Importantly, these effects are strongly dependent on the source of oversight: when the IFC council imposes a moratorium (e.g. a self-imposed moratorium), the effects disappear in contrast to a university-imposed moratorium. In addition, fraternity moratoriums show weak statistical evidence of decreases in sexual assault. Similarly to alcohol offenses, these effects are strongest on the weekends, lending  evidence that the observed decreases are the result of the moratoriums themselves. 

Taken together, these results provide support for the drastic reformation of fraternities to significantly improve campus safety. By prohibiting alcohol across all IFC fraternity social events, campus-wide alcohol offenses declined significantly and reports of sexual assault decreased on the weekends. Hence, universities can experience large benefits with more restrictive measures on their fraternity's social gatherings. However, it is crucial that these guidelines be enforced by the university, as student-enforced restrictions are ineffective. 

It is important to understand that this paper does not provide evidence advocating for the removal of fraternity life. Within this study, none of the universities removed fraternity life, only restricted it. Thus, future research on the impact of removing fraternities from universities is needed to understand the cost/benefit analysis as the answer remains ambiguous: risky fraternity-related behavior could disappear or, on the other hand, worsen if these high-risk individuals are unregulated. Additional policies aimed to improve fraternity and sorority life also need further evaluation. For instance, a new practice termed 'deferred recruitment' prohibits fraternity and sororities from adding new members in the fall semester. While this policy has already taken place at multiple large universities across the country, there is little rigorous evaluation of such procedure. Until further research is completed, there is no clear answer to whether national movements such as "Abolish Greek Life" should be embraced.





