---
title: "Empirical Strategy"
output: pdf_document
---

# Empirical Strategy

I estimate the effect of fraternity moratoriums on reports of sexual assault, alcohol offenses, and drug offenses by exploiting across-time and within-university variation brought about by the plausibly exogenous nature of the moratoriums. The model's identifying assumption is that universities that have experienced, will experience, or have never experienced a campus-wide fraternity moratorium are a good counterfactual for a university experiencing a campus-wide fraternity moratorium. In particular, the baseline approach to this model is estimated using Equation \ref{main_model}, where $Y_{u,t}$ represents the outcome of either sexual assault, alcohol offenses, or drug offenses at university $u$ in time $t$, $\mathbb{X}_{u,t}$ is a vector of observable university characteristics that are complete across all universities^[List out the observables here] to minimize the impact of missing data, $\gamma_{u,semester}$ is a university-by-semester fixed effect, $\alpha_{weekday}$ is a weekday fixed effect, and $\epsilon_{u,t}$ is the error term. 

```{=tex}
\begin{equation}\label{main_model}
Y_{u,t} = \beta Moratorium_{u,t} + \mathbb{X}_{u,t} + \gamma_{u, semester} + \alpha_{weekday} + \epsilon_{e,t}
\end{equation}
```

University-by-semester fixed effects are included to remove any time-invariant differences between university-semesters. For instance, fraternity recruitment events vary across university-semesters (e.g. some universities may only allow spring recruitment, while others may allow fall and spring recruitment) which may enhance fraternity-related activities within a semester (CITE). The inclusion of these fixed effects ensures that the estimated effects are driven by moratoriums instead of a cyclical increase in fraternity activities. 

I include day-of-week fixed effects to address the fact that most fraternity-related activities occur on Fridays/Saturdays. Hence, the estimates should be interpreted as an additional effect of the crimes that typically reported on a given weekday. 

To increase precision of the estimates, I use only academic calendar days for each specific university. In particular, I extracted academic calendars for each university^[Academic calendars are based on the most recent calendar that was relevant to my sample period. Most academic calendars are based on academic years 2019-2020.] using the first-day of classes as the start-date of the fall semester, the finalized grade date for the end of the semester, and added a seven-day period to each beginning and end of a semester to account for slight variations across years.^[However, I do not add a seven-day period to the end of the fall semester as this would bleed into Christmas vacation for many of the schools. Considering I use an extremely conservative end date (finalized grade date), there is little possibility that I will be excluding a significant amount meaningful university-student-life activity. Additionally, if a start date was January 7th or earlier, I do not add a seven-day buffer. Exact academic calendars were not used because a significant portion of schools do not retain their old academic calendars.] To harmonize the  `r round(2/53,2) *100`% of the universities in the sample that use the quarter system, the fall quarter is defined as the fall semester, and the winter/spring quarters are defined as the spring semester. 

Based on this empirical strategy, the main challenges with interpreting $\beta$ as the causal effect of fraternity moratoriums come from two separate channels: reporting and ex-ante trends. First, it is important that the propensity to report a crime does not change between moratorium days and non-moratorium days. For instance, $\beta$ would be overestimating the effect of fraternity moratoriums if victims of sexual assault were more inclined to report (e.g. increase pressure on fraternities) or if there was more surveillance (e.g. more police officers on-duty to prevent bad behavior) on moratorium days which could result in higher reports of sexual assault and more discoveries of alcohol/drug offenses respectively. On the other hand, $\beta$ may be underestimating the effect of fraternity moratoriums if sexual assault victims are less inclined to report an offense (e.g. fear of retaliation) or if police surveillance decreased (e.g. less need for police officers when little fraternity activity) during moratoriums. To indirectly test these possibilities of reporting differences, I test whether there is a significant change in the proportion of offenses that are reported with a lag (see section BLANK) on moratorium days. I follow (SILENCED WOMAN) and define a crime reported as a lag 

Moreover, $\beta$ would not represent the causal effect of fraternity moratoriums if university police incidences/reports of crimes were already trending downward prior to the moratorium and would have continued downward absent the moratorium (e.g. Ashenfelter's Dip).

