---
title: "Fraternity Moratoriums"
output: pdf_document
---

# Fraternity Moratoriums

## Collection of Dates and University Characteristics

University-wide fraternity moratoriums are defined as a temporary cease of fraternity-related social gatherings with alcohol. While there is variation in each university's guidelines (e.g. some universities may restrict third-party vendors for fraternity events during a moratorium, others may not), each of the universities in the sample restrict registered social events with alcohol.^[Fraternity social events typically need to be registered through their respective university. An example of the guidelines for one university can be found HERE.]. The existence of a moratorium was found searching school newspaper articles, Lexis Nexis, and a private repository of news articles relating to fraternities. Table FRATERNITY MORATIA DATES shows each of the university's moratorium start and end dates. Each date in Table FRATERNITY MORATORIA DATES was verified using either newspaper articles, conversations with Fraternity and Sorority Life employees, or Freedom of Information Act requests. However, Table FRATERNITY MORATORIA DATES is not an exhaustive list of all moratoria. NUMBER OF SCHOOLS LEFT OUT B/C DATA universities were omitted from the sample because either verification of exact start and end dates could not be achieved, or the university's police department did not provide Daily Crime Logs in a format readable by any software.^[One particularly notable omission from the sample is Pennsylvania State University which registered a fraternity moratorium on PENN STATE DATE due to the cause of Timothy Piazza. The university police department did not allow copies of their Daily Crime Logs to be distributed- only inspected in person.] Hence, the `r 38` universities experiencing moratoriums in the sample are a subset of all university-wide fraternity moratoriums that occurred between 2014 and 2019. Additionally, `r 15` universities (`r round(15/53 * 100,2)`%) that *did not* experience a fraternity moratorium, but experienced a fraternity-activity-related death are included as a 'never treated' control group. This amounts to a total of `r 53` universities that are widely dispersed among the US (see Appendix MAP). Table SUMMARY STATS shows summary statistics of university characteristics using data from the Integrated Postsecondary Education Data System (IPEDS). On average, the universities are large (~28k enrollment), predominantly white (~59% of undergraduates), mostly public (84%) and have a wide variation in terms of selectivity and graduation rate. 

## Who oversees fraternity moratoriums and why do they occur?

Fraternities have three sources of oversight: the university's IFC, the unique fraternity chapter's national headquarters, and the university itself. Of these three sources of oversight, only the IFC and university have the jurisdiction to impose a university-wide fraternity moratorium. IFC-imposed moratoriums account for `r round(16/45,2)*100`% of the moratorium in the sample, while universities account for the remaining `r round(29/45,2)*100`%.

Moratoriums are the result of a plausibly exogenous shock to a university such as fraternity-related deaths, sexual assaults, hazing violations, or racist activity gone viral. Figure TRIGGER GRAPH shows the `r 45` moratoriums in the sample by the event that triggered the moratorium. The most frequent (`r round(19/45,2)*100`%) are behavior violations which include alcohol violations, racist activity gone viral, and hazing allegations, while second are fraternity related deaths (`r round(10/45,2)*100`%), and third are sexual assault allegations (`r round(9/45,2)*100`%). Of these triggering events, death results in the longest average moratorium at approximately 103 university-calendar days, while behavior and sexual assault allegations result in approximately 58 and 31 average university-calendar days respectively. 7 (`r round(7/45,2)*100`%) of these moratoriums had no clarifying explanation for the resulting moratorium. To test the plausible exogeneity of these triggering events, I estimate both a linear probability and logit model on pre-treatment characteristics to predict a fraternity moratorium based on observables. I estimate Equation \ref{prediction_model} where $EverMoratorium_u$ represents whether university $u$ ever experiences a fraternity moratorium, $\mathbb{X}_u$ is a vector of observable characteristics including enrollment, demographics, pricing, and source of income for each university averaged over all years prior to the first moratorium, and $\epsilon_i$ is the error term. Standard errors are clustered by university, and an indicator for missing data is added to the model as revenues and SAT data is missing among a large portion of the sample.

```{=tex}
\begin{equation}\label{prediction_model}
EverMoratorium_u = \gamma \mathbb{X}_{u} + \epsilon_u
\end{equation}
```

Table PREDICTION TABLE shows the results of this prediction exercise. Overall, there is little evidence that university characteristics can predict whether or not a moratorium is implemented. While there appears to be slight evidence that selectivity and total cost are predictors of moratoriums, these are weakly significant, not robust across both specifications, and likely represent 'by-chance' significance due to the multiple hypothesis tests problem. A Bonferroni p-value correction (e.g. multiplying the p-value by the number of hypothesis tests) yields no significance across any of the observable covariates, thus providing further evidence of the plausible exogeneity of these events. 




