---
title: "Introduction"
output: pdf_document
bibliography: references.bib
linkcolor: blue
---
```{r, echo = F}
number_of_universities = 53
## things used here
## main_estimation will be the main estimation table
## leave_one_out is the leave one out figure - side-by-side 1 figure only. 
```


# Introduction

Fraternities are a polarizing college tradition, and it is unclear whether they should remain at universities. While past literature has revealed strong correlations between fraternity membership and better labor market outcomes and GPA, others have found evidence of higher alcohol use and sexual assault [@foubert_behavior_2008]. Moreover, according to data compiled by Hank Nuwer, a journalism professor at Franklin College, more than 200 students have died in hazing-related incidents since 1838--with more than 40 in the last decade. Universities have responded with attempts to reform their fraternity and sorority life such as offering educational classes to assist with binge drinking and sexual assault risk. Despite these progressions, recent movements such as "Abolish Greek Life", a student-led initiative to remove fraternities from universities have gained national attention. But *should* fraternities be prohibited? Universities often rely on fraternities as quasi-official dorms and would otherwise need to create an expensive alternative [@hechinger_true_2017]. Moreover, prohibiting fraternities could result in unregulated alternatives, thus raising the possibility of moving these behaviors to an even riskier setting. 

In this paper, I provide the first causal evidence of how temporarily removing alcohol from fraternity social events and decreasing fraternity activity can reduce alcohol offenses *campus-wide*. In particular, I exploit the plausibly random events in the timing of university-wide fraternity moratoriums--temporary periods where fraternity social events with alcohol are prohibited. These events are unpredictable through standard regression techniques and are often the result of fraternity-related deaths, sexual assault allegations, or behavior violations. Consequently, I find large, robust, and statistically significant evidence that fraternity moratoriums cause a 25% reduction in alcohol offenses. Intuitively, I compare days from universities that, over a six-year period (2014-2019), have had, will have, or never had (but experienced similar fraternity activity) a fraternity moratorium to universities that are experiencing a moratorium while controlling for characteristics that are unique to universities across semesters and across different days of the week. Hence, these large decreases can be interpreted as the additional decrease in alcohol offenses from what we would expect at a given university day in a particular semester. These effects are driven by decreases on weekends (when alcohol drinking and fraternity partying is more frequent) and persist across different estimation methods. Moreover, these decreases are especially potent when a moratorium is triggered by a fraternity-related death. I find no evidence that these results are due to changes in reporting during moratorium days, nor an already-trending decline in alcohol offenses. Furthermore, I find weak evidence that fraternity moratoriums cause decreases in sexual assaults-particularly when a moratorium is triggered by sexual assault allegations. 


I introduce a novel data set, combining fraternity moratorium dates uncovered through school newspapers, Lexis Nexus searches, Freedom of Information Act (FOIA) requests, and conversations with Fraternity and Sorority Life advisers with university-specific Daily Crime Logs- a federally mandated data source that all universities which receive federal funding must maintain. The Daily Crime Logs contain the universe of all crimes reported to the campus police over the most recent seven-year period. The crime logs were obtained through webscraping, PDF extracting, and Jeanne Clery Act requests.  While the crime logs are not harmonized across universities, I pattern-match crime descriptions using regular expressions to find daily counts of alcohol offenses, sexual assaults, and robberies--offenses that are contained in the Campus Safety and Security Data but aggregated to the yearly level. Importantly, this is the first data set to my knowledge to contain harmonized daily counts of alcohol offenses^[The National Incident-Based Reporting System by the FBI contains alcohol offenses by-day, but only for alcohol offenses that end in arrests.] across a wide range of universities.


Previous causal studies on fraternities, while few, have shown that fraternity membership lowers GPA, causes higher alcohol consumption, and increases the likelihood of graduation. Specifically, @mara_social_2018 exploit variation in one university's residential environment and finds a small .25-point GPA decrease and a large, 36% increase in income attributed to fraternity membership. On the other hand, @even_greek_2020 use regression discontinuity methods to show that membership significantly decreases GPA by 0.1-0.3 standard deviations, with effects being most prominent in a fraternity member's first semester. Furthermore, @routon_impact_2014 use propensity score matching to find that fraternity membership increases frequent beer drinking by 14% and graduation rates by approximately 5% and @glindemann_reducing_2007, using a field experiment, found that monetary incentives were successful in reducing blood alcohol content by 20% at fraternity parties, although the sample of participants were not randomly selected. This study contributes to this literature by providing a nation-wide sample of universities and utilizing objective outcomes collected through official university police Daily Crime Logs rather than survey data which is subject to strong measurement error [@bertrand_people_2001]. 

Finally, this paper is the first to causally link fraternity activity to sexual assault. Past research has provided evidence of the relationship between fraternity members' likelihood to commit a sexual assault [@foubert_behavior_2008], and sorority members increased likelihood of reporting being sexually assaulted [@minow_sorority_2009]. However, each of these studies examines only one university and the main analysis is built upon survey data. Although unrelated to fraternity activity,  @lindo_college_2018 most closely resembles this study in empirical strategy and finds causal evidence that college partying increases reports of rapes using football game variation. This study, on the other hand, isolates a decrease in risky fraternity activity.





