---
title: "Results"
output: pdf_document
bibliography: references.bib
linkcolor: blue
---
```{r, echo = F}
number_of_universities = 53
## things used here
## main_estimation will be the main estimation table
## leave_one_out is the leave one out figure - side-by-side 1 figure only. 
```


# Results

## Main Results and Robustness

In Table \ref{tab:main_results}, I estimate Equation \ref{main_model} with OLS using both reports of sexual assault and alcohol offenses per twenty-five-thousand enrolled students as the dependent variables. Standard errors are clustered at the university level, and university-by-semester and weekday fixed effects are included in all specifications. Columns (1)-(3) represent the effect of fraternity moratoriums on alcohol offenses. Column (1) shows a large and statistically significant decrease in alcohol offenses when there are no restrictions on days of the week (e.g. including Monday-Sunday), representing a `r round(.141/.556,2)*100`% reduction from the mean. These effects are driven by weekend days (Friday/Saturday/Sunday), as shown in column (2), while there is no evidence of significant decreases in alcohol offenses during weekdays in column (3). This is consistent with evidence that drinking behavior is less common on weekdays, and alcohol related offenses tend to occur most frequently on the weekends. On the other hand, column (4) shows that reports of sexual assault decrease by a small and statistically insignificant magnitude during moratorium days within the whole sample (Monday-Sunday). While this effect remains small on weekdays (column (6)), there appears to be evidence of large `r round(.017/.054,2) *100`% reduction from the mean on weekends.

In Table \ref{tab:poisson_results}, I replicate the results shown in Table \ref{tab:main_results} using poisson estimation given the discrete, non-negative count nature of the offenses. Hence, $\beta$ can be interpreted as the percent change in the outcome of interest due to moratoriums after a slight transformation.^[For a 'percentage change' interpretation, I use the $e^\beta-1$ transformation.] The estimation exhibits similar results: alcohol offenses decline substantially during moratoriums while sexual assaults remain unchanged at conventional levels of significance. The coefficients show a 28% decrease in alcohol offenses (column (1)), with this effect being attributed to large decreases on the weekends (column (2)). Similarly to OLS, there is little evidence of reductions in reports of sexual assault when considering all weekdays (column (4)), but weakly significant of reductions (32%) on the weekends (column (5)).^[Despite slightly larger magnitudes, I prefer OLS estimation since it (1) provides more conservative estimates and (2) poisson regression with fixed effects may drop observations when no variation is observed.]

While the effects are robust across different estimators, I empirically test that the results are not being driven by one specific university. For instance, it is conceivable that the large decreases observed in alcohol offenses are the consequence of one university that had particularly large effects or experienced an unusually long moratorium period. To mitigate this plausible issue, I estimate Equation \ref{main_model} using a leave-one-out regression framework. More specifically, I estimate `r number_of_universities` separate regressions, with each estimation omitting one university and plot the distribution of estimated $\beta$ coefficients and standard errors in Figure \ref{loo}. In each iteration, the results remain similar across both alcohol offenses and sexual assault. There appears to be no deviation in statistical significance and little deviation in the magnitude of the effects when omitting a single university.

Furthermore, as a placebo test, I test whether robberies and burglaries, two outcomes that have not been documented to be associated with fraternity behavior, are affected by fraternity moratoriums. I combine robberies and burglaries into a single explanatory variable, and estimate Equation \ref{main_model} in Table \ref{tab:robbery}. As expected, there are no effects across robberies.

## Heterogeneity

### Which triggering events have the biggest effects?

Not all moratoriums are equivalent. As shown in Figure \ref{trigger_plot}, a moratorium can stem from a variety of events such as sexual assault allegations, a notable behavior violation, or a fraternity-related death. There are large differences in the salience of these events. For instance, a sexual assault allegation or a behavior violation may only be known within the fraternity community, while a fraternity-related death may be publicized across campus. Hence, campus-wide effects may differ across these levels of salience.  Table \ref{tab:hetero_trigger_alc} explores this heterogeneity, noting that if a moratorium was implemented for an unknown reason, I categorize these as unknown. Column (1) shows the effect of moratoriums that were caused by a sexual assault on alcohol offenses. The effect size is small and statistically indistinguishable from zero. In contrast, a moratorium triggered by a fraternity-related death [column (2)], exhibits a strong and significant `r round(.247/.556,2)*100`% reduction from the mean. This is larger than any effect shown in Table \ref{tab:hetero_trigger_alc} or the main results in Table \ref{tab:main_results}, suggesting that particularly salient events (such as a fraternity death) have a particularly strong impact on student behavior, whereas less salient events (such as a behavior violation [column (3)] or sexual assault [column (1)]) have little impact.

Given that fraternity-related deaths cause the highest campus-wide reductions in alcohol violations, it is possible that these effects are being driven by a change in non-fraternity-member (non-members) behavior rather than the fraternity members (members) themselves. For example, typical member behavior could persist, while non-members reduce their partying and alcohol consumption due to this external, and possibly traumatic shock. This would attribute the effect observed to the death itself, rather than a moratorium. However, this is unlikely to be the case given the choice of the 'never-treated' group; 15 universities were included in the sample that experienced a fraternity-related death, but never experienced a moratorium. It is reasonable to assume that non-members at the 'never-treated' universities experienced a similar shock to those at moratorium universities, and hence, the only change in behavior across campus should be attributed to the moratorium. Taken together, this implies that the moratorium is changing behavior, not the occurrence of a death.

I further examine the heterogeneous effects by triggering event in Table \ref{tab:hetero_trigger_sex}, where sexual assault is the outcome of interest. Column (1) exhibits the effect of a moratorium triggered by a sexual assault on reports of sexual assault where there is a large and significant reduction from the mean of `r round(0.045/.06,2)*100`%. All other triggering events--death of a student [column (2)], behavior violation [column (3)], and unknown [column(4)]--show statistical zeros. This result may the result of two mechanisms. The first, as shown in @doleac_effects_2017, is that an increase in the probability of being caught reduces crimes rates, especially in categories where forensic evidence is likely to be used (e.g., rape). Therefore, marginal fraternity members may be dissuaded from engaging in activities that *could* lead them to a sexual assault allegation. Since sexual assaults are common among universities,^[Survey evidence from the AAU Campus Climate Survey (2019) shows that the overall rate of non-consensual sexual contact was 13 percent.] the enactment of a moratorium intensifies the likelihood of being caught, thus leading to the observed decreases. Second, some fraternity chapters impose mandatory sexual assault training for fraternities following a moratorium. While records on these mandates are incomplete, and often missing entirely, these educational sessions may provide behavior changes for the most at-risk individuals.


### Which disciplinary figure is best?

To explore heterogeneity further, I test whether there are differences in the effects of moratorium on offenses between university-enacted and IFC council-enacted moratoriums. There are distinct differences between the two sources of oversight; a university-enacted moratorium is imposed by the overseeing university and IFC council-enacted moratoriums are imposed by the IFC council. Hence, an IFC council-enacted moratorium can be described as a student-enforced action. A university-enacted moratorium generally contains clear guidelines that fraternities must abide by or risk further disciplinary action. On the other hand, it is uncertain what consequences are ascertained when a fraternity breaks the guidelines given by an IFC council.

Table \ref{tab:hetero_uni_ifc} shows the estimated effects of both university-enacted and IFC council-enacted moratorium on alcohol offenses and reports of sexual assault. In columns (1) and (2), alcohol offenses significantly decrease in both the full sample (Monday-Sunday) and when restricting to weekends when the university enacts the moratorium. Conversely, there is little statistical evidence that IFC enacted moratoriums have a significant impact on alcohol offenses, with weakly significant decreases appearing on the weekends. Columns (3)-(6) show the effects on reports of sexual assault. In each column, reports of sexual assault remain statistically indistinguishable from zero. Collectively, these estimates exhibit the need for strong oversight for moratoriums to be effective. IFC-council imposed moratoriums fail to change behavior across campus, while university-enacted moratoriums result in significant decreases of alcohol offenses. 

