---
title: "Discussion and Conclusion"
output: pdf_document
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Discussion \label{section:discussion}

## Do Moratoriums Mitigate the Effects of Football Games? \label{section:football}

It is well-documented in the literature that college football games cause higher rates of alcohol offenses and rape [@rees_college_2009;@lindo_college_2018]. While football games cause negative outcomes, universities are reluctant to suspend football games—college football is popular among students and alumni in addition to being a major source of revenue. Therefore, finding an effective policy that can mitigate the detrimental effects of football games while maintaining the benefits is important for university administrators. This subsection analyzes whether moratoriums are the policy tool that can accomplish this.

Figure \ref{game_moratorium_plot} shows that football game-days cause a significant increase in the number of alcohol offenses and sexual assaults. These effects are identified by 34 of 37 universities that have football teams in the sample, resulting in over 2000 football games. Each of these effects is larger on home games rather than away games which is consistent with @lindo_college_2018 and @rees_college_2009. Furthermore, Figure \ref{game_moratorium_plot} also shows the combined effect of a game day and a moratorium. In each of these estimations, the point estimates are similar to the effect of game-days only, although less precise. This may be caused by a lack of identifying variation—the estimates are identified by 89 occurrences of game days that coincide with moratoriums. As a robustness check, I broaden the definition of game-days to game-weekends in Appendix Figure \ref{game_weekend_plot}. Although this nearly triples the amount of identifying variation, the results are consistent.^[Not all game-days occur on a weekend, so the expanding the definition to a game-day weekend does not quite triple the number.]  Considering these results, it is uncertain whether moratoriums mitigate the effects of game-days. On one hand, these results offer the possibility that fraternities are not an integral component to college partying on game-days—students can substitute away from fraternity parties to other alternatives such as tailgates. On the other hand, it may be that moratoriums restrict the amount of dangerous partying that occurs during football games and produce a safer environment. Since the estimates are imprecise, it is unclear whether moratoriums can act as an effective policy tool to mitigate the undesirable effects of football game-days. 

## Who Should Enforce Moratoriums? \label{section:enforce}

Recall from Section \ref{section:moratoriums} that there are two sources of enactment/oversight for campus-wide moratoriums—the university itself and the university-specific IFC council. In the sample, 27 of the 44 (61%) moratoriums are enacted by a university. There is reason to suspect differences between these two sources of jurisdiction since IFC moratoriums may lack the incentive structure that university moratoriums have. For instance, a university can permanently suspend a fraternity chapter from its campus for failure to abide by moratorium guidelines which may damage the fraternity chapter's membership and reputation. On the other hand, IFC councils have little incentive to permanently suspend or impose additional sanctions as fraternity chapters rely on each other to maintain their community life. As such, further disciplinary measures by the IFC-council directly affect the council members themselves, thus creating a system that may incentivize IFC council members to look away from the moratorium guidelines.

In Table \ref{ifc_uni_table}, the coefficient estimates on alcohol offenses show suggestive evidence of a decline when a university imposes the moratorium as shown in Panel A. Consistent with the main results, the largest effects are on weekends rather than weekdays. However, in Panel B, the coefficient estimates for sexual assaults are insignificant across both university-imposed and IFC-enacted moratoriums, likely due to the infrequent reporting of sexual assaults. While there is no definitive evidence for differences in enforcement for sexual assaults, the significant declines in the number of alcohol offenses point to the university administration as the more effective enforcement body rather than the fraternity members themselves. 



# Conclusion \label{section:conclusion}

In this paper, I estimate the causal effect of temporary restrictions of fraternity social events with alcohol (*moratoriums*) on campus-wide reports of alcohol offenses and sexual assaults across 37 universities in the US. I construct a novel dataset which includes daily-level incident reports from each university police department. Using these data, I compare academic-calendar days with a moratorium to academic-calendar days without a moratorium while controlling for expected differences in the days of the week, holidays, semesters, academic years, football game-days, and universities. I find that moratoriums decrease the average reports of alcohol offenses on a given academic calendar day by approximately 26%. This result is most prominent on the weekends when partying is most frequent (28% reduction) while nonexistent on the weekdays, and importantly, does not exhibit substantial evidence that moratoriums displace crime to nearby areas. Moreover, I find suggestive evidence of decreases in reports of sexual assaults on the weekends by 29%, although only significant at the 10% level. Notably, moratoriums show no lasting effects, and this result is consistent across moratoriums of shorter and longer lengths. Taken together, these results support the notion that moratoriums are only effective in temporarily reducing campus-wide crime.

Given that moratoriums are unable to create permanent changes in student behavior, it is unclear whether they are a welfare-improving policy. On one hand, moratoriums cause large decreases in alcohol offenses. If these decreases are the result of a displacement effect, these offenses may be occurring in relatively safer areas (residence halls) as speculated in Section \ref{section:spillover}. Furthermore, moratoriums may help alleviate the detrimental health effects that alcohol causes in college students such as hindering academic performance and costly emergency room visits. On the other hand, moratoriums do not permanently change student behavior; while moratoriums have large effects during enforcement, moratoriums are an unproductive policy to systematically reduce college partying behavior. Hence, school administrators should understand that moratoriums are a transient solution and should therefore look for other methods to promote long-term change. One understudied possibility is the suspension of specific misbehaving fraternity chapters from universities rather than IFC moratoriums. Although this policy alleviates the criticism that moratoriums are punishing even well-behaving fraternities, more research is needed to understand the benefits and downfalls of this practice. Specifically, it is unclear whether this truly propagates behavior change—members of a poor behaving fraternity may choose to substitute to a new fraternity and thereby negatively influence its members. 



