---
title: "Heterogeneity"
output: pdf_document
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Heterogeneity \label{section:heterogeneity}

In this section, I analyze two types of heterogeneous effects. First, I analyze whether moratoriums are more effective at schools with a reputation for partying and show that moratoriums are more effective in reducing alcohol offenses at party schools than non-party schools. Second, I examine which type of triggering event of a moratorium causes the most significant decreases of offenses and find that fraternity-related deaths exhibit the strongest results for alcohol offenses. 

## Do Party Schools Exhibit the Strongest Effects?

Universities that have a reputation for partying may be more impacted by the restrictions of moratoriums than universities that party less. For example, @lindo_college_2018 find that party schools exhibit two times the increase in reports of rape on football game days than non-party schools. To examine this possibility, I use Niche.com's Top Party Schools in America list.^[I use Niche.com over the Princeton Review since the Princeton Review no longer posts their party school rankings.] The list assigns "party scene" scores based on criteria such as athletic department revenue, fraternity and sorority life statistics, access to bars, and student surveys.^[For more details on the methodology see: https://www.niche.com/about/methodology/top-party-schools/.]  Using this list, a university is defined as a party school if it appears in the top 50 rankings. This amounts to 16 of the 37 universities in the sample being classified as a party school. 

Table \ref{party_school_table} shows that party schools exhibit larger decreases in alcohol offenses than non-party schools. The point estimates in Panel A indicate that moratoriums decrease alcohol offenses on academic-calendar days by approximately 33% from the mean for party schools and 16% for non-party schools. Importantly, only the point estimates for party schools are statistically significant, thus showing that the effects of the moratorium are driven by schools that have a stronger party culture. 

## Does the Reasoning for a Moratorium Matter?

As described in Section \ref{section:background}, moratoriums can be the result of a fraternity-related death, a prominent sexual assault, or a behavior violation. There is little reason to expect that moratoriums similar effects across these triggering events. As an illustration, a death may be more salient than a behavior violation,^[Recall that a behavior violation includes hazing, offensive behavior, rule violations, and other disorderly conduct.] resulting in a behavior shock to the college campus. Moreover, both deaths and sexual assaults are less subjective results of risky behavior—a moratorium may seem more justified than an instance of hazing. 

Figure \ref{trigger_reg_graph} shows that the effect of moratoriums is most prominent when a death or sexual assault is the corresponding trigger. In particular, alcohol offenses decline significantly when a fraternity-related death is the triggering event. To ensure that this is the effect of the moratorium rather than the triggering death, I separately analyze (although not shown) the sample restricting to only the universities that experienced a fraternity-related death with an additional 15 universities that experienced a fraternity-related death in the sample period, but *did not* undergo a moratorium.^[These universities were found using Hank Nuwer's repository of hazing-related deaths in the US: https://www.hanknuwer.com/hazing-deaths/.]. Hence, the supplemental universities are those whose students experience the effects of a fraternity-related death, but do not experience a moratorium. Therefore, if the shock of death is the mechanism which produces decreases in alcohol offenses, then the effects of a moratorium on alcohol offenses would be insignificant when including these universities as a control group. However, with the inclusion of these universities, alcohol offenses maintain similar results—decreases in alcohol are significant at the 10% level.

Additionally, Figure \ref{trigger_reg_graph} shows significant decreases in sexual assaults when a triggering event involves either a sexual assault or behavior violation. However, the shortcomings of the estimations underlying these results must be carefully considered. Specifically, sexual assaults are a significantly under-reported offense—survey evidence shows that nearly 80% of sexual assaults go unreported.^[This is based on statistics from the AAU Campus Climate Survey on Sexual Assault and Sexual Misconduct. See here: https://ira.virginia.edu/sites/ias.virginia.edu/files/University%20of%20Virginia_2015_climate_final_report.pdf] Due to this, sexual assaults are relatively rare in police reports, thus resulting in a small number of observations which hinders identification. In addition, these estimates are based on a small subset of universities (19 universities for behavior violations and 10 for sexual assaults). Taken together, the results indicate evidence of decreases in sexual assaults, although this evidence is mostly speculative under these data limitations.
