---
title: "Results"
output: pdf_document
linkcolor: blue
bibliography: "references.bib"
link-citations: yes
---

# Results \label{section:results}

In this section, the estimated causal effects of a fraternity moratorium on alcohol offenses and sexual assaults are reported using OLS. Figure \ref{diff_average_offenses} serves as a preview of the main results and plots the distribution of differences between the number of offenses per-25000 enrolled students on moratorium days and non-moratorium days. On average, most universities observe fewer alcohol offenses and sexual assaults on moratorium days as displayed by the dashed line.

## Main Results \label{section:mainresults}

Table \ref{main_table} reports that fraternity moratoriums lead to substantially fewer alcohol offenses across university campuses and provides suggestive evidence of decreases in sexual assaults. Column (1) shows the baseline specification from Equation \ref{main_model}. This baseline specification includes day of the week, holiday, semester, football game-day, and academic-year fixed effects. Moreover, columns (2) and (3) show the results of adding increasingly flexible fixed effects, although recall from Section \ref{section:approach} that column (2) is the preferred specification. In Panel A, alcohol offenses decrease during moratorium days relative to non-moratorium days in the academic-calendar. Across the three specifications, an average moratorium day exhibits between 26 to 28 percent fewer alcohol offenses in comparison to an average academic-calendar day as reflected in the point estimates. These estimates are statistically significant across all specifications, reemphasizing that moratoriums decrease campus-wide alcohol offenses. Although the point estimates on alcohol offenses are robust, the estimates on sexual assaults fail to achieve statistical significance across each specification. Additionally, the magnitude of each specification varies considerably; sexual assaults show a 14-20 percent reduction from the mean across each estimation. 

The effects of moratoriums are driven by the weekends (Friday-Sunday), consistent with the literature that most college partying occurs on weekends rather than weekdays [@lindo_college_2018]. Columns (4) and (5) of Table \ref{main_table} show the preferred specification (i.e. column (2)) separated by weekends and weekdays. During the weekends, alcohol offenses decrease by 28% relative to an average academic-calendar weekend as shown in Panel A. Nevertheless, weekdays show no statistically significant decreases. Similar to alcohol offenses, the point estimates on sexual assaults show larger decreases on the weekend than on weekdays in Panel B. A weekend during a moratorium can expect 29% fewer sexual assaults relative to an average academic-calendar weekend. This decrease in sexual assaults is significant at the 10% level.

Importantly, these findings persist across a variety of robustness and sensitivity tests. First, given the non-negative count nature of the incident data and the sensitivity of OLS estimation to outliers, Appendix Table \ref{main_table_p} reaffirms the results reported in Table \ref{main_table} using poisson estimation in lieu of OLS. Specifically, poisson estimation shows a statistically significant 27 and 32 percent average reduction in alcohol offenses and sexual assaults on the weekends respectively. Second, to ensure that the results described above are not driven by a single university, Appendix Figures \ref{loo_alc_ols} and \ref{loo_sex_ols} show leave-one-out coefficient estimates for each offense. In particular, 37 unique regressions are estimated for each offense, omitting one university within each iteration—all which demonstrate similar findings to the main results. Finally, recall from Section \ref{section:did} that negative weights occur in the difference-in-difference estimator when treated units are used as control groups. Given that the sample includes only treated universities, I include 14 additional universities in the sample that never underwent a moratorium in the period of analysis to potentially mitigate the negative weighting issue. This amounts to 51 universities for a total of approximately 75,000 academic calendar days. Each of the additional universities are chosen from the Colleges with the Best Greek Life list on Niche.com.^[I use Niche.com since it is the top search result on Google when searching for the "best fraternity colleges". The Princeton Review, notable for its annual list of party schools, does not a list regarding fraternity life.] Never-treated universities are selected if they are regarded as a Top 50 Greek Life school.^[Notably, it is known that at least one university (Chico State) had a moratorium outside of the sample period (2013). This, however, only further validates the selection of the never-treated universities.] Seventeen of these universities are already included in the sample due to experiencing a fraternity moratorium, further justifying the remaining 33 Top 50 Greek Life universities as a good counterfactual. However, only 14 of the these universities are included in the sample while the remaining 17 are excluded since they are unable to provide Daily Crime Logs. Appendix Figures \ref{alc_forest} and \ref{sex_forest} show the effect of moratoriums when including these never-treated universities (see *Main Sample + Never Treated* rows). Overall, the results remain similar, with weekend decreases in alcohol offenses and sexual assaults of approximately 18 percent and 26 percent respectively.



## Are There Spillovers to Nearby Areas? \label{section:spillover}

One potential caveat to the main results in Table \ref{main_table} is that the reported decreases in alcohol offenses and sexual assaults are being displaced to potentially riskier areas. For instance, while campus-wide alcohol is decreasing, it may be that fraternity members and other students are substituting their behaviors on-campus to off-campus areas that are less regulated. If this is true, the net effect of a moratorium may be worse than never implementing a moratorium. Unfortunately, there does not exist a perfect data source to explore such mechanism directly; the National Incidence-Based Reporting System (NIBRS) only reliably covers 24 percent of the sample universities' neighboring police departments and includes only alcohol arrests rather than all incidents.^[In this case, I consider a data source to be reliable if reporting of crime is consistent in the sample period. NIBRS features only nine schools that continually report data without large missing periods.] Furthermore, the Campus Safety and Security (CSS) data, while containing all incidences of crime reported on university campuses, is aggregated to the yearly level. 

Despite these challenges, I perform two sets of analyses using these data. First, to identify whether crime incidence is displaced into nearby areas, I use the NIBRS data to compare the reported incidence of crimes at nearby police departments with the crimes reported at university-specific police departments using the Daily Crime Logs. Nearby police departments are defined as police departments that serve the surrounding area, but are not affiliated directly with a university.^[The neighboring police departments were identified using @lindo_college_2018 public access data files in addition to Jacob Kaplan's NIBRS data tool available here: https://jacobdkaplan.com/nibrs.html#state=Colorado&agency=Denver%20Police%20Department&category=murder_nonnegligent_manslaughter&rate=false] This results in a comparison of nine university police departments from the Daily Crime Logs and their corresponding nearby police departments from the NIBRS. To harmonize the NIBRS data with the Daily Crime Logs, I define each offense from the NIBRS as per-25000 enrolled students at the corresponding university and limit the panel to only academic-calendar days. Both alcohol offenses and sexual assaults are restricted to incidences involving college-aged individuals (i.e., 17-22), although the results are consistent when broadening the definition to include all ages. Moreover, I define sexual assaults in the NIBRS data to include fondling, rape, and sexual assault with an object to align with the definition using the Daily Crime Logs. 

In both Panels A and B of Table \ref{spillover_table}, alcohol offenses and sexual assaults have an insignificant and negative point estimate at nearby police departments, thereby showing no evidence of substantial spillovers. Reassuringly, the university-specific police departments continue to show large and significant effects of the moratorium for alcohol offenses despite being a small subset of the main sample. These results give weight to the interpretation that moratoriums are decreasing the number of alcohol offenses on university campuses and students are not moving their risky behaviors to off-campus areas that are less regulated by the university.

As the second set of analysis, I analyze the CSS data to examine if students substitute partying at fraternity houses to different on-campus locations during moratoriums. The CSS data contains all violations of liquor, drug, and sexual assaults that occur in a calendar-year. The main advantage to using the CSS data is that it delineates between crimes that occur within a residence hall or a different on-campus location. Moreover, the CSS data includes liquor violations that may not have been reported to the university police (thus not in the Daily Crime Logs) if they were handled internally by university staff. For instance, if a liquor violation occurs in a residence hall, this citation will be absent from the Daily Crime Logs if it is handled only by the residence hall staff. However, recall that the biggest disadvantage to this data is the aggregation of all incidents to the calendar-year level. Since moratoriums can last for as few as six days and can continue through multiple calendar-years, this analysis should be taken only as speculative, not causal. See Appendix \ref{asection:spillovers} for a more detailed discussion of the CSS data and the corresponding model.

Using the CSS data, there is evidence that moratoriums move drinking from fraternity houses to residence halls. Residence halls show a 28% *increase* in alcohol offenses relative to the mean when a proportion of a calendar-year is in a moratorium. Interestingly, this is accompanied by a large 82% *decrease* from the mean in residence hall sexual assaults. Although these results appear counterintuitive given the literature documents that alcohol offenses and sexual assaults tend to coincide [@lindo_college_2018], these results point to the possibility that moratoriums cause a substitution effect of partying behavior; students substitute drinking at fraternity houses to residence halls. Residence halls, unlike fraternity houses, are far more regulated, contain university staff, and potentially have more sober bystanders to intervene if behavior appears to be escalating dangerously. Taken together, these results support the notion that *if* moratoriums displace dangerous alcohol-fueled behavior, they displace it to *less* risky areas. 


## Do Moratoriums Have Long-run Effects? \label{section:longrun}

Although moratoriums clearly impact student behavior when implemented, I find no evidence showing that moratoriums provide long-run impacts. In this subsection, I perform two analyses to demonstrate this: first, I conduct an F-test on the lagged coefficients in the event study specification shown in Section \ref{section:approach}, and second, I extend the preferred specification from Table \ref{main_table} with an indicator for the week before and week after a moratorium. 

Table \ref{long_run_effects} reports the results of the first set of analysis which fails to show significant evidence of long-run effects. Panel A includes results from the event study estimation shown in Figures \ref{es_alc} and \ref{es_sex}. In addition, p-values from joint F-tests on the four lagged coefficients are reported. The p-values for both alcohol offenses and sexual assaults are above the 10 percent level of significance, therefore showing little evidence that the effect of the moratorium persists in the four 14-day periods (56 total days) following a moratorium.

While the sample does not collectively exhibit long-run effects, there is potential that longer moratoriums may induce more behavior change than relatively shorter ones. To study this possible heterogeneity, I supplement the analysis above by splitting the sample into three quantiles based on the length of a moratorium. Each quantile represents universities with a moratorium less than 32 academic-calendar days (quantile 1), between 33 and 59 academic-calendar days (quantile 2), and more than 60 academic-calendar days (quantile 3).^[Note that six universities have more than one moratorium and can therefore be included in multiple quantiles. This occurs for five of the six universities. However, this represents a small fraction within each quantile: quantile 1 (20%), quantile 2 (23%), and quantile 3 (26%) ] Panel B of Table \ref{long_run_effects} shows the p-values corresponding to the F-tests on the four lagged coefficients for both alcohol offenses and sexual assaults. Similar to Panel A, there is no statistical significance across each test. Interestingly, there does appear to be evidence that moratoriums with lengths between 33 and 59 days (quantile 2) have the largest instantaneous effect, therefore showing that the length of a moratorium may be crucial to the overall effectiveness.

Last, Figure \ref{week_before_after} reports the estimates from the second analysis which extends specification (2) in Table \ref{main_table} with an indicator variable for the week after and week before a moratorium. When considering the entire sample, each offense exhibits decreases that persist only during the moratorium period and instantaneously return to previous levels in the week directly following a moratorium. This pattern persists when restricting the sample to weekends where the effects of the moratorium are most prominent.  





