---
title: "Tables"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(kableExtra)
```

<!-- \FloatBarrier -->
# Tables

```{r}
source(paste0(here::here("tables/matching_word_table.R")))
```

```{r}
matching_table
```

\newpage
```{r university_characteristics}
source(paste0(here::here("tables/summary_stats_university.R")))
```

```{r, fig.pos = "H"}
## summary_stats
university_characteristics
```

\newpage
```{r}
source(here::here(paste0("tables/regressions_reporting.R")))
```

\begin{landscape}
```{r}
## reporting_table
reporting_table
```
\end{landscape}

```{r}
source(here::here(paste0("tables/regressions_main.R")))
```

```{r}
main_table 
```

```{r}
source(paste0(here::here("tables/regressions_spillovers_compare.R")))
```

\begin{landscape}
```{r}
## reporting_table
spillover_table
```
\end{landscape}


```{r}
source(here::here(paste0("figures/event_study_final_dec13.R")))
```

```{r}
## WARNING!! THIS WILL NOT RUN UNLESS THE FIGURES FILE IS RAN FIRST!!! B/C THIS IS IN EVENT STUDY
long_run_effects
```

```{r}
source(paste0(here::here("tables/regressions_party_schools.R")))
```

```{r}
party_school_table
```


```{r}
source(here::here(paste0("tables/heteroeffects_uni_ifc.R")))
```

```{r}
ifc_uni_table
```

