var gvjs_gN="Invalid state: should be an array of values.",gvjs_hN="No valid DataTable received from draw()",gvjs_iN="Start and end points must be 2D",gvjs_jN="goog-combobox-active",gvjs_kN="goog-flat-button",gvjs_lN="goog-link-button",gvjs_mN="aside",gvjs_nN="belowStacked",gvjs_oN="blockIncrement",gvjs_pN="google-visualization-controls-rangefilter",gvjs_qN="month",gvjs_rN="placeholder",gvjs_sN="uichange",gvjs_tN="useFormattedValue",gvjs_uN="yy/MM/dd hh:mma";
gvjs_1B.prototype.wq=gvjs_W(123,function(a){this.eB=a});gvjs_3D.prototype.wq=gvjs_W(122,function(a){this.eB=a});gvjs_I.prototype.Bg=gvjs_W(13,function(){return this.Rg});function gvjs_vN(a){return new gvjs_u(a.offsetLeft,a.offsetTop)}function gvjs_wN(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];gvjs_qe(d)?gvjs_wN.apply(null,d):gvjs_J(d)}}
function gvjs_nia(a){if(a.altKey&&!a.ctrlKey||a.metaKey||112<=a.keyCode&&123>=a.keyCode)return!1;if(gvjs_5A(a.keyCode))return!0;switch(a.keyCode){case 18:case 20:case 93:case 17:case 40:case 35:case 27:case 36:case 45:case 37:case 224:case 91:case 144:case 12:case 34:case 33:case 19:case 255:case 44:case 39:case 145:case 16:case 38:case 252:case 224:case 92:return!1;case 0:return!gvjs__g;default:return 166>a.keyCode||183<a.keyCode}}function gvjs_xN(){gvjs_2D.call(this);this.pr=[]}gvjs_r(gvjs_xN,gvjs_2D);
gvjs_xN.prototype.add=function(a){gvjs_Le(this.pr,a)||(this.pr.push(a),gvjs_K(a,gvjs_Au,this.Zca,!1,this))};gvjs_xN.prototype.remove=function(a){gvjs_Ne(this.pr,a)&&gvjs_dm(a,gvjs_Au,this.Zca,!1,this)};gvjs_xN.prototype.O=function(){gvjs_s(this.pr,function(a){a.ma()});this.pr.length=0;gvjs_xN.o.O.call(this)};function gvjs_yN(){gvjs_xN.call(this);this.dY=0}gvjs_r(gvjs_yN,gvjs_xN);
gvjs_yN.prototype.play=function(a){if(0==this.pr.length)return!1;if(a||0==this.J)this.dY=0,this.YJ();else if(this.bp())return!1;this.Uh("play");-1==this.J&&this.Uh("resume");var b=-1==this.J&&!a;this.startTime=gvjs_we();this.endTime=null;this.J=1;gvjs_s(this.pr,function(c){b&&-1!=c.J||c.play(a)});return!0};gvjs_yN.prototype.pause=function(){this.bp()&&(gvjs_s(this.pr,function(a){a.bp()&&a.pause()}),this.J=-1,this.Uh("pause"))};
gvjs_yN.prototype.stop=function(a){gvjs_s(this.pr,function(b){0==b.J||b.stop(a)});this.J=0;this.endTime=gvjs_we();this.Uh(gvjs_0p);this.Yz()};gvjs_yN.prototype.Zca=function(){this.dY++;this.dY==this.pr.length&&(this.endTime=gvjs_we(),this.J=0,this.Uh(gvjs_Au),this.Yz())};function gvjs_zN(a,b,c,d,e){gvjs_3D.call(this,b,c,d,e);this.element=a}gvjs_r(gvjs_zN,gvjs_3D);gvjs_=gvjs_zN.prototype;gvjs_.dB=gvjs_ne;gvjs_.vh=function(){void 0===this.tr&&(this.tr=gvjs_4y(this.element));return this.tr};
gvjs_.Y0=function(){this.dB();gvjs_zN.o.Y0.call(this)};gvjs_.Yz=function(){this.dB();gvjs_zN.o.Yz.call(this)};gvjs_.YJ=function(){this.dB();gvjs_zN.o.YJ.call(this)};function gvjs_AN(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error(gvjs_iN);gvjs_zN.call(this,a,b,c,d,e)}gvjs_r(gvjs_AN,gvjs_zN);gvjs_AN.prototype.dB=function(){var a=this.eB&&this.vh()?gvjs_h:gvjs_dd;this.element.style[a]=Math.round(this.coords[0])+gvjs_U;this.element.style.top=Math.round(this.coords[1])+gvjs_U};
function gvjs_BN(a,b,c,d,e){gvjs_zN.call(this,a,[b],[c],d,e)}gvjs_r(gvjs_BN,gvjs_zN);gvjs_BN.prototype.dB=function(){this.element.style.width=Math.round(this.coords[0])+gvjs_U};function gvjs_CN(a,b,c,d,e){gvjs_zN.call(this,a,[b],[c],d,e)}gvjs_r(gvjs_CN,gvjs_zN);gvjs_CN.prototype.dB=function(){this.element.style.height=Math.round(this.coords[0])+gvjs_U};function gvjs_DN(){gvjs_jm.call(this)}gvjs_r(gvjs_DN,gvjs_jm);gvjs_=gvjs_DN.prototype;gvjs_.ce=0;gvjs_.kp=0;gvjs_.Gn=100;gvjs_.Yl=0;gvjs_.Dj=1;
gvjs_.ol=!1;gvjs_.Qz=!1;gvjs_.Wa=function(a){a=gvjs_EN(this,a);this.ce!=a&&(this.ce=a+this.Yl>this.Gn?this.Gn-this.Yl:a<this.kp?this.kp:a,this.ol||this.Qz||this.dispatchEvent(gvjs_Lt))};gvjs_.getValue=function(){return gvjs_EN(this,this.ce)};gvjs_.aT=function(a){a=gvjs_EN(this,a);this.Yl!=a&&(this.Yl=0>a?0:this.ce+a>this.Gn?this.Gn-this.ce:a,this.ol||this.Qz||this.dispatchEvent(gvjs_Lt))};gvjs_.em=function(){var a=this.Yl;return null==this.Dj?a:Math.round(a/this.Dj)*this.Dj};
gvjs_.Mw=function(a){if(this.kp!=a){var b=this.ol;this.ol=!0;this.kp=a;a+this.Yl>this.Gn&&(this.Yl=this.Gn-this.kp);a>this.ce&&this.Wa(a);a>this.Gn&&(this.Yl=0,this.iu(a),this.Wa(a));(this.ol=b)||this.Qz||this.dispatchEvent(gvjs_Lt)}};gvjs_.yf=function(){return gvjs_EN(this,this.kp)};
gvjs_.iu=function(a){a=gvjs_EN(this,a);if(this.Gn!=a){var b=this.ol;this.ol=!0;this.Gn=a;a<this.ce+this.Yl&&this.Wa(a-this.Yl);a<this.kp&&(this.Yl=0,this.Mw(a),this.Wa(this.Gn));a<this.kp+this.Yl&&(this.Yl=this.Gn-this.kp);(this.ol=b)||this.Qz||this.dispatchEvent(gvjs_Lt)}};gvjs_.xf=function(){return gvjs_EN(this,this.Gn)};gvjs_.mI=function(){return this.Dj};
gvjs_.mT=function(a){this.Dj!=a&&(this.Dj=a,a=this.ol,this.ol=!0,this.iu(this.xf()),this.aT(this.em()),this.Wa(this.getValue()),(this.ol=a)||this.Qz||this.dispatchEvent(gvjs_Lt))};function gvjs_EN(a,b){return null==a.Dj?b:a.kp+Math.round((b-a.kp)/a.Dj)*a.Dj}function gvjs_FN(a,b){gvjs_OB.call(this,a);this.Z5=null;this.$e=new gvjs_DN;this.ssa=b||gvjs_Ze;this.Yna=!0;gvjs_K(this.$e,gvjs_Lt,this.U$,!1,this)}gvjs_r(gvjs_FN,gvjs_OB);gvjs_=gvjs_FN.prototype;gvjs_.ub=gvjs_0;gvjs_.$P=!1;gvjs_.E0=!1;
gvjs_.Sm=10;gvjs_.$Q=0;gvjs_.aba=!0;gvjs_.zca=0;gvjs_.Qia=1E3;gvjs_.yg=!0;gvjs_.Zl=!1;gvjs_.K=function(){gvjs_FN.o.K.call(this);var a=this.xa().K(gvjs_b,this.ra(this.ub));this.Jf(a)};
gvjs_.Jf=function(a){gvjs_FN.o.Jf.call(this,a);gvjs_XB(a,this.ra(this.ub));a=this.j();var b=this.xa().K(gvjs_b,"google-visualization-controls-slider-handle");gvjs_fB(b,gvjs_Ct);this.nC=b;a.appendChild(this.nC);this.Pd=gvjs_GN(this);a.appendChild(this.Pd);this.ij=gvjs_GN(this);a.appendChild(this.ij);a=this.j();gvjs_fB(a,"slider");gvjs_HN(this)};
gvjs_.Ob=function(){gvjs_FN.o.Ob.call(this);this.Nm=new gvjs_1B(this.Pd);this.xq=new gvjs_1B(this.ij);this.Nm.wq(this.Zl);this.xq.wq(this.Zl);this.Nm.ly=this.xq.ly=gvjs_ne;this.Tf=new gvjs_vC(this.j());gvjs_IN(this,!0);this.j().tabIndex=0;gvjs_JN(this)};
function gvjs_IN(a,b){b?(a.jc().D(a.Nm,gvjs_qt,a.qP).D(a.xq,gvjs_qt,a.qP).D(a.Nm,[gvjs_1,gvjs_T],a.Jv).D(a.xq,[gvjs_1,gvjs_T],a.Jv).D(a.Tf,gvjs_mv,a.yn).D(a.j(),gvjs_1t,a.tP).D(a.j(),gvjs_kd,a.tP),a.aba&&gvjs_KN(a,!0)):(a.jc().Ab(a.Nm,gvjs_qt,a.qP).Ab(a.xq,gvjs_qt,a.qP).Ab(a.Nm,[gvjs_1,gvjs_T],a.Jv).Ab(a.xq,[gvjs_1,gvjs_T],a.Jv).Ab(a.Tf,gvjs_mv,a.yn).Ab(a.j(),gvjs_1t,a.tP).Ab(a.j(),gvjs_kd,a.tP),a.aba&&gvjs_KN(a,!1))}gvjs_.Te=function(){gvjs_FN.o.Te.call(this);gvjs_wN(this.Nm,this.xq,this.Tf,this.Hn)};
gvjs_.qP=function(a){var b=a.FX==this.Nm?this.Pd:this.ij;if(this.ub==gvjs_V){var c=this.j().clientHeight-b.offsetHeight;c=(c-a.top)/c*(this.xf()-this.yf())+this.yf()}else c=this.j().clientWidth-b.offsetWidth,c=a.left/c*(this.xf()-this.yf())+this.yf();c=a.FX==this.Nm?Math.min(Math.max(c,this.yf()),this.getValue()+this.em()):Math.min(Math.max(c,this.getValue()),this.xf());gvjs_LN(this,b,c)};
gvjs_.Jv=function(a){var b=a.type==gvjs_1;gvjs_0B(this.j(),"goog-slider-dragging",b);gvjs_0B(a.target.SC,"goog-slider-thumb-dragging",b);a=a.FX==this.Nm;b?(this.dispatchEvent("e"),this.dispatchEvent(a?"a":"c")):(this.dispatchEvent("f"),this.dispatchEvent(a?"b":"d"))};
gvjs_.yn=function(a){var b=!0;switch(a.keyCode){case 36:gvjs_MN(this,this.yf());break;case 35:gvjs_MN(this,this.xf());break;case 33:gvjs_NN(this,this.Sm);break;case 34:gvjs_NN(this,-this.Sm);break;case 37:var c=this.Zl&&this.vh()?1:-1;gvjs_NN(this,a.shiftKey?c*this.Sm:c*this.aB);break;case 40:gvjs_NN(this,a.shiftKey?-this.Sm:-this.aB);break;case 39:c=this.Zl&&this.vh()?-1:1;gvjs_NN(this,a.shiftKey?c*this.Sm:c*this.aB);break;case 38:gvjs_NN(this,a.shiftKey?this.Sm:this.aB);break;default:b=!1}b&&a.preventDefault()};
gvjs_.tP=function(a){this.Yna&&this.j().focus&&this.j().focus();var b=a.target;gvjs_Eh(this.Pd,b)||gvjs_Eh(this.ij,b)||(b=a.type==gvjs_1t,b&&gvjs_we()<this.zca+this.Qia||(b||(this.zca=gvjs_we()),this.E0?gvjs_MN(this,gvjs_ON(this,a)):(this.Y3(a),this.$n=gvjs_PN(this,gvjs_ON(this,a)),this.Gaa=this.ub==gvjs_V?this.Dz<this.$n.offsetTop:this.Dz>gvjs_QN(this,this.$n)+this.$n.offsetWidth,a=gvjs_hh(this.j()),this.jc().D(a,gvjs_qd,this.W3,!0).D(this.j(),gvjs_nd,this.Y3),this.Sv||(this.Sv=new gvjs_2A(200),
this.jc().D(this.Sv,gvjs_cx,this.$$)),this.$$(),this.Sv.start())))};gvjs_.Q$=function(a){gvjs_NN(this,(0<a.detail?-1:1)*this.aB);a.preventDefault()};
gvjs_.$$=function(){var a;if(this.ub==gvjs_V){var b=this.Dz,c=this.$n.offsetTop;this.Gaa?b<c&&(a=gvjs_RN(this,this.$n)+this.Sm):b>c+this.$n.offsetHeight&&(a=gvjs_RN(this,this.$n)-this.Sm)}else b=this.Dz,c=gvjs_QN(this,this.$n),this.Gaa?b>c+this.$n.offsetWidth&&(a=gvjs_RN(this,this.$n)+this.Sm):b<c&&(a=gvjs_RN(this,this.$n)-this.Sm);void 0!==a&&gvjs_LN(this,this.$n,a)};gvjs_.W3=function(){this.Sv&&this.Sv.stop();var a=gvjs_hh(this.j());this.jc().Ab(a,gvjs_qd,this.W3,!0).Ab(this.j(),gvjs_nd,this.Y3)};
function gvjs_SN(a,b){b=gvjs_dy(b,a.j());return a.ub==gvjs_V?b.y:a.Zl&&a.vh()?a.j().clientWidth-b.x:b.x}gvjs_.Y3=function(a){this.Dz=gvjs_SN(this,a)};function gvjs_ON(a,b){var c=a.yf(),d=a.xf();if(a.ub==gvjs_V){var e=a.Pd.offsetHeight,f=a.j().clientHeight-e;a=gvjs_SN(a,b)-e/2;return(d-c)*(f-a)/f+c}e=a.Pd.offsetWidth;f=a.j().clientWidth-e;a=gvjs_SN(a,b)-e/2;return(d-c)*a/f+c}
function gvjs_RN(a,b){if(b==a.Pd)return a.$e.getValue();if(b==a.ij)return a.$e.getValue()+a.$e.em();throw Error("Illegal thumb element. Neither minThumb nor maxThumb");}function gvjs_NN(a,b){Math.abs(b)<a.mI()&&(b=gvjs_3x(b)*a.mI());var c=gvjs_RN(a,a.Pd)+b;b=gvjs_RN(a,a.ij)+b;c=gvjs_0e(c,a.yf(),a.xf()-a.$Q);b=gvjs_0e(b,a.yf()+a.$Q,a.xf());gvjs_TN(a,c,b-c)}
function gvjs_LN(a,b,c){var d=gvjs_EN(a.$e,c);c=b==a.Pd?d:a.$e.getValue();b=b==a.ij?d:a.$e.getValue()+a.$e.em();c>=a.yf()&&b>=c+a.$Q&&a.xf()>=b&&gvjs_TN(a,c,b-c)}function gvjs_TN(a,b,c){a.yf()<=b&&b<=a.xf()-c&&a.$Q<=c&&c<=a.xf()-b&&(b!=a.getValue()||c!=a.em())&&(a.$e.Qz=!0,a.$e.aT(0),a.$e.Wa(b),a.$e.aT(c),a.$e.Qz=!1,a.U$(null))}gvjs_.yf=function(){return this.$e.yf()};gvjs_.Mw=function(a){this.$e.Mw(a)};gvjs_.xf=function(){return this.$e.xf()};gvjs_.iu=function(a){this.$e.iu(a)};
function gvjs_PN(a,b){return b<=a.$e.getValue()+a.$e.em()/2?a.Pd:a.ij}gvjs_.U$=function(){gvjs_JN(this);gvjs_HN(this);this.dispatchEvent(gvjs_Lt)};
function gvjs_JN(a){if(a.Pd&&!a.$P){var b=gvjs_UN(a,gvjs_RN(a,a.Pd)),c=gvjs_UN(a,gvjs_RN(a,a.ij));if(a.ub==gvjs_V)a.Pd.style.top=b.y+gvjs_U,a.ij.style.top=c.y+gvjs_U,a.Gg&&(b=gvjs_VN(c.y,b.y,a.Pd.offsetHeight),a.Gg.style.top=b.offset+gvjs_U,a.Gg.style.height=b.size+gvjs_U);else{var d=a.Zl&&a.vh()?gvjs_h:gvjs_dd;a.Pd.style[d]=b.x+gvjs_U;a.ij.style[d]=c.x+gvjs_U;a.Gg&&(b=gvjs_VN(b.x,c.x,a.Pd.offsetWidth),a.Gg.style[d]=b.offset+gvjs_U,a.Gg.style.width=b.size+gvjs_U)}}}
function gvjs_VN(a,b,c){var d=Math.ceil(c/2);return{offset:a+d,size:Math.max(b-a+c-2*d,0)}}function gvjs_UN(a,b){var c=new gvjs_u;if(a.Pd){var d=a.yf(),e=a.xf();b=b==d&&d==e?0:(b-d)/(e-d);a.ub==gvjs_V?(d=a.Pd.offsetHeight,d=a.j().clientHeight-d,b=Math.round(b*d),c.x=a.E0?0:gvjs_QN(a,a.Pd),c.y=d-b):(d=a.j().clientWidth-a.Pd.offsetWidth,c.x=Math.round(b*d),c.y=a.E0?0:a.Pd.offsetTop)}return c}
function gvjs_MN(a,b){b=gvjs_0e(b,a.yf(),a.xf());a.$P&&(a.rH.stop(!0),a.rH.ma());var c=new gvjs_yN,d=gvjs_PN(a,b),e=a.getValue(),f=a.em(),g=gvjs_RN(a,d),h=gvjs_UN(a,g);var k=a.mI();Math.abs(b-g)<k&&(b=gvjs_0e(g+(b>g?k:-k),a.yf(),a.xf()));gvjs_LN(a,d,b);g=gvjs_UN(a,gvjs_RN(a,d));k=a.ub==gvjs_V?[gvjs_QN(a,d),g.y]:[g.x,d.offsetTop];h=new gvjs_AN(d,[h.x,h.y],k,100);h.wq(a.Zl);c.add(h);a.Gg&&gvjs_oia(a,d,e,f,g,c);a.Z5&&(b=a.Z5.jCa(e,b,100),gvjs_s(b,function(l){c.add(l)}));a.rH=c;a.jc().D(c,gvjs_T,a.Ana);
a.$P=!0;c.play(!1)}
function gvjs_oia(a,b,c,d,e,f){var g=gvjs_UN(a,c),h=gvjs_UN(a,c+d);c=g;d=h;b==a.Pd?c=e:d=e;a.ub==gvjs_V?(b=gvjs_VN(h.y,g.y,a.Pd.offsetHeight),g=gvjs_VN(d.y,c.y,a.Pd.offsetHeight),e=new gvjs_AN(a.Gg,[gvjs_QN(a,a.Gg),b.offset],[gvjs_QN(a,a.Gg),g.offset],100),b=new gvjs_CN(a.Gg,b.size,g.size,100),e.wq(a.Zl),b.wq(a.Zl),f.add(e),f.add(b)):(b=gvjs_VN(g.x,h.x,a.Pd.offsetWidth),g=gvjs_VN(c.x,d.x,a.Pd.offsetWidth),e=new gvjs_AN(a.Gg,[b.offset,a.Gg.offsetTop],[g.offset,a.Gg.offsetTop],100),b=new gvjs_BN(a.Gg,
b.size,g.size,100),e.wq(a.Zl),b.wq(a.Zl),f.add(e),f.add(b))}gvjs_.Ana=function(){this.$P=!1;this.dispatchEvent("g")};gvjs_.setOrientation=function(a){if(this.ub!=a){var b=this.ra(this.ub),c=this.ra(a);this.ub=a;this.j()&&(a=this.j(),gvjs_WB(a,b)&&(gvjs_ZB(a,b),gvjs_XB(a,c)),b=this.Zl&&this.vh()?gvjs_h:gvjs_dd,this.Pd.style[b]=this.Pd.style.top="",this.ij.style[b]=this.ij.style.top="",this.Gg&&(this.Gg.style[b]=this.Gg.style.top="",this.Gg.style.width=this.Gg.style.height=""),gvjs_JN(this))}};
gvjs_.Ei=function(){return this.ub};gvjs_.O=function(){gvjs_FN.o.O.call(this);this.Sv&&this.Sv.ma();delete this.Sv;this.rH&&this.rH.ma();delete this.rH;delete this.Pd;delete this.ij;this.Gg&&delete this.Gg;this.$e.ma();delete this.$e;this.Tf&&(this.Tf.ma(),delete this.Tf);this.Hn&&(this.Hn.ma(),delete this.Hn);this.Nm&&(this.Nm.ma(),delete this.Nm);this.xq&&(this.xq.ma(),delete this.xq)};gvjs_.aB=1;gvjs_.mI=function(){return this.$e.mI()};gvjs_.mT=function(a){this.$e.mT(a)};gvjs_.getValue=function(){return this.$e.getValue()};
gvjs_.Wa=function(a){gvjs_LN(this,this.Pd,a)};gvjs_.em=function(){return this.$e.em()};gvjs_.aT=function(a){gvjs_LN(this,this.ij,this.$e.getValue()+a)};gvjs_.setVisible=function(a){gvjs_4(this.j(),a);a&&gvjs_JN(this)};function gvjs_HN(a){var b=a.j();b&&(gvjs_Wq(b,"valuemin",a.yf()),gvjs_Wq(b,"valuemax",a.xf()),gvjs_Wq(b,"valuenow",a.getValue()),gvjs_Wq(b,"valuetext",a.ssa(a.getValue())||""))}
function gvjs_KN(a,b){b?(a.Hn||(a.Hn=new gvjs_VD(a.j())),a.jc().D(a.Hn,gvjs_Vv,a.Q$,{passive:!1})):a.jc().Ab(a.Hn,gvjs_Vv,a.Q$,{passive:!1})}gvjs_.Hb=function(a){this.yg!=a&&this.dispatchEvent(a?gvjs_vu:gvjs_ou)&&(this.yg=a,gvjs_IN(this,a),a||this.W3(),gvjs_0B(this.j(),"goog-slider-disabled",!a))};gvjs_.isEnabled=function(){return this.yg};function gvjs_QN(a,b){return a.Zl?gvjs_4A(b):b.offsetLeft}var gvjs_pia={rM:gvjs_V,nM:gvjs_0};
function gvjs_WN(a){gvjs_I.call(this);this.ia=a;this.aa=new gvjs_Jq(this)}gvjs_r(gvjs_WN,gvjs_I);gvjs_=gvjs_WN.prototype;gvjs_.O=function(){this.clear();gvjs_WN.o.O.call(this)};gvjs_.clear=function(){this.aa.removeAll();gvjs_J(this.aa);gvjs_uh(this.ia)};gvjs_.getContainer=function(){return this.ia};gvjs_.addEventListener=function(a,b,c,d,e){e?gvjs_Lq(this.aa,a,b,c,d,e):this.aa.D(a,b,c,d)};gvjs_.draw=function(){};gvjs_.getState=function(){return{}};function gvjs_XN(a){gvjs_O.call(this,a);this.G8=[]}gvjs_r(gvjs_XN,gvjs_O);gvjs_=gvjs_XN.prototype;gvjs_.O=function(){this.clear();gvjs_XN.o.O.call(this)};gvjs_.clear=function(){this.nf()};gvjs_.nf=function(){this.HL&&(gvjs_3m(this.HL),gvjs_J(this.HL),this.HL=null);gvjs_J(this.Tc);this.Tc=null;gvjs_uh(this.container)};gvjs_.qa=null;gvjs_.xu=null;gvjs_.m=null;gvjs_.Tc=null;gvjs_.HL=null;gvjs_.a5=null;gvjs_.J=null;gvjs_.Tv=null;gvjs_.Xa=function(){return this.qa};gvjs_.cd=function(){return this.m};
gvjs_.Mf=function(){return{}};gvjs_.hm=function(a,b){return gvjs_Gy(b,"ui",{})};gvjs_.gt=function(){return""};gvjs_.ifa=function(a){this.G8=a};gvjs_.VO=function(){return this.G8};gvjs_.nr=function(){};gvjs_.getState=function(){return this.J?gvjs_Sg(gvjs_Pg(this.J)):null};gvjs_.draw=function(a,b,c){gvjs_Aj(a);this.qa=a;this.xu=b||{};this.a5=c||{};gvjs_6m(this.Ai,this.kC,this)};
gvjs_.kC=function(){if(this.qa){this.J=this.a5||{};if(!gvjs_p(this.J))throw Error("Control state must be an object.");this.Tv=this.Tv||this.J;this.m=new gvjs_ji([this.xu,this.Mf()||{}]);this.nr(this.qa,this.m,this.J);if(!this.Tc){var a=gvjs_D(this.m,"ui.type",this.gt());this.Tc=(a=gvjs_vl(a))?new a(this.container):null;if(!this.Tc)throw Error("Invalid Ui instance.");this.HL=gvjs_Ym(this.Tc,gvjs_sN,gvjs_q(this.rya,this))}this.Tc.draw(this.J,this.hm(this.qa,this.m));this.J=this.Tc.getState();gvjs_N(this,
gvjs_g,null)}};gvjs_.rya=function(a){this.J=this.Tc.getState();gvjs_N(this,gvjs_Kd,a)};gvjs_.Yt=function(){gvjs_6m(this.Ai,this.wva,this)};gvjs_.wva=function(){this.Tv&&(this.a5=this.Tv,this.kC())};function gvjs_YN(a,b){this.W4=a;this.pf=b}gvjs_YN.prototype.getUrl=function(){return this.W4};gvjs_YN.prototype.nd=function(a){return this.pf[a].id};gvjs_YN.prototype.Y=function(a){return this.pf[a].type};gvjs_YN.prototype.Z=function(){return this.pf.length};function gvjs_qia(a,b){var c=new gvjs_ym(a);c.wl("limit 1");c.send(function(d){if(d.mk())b(null);else{var e=[];d=d.Xa();for(var f=0;f<d.Z();f++)e.push({id:d.nd(f),type:d.Y(f)});b(new gvjs_YN(a,e))}})};function gvjs_ZN(a,b){this.Xh=[];this.R=a;this.oea=b||null;this.tba=(this.oea||this.R.Xa()).Y(0)==gvjs_Qb?"second":gvjs_Pb}var gvjs__N=["year",gvjs_qN,"day","hour","minute","second"],gvjs_0N=[function(a){return a.getFullYear()},function(a){return a.getMonth()+1},function(a){return a.getDate()},function(a){return a.getHours()},function(a){return a.getMinutes()},function(a){return a.getSeconds()}],gvjs_ria=[gvjs_Xa,gvjs_Ha,gvjs__a,gvjs_pa,gvjs_0a,"June","July",gvjs_sa,gvjs_db,gvjs_5a,gvjs_3a,gvjs_Ea];
function gvjs_sia(a,b){function c(e){b(new gvjs_ZN(a,e))}if(a.Xa())c(null);else{var d=a.df;if(d)gvjs_qia(d,c);else throw Error("Wrapper should hold dataTable or dataSourceUrl");}}function gvjs_tia(a,b){var c=gvjs_uo||gvjs_uo;b=b||function(f){return f};for(var d=[],e=1;e<a.Z();e++)d.push({column:e,aggregation:c,type:a.Y(e),label:a.Ca(e),id:a.nd(e)});return gvjs_xo(a,[{column:0,modifier:b,type:gvjs_f,label:a.Ca(0),id:a.nd(0)}],d)}
gvjs_ZN.prototype.qG=function(){var a=this.R.ao();a=new gvjs_Q(a);var b=a.Xa();if(null!=b){for(var c=this.Xh,d=0;d<b.ca();d++){a:{var e=this.Xh;for(var f=b.getValue(d,0),g=0;g<e.length;g++){var h=e[g];gvjs__N[g]==gvjs_qN&&h++;if(gvjs_0N[g](f)!=h){e=!1;break a}}e=!0}e||(b.oA(d),d--)}b=gvjs_tia(b,gvjs_0N[c.length]);a.eh(b)}else{b=this.oea;b.Y(0)==gvjs_Pb&&(this.tba="day");c="select "+gvjs_1N(this)+"("+b.nd(0)+")";gvjs_1N(this)==gvjs_qN&&(c+=" + 1");for(d=1;d<b.Z();d++)c+=", sum("+b.nd(d)+")";b=[c,gvjs_uia(this,
b),"group by "+gvjs_1N(this)+"("+b.nd(0)+")",gvjs_via(this,b)].join(" ");a.wl(b)}return a};gvjs_ZN.prototype.pO=function(a){var b=gvjs_1N(this);if(b==this.tba)return!1;b==gvjs_qN&&a--;this.Xh.push(a);return!0};gvjs_ZN.prototype.rollup=function(){return 0<this.Xh.length?(this.Xh.pop(),!0):!1};function gvjs_1N(a){return gvjs__N[a.Xh.length]}
function gvjs_wia(a){var b=[];0<a.Xh.length&&b.push(String(a.Xh[0]));if(1<a.Xh.length){var c=a.Xh[1];c=gvjs_ria[c];b.push(String(c))}2<a.Xh.length&&b.push(String(a.Xh[2]));3<a.Xh.length&&(c=a.Xh[3],a=a.Xh[4]||"00",a=String(a),1==a.length&&(a="0"+a),b.push(c+":"+a));return b.join(" ")}function gvjs_uia(a,b){if(0==a.Xh.length)return"";for(var c=[],d=0;d<a.Xh.length;d++)c.push(gvjs__N[d]+"("+b.nd(0)+") = "+a.Xh[d]);return"where "+c.join(gvjs_rr)}
function gvjs_via(a,b){b="order by "+gvjs_1N(a)+"("+b.nd(0)+")";gvjs_1N(a)==gvjs_qN&&(b+=" + 1");return b};function gvjs_2N(a){this.ia=a}gvjs_=gvjs_2N.prototype;gvjs_.bn=null;gvjs_.R=null;gvjs_.draw=function(a){var b=this;gvjs_sia(a,function(c){b.bn=c;b.cB()})};gvjs_.rollup=function(){null!=this.bn&&null!=this.R&&this.bn.rollup()&&this.cB()};gvjs_.pO=function(a){(a=this.bn.pO(a))&&this.cB();return a};gvjs_.Kqa=function(){var a=this.R.vf().getSelection()[0].row;a=this.R.gP().Xa().getValue(a,0);this.pO(a)};
gvjs_.cB=function(){this.R&&gvjs_4m(this.R);var a=this.R=this.bn.qG(),b=this.R,c=b.getOption(gvjs_1u)||{};c.title=gvjs_1N(this.bn);b.$(gvjs_1u,c);b.$(gvjs_ex,gvjs_wia(this.bn));a.$(gvjs_7c,!0);b=gvjs_q(this.Kqa,this);gvjs_Ym(a,gvjs_i,b);a.draw(this.ia)};function gvjs_3N(a){gvjs_XN.call(this,a)}gvjs_r(gvjs_3N,gvjs_XN);gvjs_3N.prototype.qG=function(){return this.apply()};gvjs_3N.prototype.apply=function(){if(!this.Xa())throw Error(gvjs_hN);return this.q6(this.Xa(),this.cd(),this.getState())};gvjs_3N.prototype.q6=function(a){return a};function gvjs_4N(a){gvjs_XN.call(this,a)}gvjs_r(gvjs_4N,gvjs_3N);gvjs_4N.prototype.bn=null;gvjs_4N.prototype.q6=function(a,b,c){a=c.targetValue;"drilldown"==c.action?typeof a===gvjs_f&&this.bn.pO(a):this.bn.rollup();c=this.bn.qG().Xa();if(null==c)throw"Operator could not be applied to null data table.";return c};gvjs_4N.prototype.gt=function(){return"DrilldownOperatorUi"};gvjs_4N.prototype.nr=function(a){this.clear();this.bn=new gvjs_ZN(new gvjs_Q({qb:a}))};
function gvjs_5N(a){gvjs_WN.call(this,a)}gvjs_r(gvjs_5N,gvjs_WN);gvjs_5N.prototype.Qf=null;gvjs_5N.prototype.getState=function(){if(!this.Qf)return{};var a=this.Qf?this.Qf.value:"{}";try{a=gvjs_Ng(a)}catch(b){}return a=gvjs_p(a)?a:{}};gvjs_5N.prototype.draw=function(a){this.Qf=this.PW(a);this.getContainer().appendChild(this.Qf)};
gvjs_5N.prototype.PW=function(a){var b=this,c=gvjs_z(gvjs_Qa);c.setAttribute(gvjs_9c,gvjs_te(this.getContainer())+"-input");a&&(c.value=gvjs_Og(a));this.addEventListener(c,gvjs_1o,function(){gvjs_N(b,gvjs_sN,null)},!1);return c};function gvjs_6N(a){gvjs_XN.call(this,a);this.oT=[]}gvjs_r(gvjs_6N,gvjs_XN);gvjs_6N.prototype.nr=function(){this.clear();this.oT=this.cd().ea("setters")||[]};gvjs_6N.prototype.apply=function(){return this.vV(this.Xa(),this.cd(),this.getState())};gvjs_6N.prototype.vV=function(a,b,c){gvjs_s(this.VO(),function(d){gvjs_s(this.oT,function(e){d.setProperty(e.output,c[e.input])},this)},this);return a};function gvjs_7N(a){gvjs_6N.call(this,a)}gvjs_r(gvjs_7N,gvjs_6N);gvjs_=gvjs_7N.prototype;gvjs_.Ya=null;gvjs_.Cb=null;gvjs_.hm=function(a,b){a=gvjs_7N.o.hm.call(this,a,b);a.minValue=this.Ya;a.maxValue=this.Cb;null==a.label&&(a.label="");return a};gvjs_.nr=function(a,b,c){this.Ya=gvjs_F(b,gvjs_id);this.Cb=gvjs_F(b,gvjs_gd);this.oT=[{input:"lowValue",mg:gvjs_D(b,"lowKey")},{input:"highValue",mg:gvjs_D(b,"highKey")}];this.WL(c)};
gvjs_.WL=function(a){if(a.lowThumbAtMinimum)a.lowValue=this.Ya;else{var b=gvjs_Lg(String(a.lowValue));isNaN(b)&&(b=Number.NEGATIVE_INFINITY);a.lowValue=gvjs_0e(b,this.Ya,this.Cb)}a.highThumbAtMaximum?a.highValue=this.Cb:(b=gvjs_Lg(String(a.highValue)),isNaN(b)&&(b=Number.POSITIVE_INFINITY),a.highValue=gvjs_0e(b,this.Ya,this.Cb))};function gvjs_8N(a){gvjs_XN.call(this,a)}gvjs_r(gvjs_8N,gvjs_XN);gvjs_8N.prototype.yB=function(){return this.apply()};gvjs_8N.prototype.apply=function(){if(!this.Xa())throw Error(gvjs_hN);return this.pG(this.Xa(),this.cd(),this.getState())};gvjs_8N.prototype.pG=function(a){return new gvjs_L(a)};function gvjs_9N(a){gvjs_XN.call(this,a);this.De=-1}gvjs_r(gvjs_9N,gvjs_8N);gvjs_=gvjs_9N.prototype;gvjs_.zq=null;gvjs_.Ya=null;gvjs_.Cb=null;gvjs_.hT=function(a){this.Ya=a};gvjs_.gT=function(a){this.Cb=a};function gvjs_$N(a,b){if(b.lowThumbAtMinimum)b.lowValue=a.Ya;else{var c=a.d5(b.lowValue);isNaN(c)&&(c=Number.NEGATIVE_INFINITY);b.lowValue=gvjs_0e(c,a.Ya,a.Cb)}b.highThumbAtMaximum?b.highValue=a.Cb:(c=a.d5(b.highValue),isNaN(c)&&(c=Number.POSITIVE_INFINITY),b.highValue=gvjs_0e(c,a.Ya,a.Cb))}
gvjs_.pG=function(a,b,c){a=new gvjs_L(a);b={column:this.De,test:this.MY(b,c.lowValue.valueOf(),c.highValue.valueOf())};a.Ap(a.it([b]));return a};gvjs_.MY=function(a,b,c){return function(d){return b<=d&&c>=d}};function gvjs_aO(a){gvjs_FN.call(this,a)}gvjs_r(gvjs_aO,gvjs_FN);gvjs_aO.prototype.nC=null;gvjs_aO.prototype.ra=function(a){return a==gvjs_V?"google-visualization-controls-slider-vertical":"google-visualization-controls-slider-horizontal"};gvjs_aO.prototype.Ob=function(){gvjs_aO.o.Ob.call(this);this.jc().D(this,gvjs_Lt,gvjs_q(this.Qga,this));this.Qga()};
gvjs_aO.prototype.Qga=function(){var a=gvjs_vN(this.Pd),b=gvjs_vN(this.ij);this.Ei()==gvjs_V?(this.nC.style.height=gvjs_Bq(Math.abs(b.y-a.y),!0),this.nC.style.top=Math.min(b.y,a.y)+gvjs_U):(gvjs_Dq(this.nC,Math.abs(b.x-a.x)),this.nC.style.left=Math.min(b.x,a.x)+gvjs_U)};function gvjs_GN(a){a=a.xa().K(gvjs_b,"google-visualization-controls-slider-thumb");gvjs_fB(a,gvjs_Ct);return a};function gvjs_bO(a){gvjs_WN.call(this,a);this.Tp=this.Jm=0}gvjs_r(gvjs_bO,gvjs_WN);gvjs_=gvjs_bO.prototype;gvjs_.O=function(){gvjs_J(this.Jm);gvjs_J(this.Lc);gvjs_bO.o.O.call(this)};gvjs_.gw=null;gvjs_.Pv=null;gvjs_.Lc=null;gvjs_.getState=function(){if(!this.Lc)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var a=this.Lc.getValue(),b=this.Lc.em();return{lowValue:a+this.Tp,highValue:a+b+this.Tp,lowThumbAtMinimum:a===this.Lc.yf(),highThumbAtMaximum:a+b===this.Lc.xf()}};
function gvjs_cO(){return gvjs_z(gvjs_$a,{"class":"google-visualization-controls-rangefilter-thumblabel"},"-")}gvjs_.jxa=function(){this.U4();this.Jm&&gvjs_mm(this.Jm);this.Jm=gvjs_lm(function(){this.Jm=0;gvjs_N(this,gvjs_sN,null)},200,this)};
function gvjs_dO(a,b,c,d,e){var f=gvjs_E(d,"showRangeValues");e=gvjs_D(d,gvjs_7v,e.orientation,gvjs_pia);var g=new gvjs_OB;b.Ja(g,!0);gvjs_XB(g.j(),gvjs_Y);f&&(e===gvjs_0?(a.gw=gvjs_cO(),g.ib().appendChild(a.gw)):(a.Pv=gvjs_cO(),g.ib().appendChild(a.Pv)));b=new gvjs_aO;gvjs_J(a.Lc);a.Lc=b;a.rfa(d);b=a.SY(d,gvjs_id);var h=a.SY(d,gvjs_gd);if(null==b||null==h)throw Error("minValue and maxValue must be specified");c=a.Qda(b,h,c);b=c.minValue;h=c.maxValue;c=c.state;a.Tp=b;h-=a.Tp;c.lowValue-=a.Tp;c.highValue-=
a.Tp;a.Lc.Mw(0);a.Lc.iu(h);a.Lc.setOrientation(e);b=c.lowThumbAtMinimum?a.Lc.yf():c.lowValue;gvjs_TN(a.Lc,b,c.highThumbAtMaximum?a.Lc.xf():c.highValue-b);g.Ja(a.Lc,!0);f&&(e==gvjs_0?(a.Pv=gvjs_cO(),g.ib().appendChild(a.Pv)):(a.gw=gvjs_cO(),g.ib().appendChild(a.gw)),a.I1&&a.I1(d),a.U4());a.addEventListener(a.Lc,gvjs_Lt,a.jxa,!1,a)};function gvjs_eO(a,b){var c=b.ea("filterColumnIndex");if(null!=c)return b=parseInt(c,10),a.nd(b),b;if(b=gvjs_D(b,"filterColumnLabel")){a:{c=a.Z();for(var d=0;d<c;d++)if(a.Ca(d)==b)break a;throw Error("Invalid column label:"+b);}return d}throw Error("Either filterColumnIndex or filterColumnLabel must be specified.");};function gvjs_fO(a){gvjs_XN.call(this,a);this.De=-1}gvjs_r(gvjs_fO,gvjs_8N);gvjs_=gvjs_fO.prototype;gvjs_.zq=null;gvjs_.uc=null;gvjs_.Mf=function(){return{useFormattedValue:!1,values:null}};gvjs_.hm=function(a,b){a=gvjs_fO.o.hm.call(this,a,b);null==a.label&&(a.label=this.zq);a.values=this.uc;return a};
gvjs_.nr=function(a,b,c){this.clear();this.De=gvjs_eO(a,b);this.zq=a.Ca(this.De);var d=b.ea("values");if(Array.isArray(d)&&d.length)this.uc=d;else{b=gvjs_E(b,gvjs_tN);d=new gvjs_C;for(var e=[],f=0;f<a.ca();f++){var g=b?a.Ha(f,this.De):a.getValue(f,this.De);null==g||d.contains(g)||(d.add(g),e.push(g))}this.uc=e}this.WL(c)};
gvjs_.WL=function(a){var b=a.selectedValues;if(b){if(!Array.isArray(b))throw Error(gvjs_gN);var c=new gvjs_C;gvjs_s(this.uc,function(d){null!=d&&c.add(String(d))});a.selectedValues=gvjs_Fe(b,function(d){return c.contains(String(d))})}};
gvjs_.pG=function(a,b,c){var d=new gvjs_C;c=c.selectedValues;if(Array.isArray(c))for(var e=0;e<c.length;e++)null!=c[e]&&d.add(String(c[e]));if(0==d.tb())return new gvjs_L(a);c=gvjs_E(b,gvjs_tN);b=[];for(e=0;e<a.ca();e++){if(c)var f=a.Ha(e,this.De);else f=a.getValue(e,this.De),null!=f&&(f=String(f));d.contains(f)&&b.push(e)}a=new gvjs_L(a);a.Ap(b);return a};function gvjs_gO(a,b,c,d){gvjs_OB.call(this,d);this.Tb=a;this.hsa=b==gvjs_V;this.awa=c||""}gvjs_r(gvjs_gO,gvjs_OB);gvjs_=gvjs_gO.prototype;gvjs_.nba=null;gvjs_.fH=null;function gvjs_hO(a){if(!a.label)return null;var b=a.labelStacking==gvjs_V?gvjs_V:gvjs_0,c;a.labelSeparator&&(c=String(a.labelSeparator));return new gvjs_gO(String(a.label),b,c)}
gvjs_.K=function(){var a=this.G.K(gvjs_b);this.H=a;this.nba=gvjs_z("LABEL","google-visualization-controls-label",this.Tb+this.awa);a.appendChild(this.nba);this.fH=gvjs_z(gvjs_b);this.hsa||gvjs_XB(this.fH,gvjs_Y);a.appendChild(this.fH)};gvjs_.Rh=function(){return!1};gvjs_.ib=function(){return this.fH};gvjs_.addElement=function(a){this.fH.appendChild(a)};function gvjs_iO(a,b){this.ce=a;this.kca=b}gvjs_iO.prototype.Fd=function(){return this.kca.Fd(this)};gvjs_iO.prototype.getId=function(){return this.kca.getId(this)};gvjs_iO.prototype.get=function(){return this.ce};function gvjs_xia(a,b){return a.Fd().localeCompare(b.Fd())}function gvjs_jO(){}gvjs_jO.prototype.Fd=function(a){return String(a.get())};gvjs_jO.prototype.getId=function(a){return String(a.get())};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function gvjs_kO(a){gvjs_jm.call(this);this.Sc=null;this.H=a;a=gvjs_x||gvjs_Zg||gvjs_0g&&!gvjs_ah("531")&&a.tagName==gvjs_Yo;this.aa=new gvjs_Jq(this);this.aa.D(this.H,a?[gvjs_nv,"paste","cut","drop",gvjs_hv]:gvjs_hv,this)}gvjs_r(gvjs_kO,gvjs_jm);
gvjs_kO.prototype.handleEvent=function(a){if(a.type==gvjs_hv)gvjs_x&&gvjs_ah(10)&&0==a.keyCode&&0==a.charCode||(gvjs_lO(this),this.dispatchEvent(gvjs_mO(a)));else if(a.type!=gvjs_nv||gvjs_nia(a)){var b=a.type==gvjs_nv?this.H.value:null;gvjs_x&&229==a.keyCode&&(b=null);var c=gvjs_mO(a);gvjs_lO(this);this.Sc=gvjs_lm(function(){this.Sc=null;this.H.value!=b&&this.dispatchEvent(c)},0,this)}};function gvjs_lO(a){null!=a.Sc&&(gvjs_mm(a.Sc),a.Sc=null)}
function gvjs_mO(a){a=new gvjs__l(a.Bi);a.type=gvjs_hv;return a}gvjs_kO.prototype.O=function(){gvjs_kO.o.O.call(this);this.aa.ma();gvjs_lO(this);delete this.H};function gvjs_nO(a,b,c){gvjs_Vl.call(this,a,b);this.item=c}gvjs_r(gvjs_nO,gvjs_Vl);function gvjs_oO(a,b){gvjs_OB.call(this,b);this.Tb=a||""}var gvjs_pO;gvjs_r(gvjs_oO,gvjs_OB);gvjs_=gvjs_oO.prototype;gvjs_.yq=null;gvjs_.usa=10;function gvjs_qO(){null==gvjs_pO&&(gvjs_pO=gvjs_rN in gvjs_qh(gvjs_Qa));return gvjs_pO}gvjs_.WC=!1;gvjs_.K=function(){this.H=this.xa().K(gvjs_Qa,{type:gvjs_k})};
gvjs_.Jf=function(a){gvjs_oO.o.Jf.call(this,a);this.Tb||(this.Tb=a.getAttribute(gvjs_bd)||"");gvjs_Nx(gvjs_hh(a))==a&&(this.WC=!0,a=this.j(),gvjs_ZB(a,this.mJ));gvjs_qO()&&(this.j().placeholder=this.Tb);a=this.j();gvjs_Wq(a,gvjs_bd,this.Tb)};
gvjs_.Ob=function(){gvjs_oO.o.Ob.call(this);var a=new gvjs_Jq(this);a.D(this.j(),gvjs_Cu,this.L$);a.D(this.j(),gvjs_1o,this.rP);if(gvjs_qO())this.aa=a;else{gvjs__g&&a.D(this.j(),[gvjs_ad,gvjs_nv,gvjs_ov],this.Qpa);var b=gvjs_hh(this.j());a.D(gvjs_iq(b),"load",this.Wqa);this.aa=a;gvjs_rO(this)}this.Zp();this.j().tj=this};gvjs_.Te=function(){gvjs_oO.o.Te.call(this);this.aa&&(this.aa.ma(),this.aa=null);this.j().tj=null};
function gvjs_rO(a){!a.doa&&a.aa&&a.j().form&&(a.aa.D(a.j().form,"submit",a.Rpa),a.doa=!0)}gvjs_.O=function(){gvjs_oO.o.O.call(this);this.aa&&(this.aa.ma(),this.aa=null)};gvjs_.mJ="label-input-label";gvjs_.L$=function(){this.WC=!0;var a=this.j();gvjs_ZB(a,this.mJ);if(!gvjs_qO()&&!gvjs_sO(this)&&!this.xra){var b=this;a=function(){b.j()&&(b.j().value="")};gvjs_x?gvjs_lm(a,10):a()}};gvjs_.rP=function(){gvjs_qO()||(this.aa.Ab(this.j(),gvjs_1t,this.L$),this.yq=null);this.WC=!1;this.Zp()};
gvjs_.Qpa=function(a){27==a.keyCode&&(a.type==gvjs_nv?this.yq=this.j().value:a.type==gvjs_ad?this.j().value=this.yq:a.type==gvjs_ov&&(this.yq=null),a.preventDefault())};gvjs_.Rpa=function(){gvjs_sO(this)||(this.j().value="",gvjs_lm(this.bpa,10,this))};gvjs_.bpa=function(){gvjs_sO(this)||(this.j().value=this.Tb)};gvjs_.Wqa=function(){this.Zp()};gvjs_.hasFocus=function(){return this.WC};function gvjs_sO(a){return!!a.j()&&""!=a.j().value&&a.j().value!=a.Tb}
gvjs_.clear=function(){this.j().value="";null!=this.yq&&(this.yq="")};gvjs_.reset=function(){gvjs_sO(this)&&(this.clear(),this.Zp())};gvjs_.Wa=function(a){null!=this.yq&&(this.yq=a);this.j().value=a;this.Zp()};gvjs_.getValue=function(){return null!=this.yq?this.yq:gvjs_sO(this)?this.j().value:""};gvjs_.Wn=function(a){var b=this.j();gvjs_qO()?(b&&(b.placeholder=a),this.Tb=a):gvjs_sO(this)||(b&&(b.value=""),this.Tb=a,this.Bea());b&&gvjs_Wq(b,gvjs_bd,this.Tb)};gvjs_.Fd=function(){return this.Tb};
gvjs_.Zp=function(){var a=this.j();gvjs_qO()?this.j().placeholder!=this.Tb&&(this.j().placeholder=this.Tb):gvjs_rO(this);gvjs_Wq(a,gvjs_bd,this.Tb);gvjs_sO(this)?(a=this.j(),gvjs_ZB(a,this.mJ)):(this.xra||this.WC||(a=this.j(),gvjs_XB(a,this.mJ)),gvjs_qO()||gvjs_lm(this.Bea,this.usa,this))};gvjs_.Hb=function(a){this.j().disabled=!a;var b=this.j();gvjs_0B(b,this.mJ+gvjs_Vr,!a)};gvjs_.isEnabled=function(){return!this.j().disabled};
gvjs_.Bea=function(){!this.j()||gvjs_sO(this)||this.WC||(this.j().value=this.Tb)};function gvjs_tO(a,b,c){gvjs_OB.call(this,a);this.tj=c||new gvjs_oO;this.yg=!0;a=this.ka=b||new gvjs_mD(this.xa());a.setVisible(!1);a.kG=!1;a.f6=!0}gvjs_r(gvjs_tO,gvjs_OB);gvjs_=gvjs_tO.prototype;gvjs_.Ec=null;gvjs_.tD=null;gvjs_.tj=null;gvjs_.ka=null;gvjs_.jB=-1;gvjs_.Qf=null;gvjs_.$_=gvjs_Hf;gvjs_.NB=null;gvjs_.rX="";gvjs_.Tna="";gvjs_.oq=null;gvjs_.Vga=!1;
gvjs_.K=function(){this.Qf=this.xa().K(gvjs_Qa,{name:this.Tna,type:gvjs_k,autocomplete:"off"});this.NB=this.xa().K(gvjs_$a,"goog-combobox-button");this.H=this.xa().K(gvjs_$a,"goog-combobox",this.Qf,this.NB);this.Vga&&(gvjs_Gh(this.NB,"\u25bc"),gvjs_TA(this.NB,!0));this.Qf.setAttribute(gvjs_bd,this.rX);this.tj.cb(this.Qf);this.ka.xp(!1);this.ka.Bb||this.Ja(this.ka,!0)};
gvjs_.Hb=function(a){this.yg=a;this.tj.Hb(a);gvjs_0B(this.j(),"goog-combobox-disabled",!a)};gvjs_.isEnabled=function(){return this.yg};gvjs_.Ob=function(){gvjs_tO.o.Ob.call(this);var a=this.jc();a.D(this.j(),gvjs_kd,this.bua);a.D(this.xa().pc(),gvjs_kd,this.cua);a.D(this.Qf,gvjs_1o,this.jua);this.Tf=new gvjs_vC(this.Qf);a.D(this.Tf,gvjs_mv,this.oj);this.Ec=new gvjs_kO(this.Qf);a.D(this.Ec,gvjs_hv,this.kua);a.D(this.ka,gvjs_Xs,this.mua)};
gvjs_.Te=function(){this.Tf.ma();delete this.Tf;this.Ec.ma();this.Ec=null;gvjs_tO.o.Te.call(this)};gvjs_.Rh=function(){return!1};gvjs_.O=function(){gvjs_tO.o.O.call(this);this.pN();this.tj.ma();this.ka.ma();this.NB=this.Qf=this.ka=this.tj=null};gvjs_.gC=function(){this.pN();gvjs_uO(this);this.ka.fh(-1)};gvjs_.Oj=function(a){this.ka.Ja(a,!0);this.jB=-1};gvjs_.Fu=function(a,b){this.ka.yx(a,b,!0);this.jB=-1};gvjs_.removeItem=function(a){if(a=this.ka.removeChild(a,!0))a.ma(),this.jB=-1};gvjs_.ud=function(a){return this.ka.gf(a)};
gvjs_.sh=function(){return this.ka.Ee()};gvjs_.Vd=function(){return this.ka};gvjs_.Wa=function(a){this.tj.getValue()!=a&&(this.tj.Wa(a),this.sP())};gvjs_.getValue=function(){return this.tj.getValue()};function gvjs_vO(a,b){var c=a.ka.isVisible(),d;if(-1==a.jB){for(var e=d=0,f=a.ka.Ee();e<f;e++)a.ka.gf(e).isVisible()&&d++;a.jB=d}d=a.jB;c&&0==d?gvjs_uO(a):!c&&0<d&&(b&&(a.VK(""),a.eT(gvjs_Kf(a.tj.getValue().toLowerCase()))),gvjs_lm(a.pN,1,a),a.ka.setVisible(!0),gvjs_XB(a.j(),gvjs_jN));a.PR()}
gvjs_.PR=function(){this.ka&&this.ka.isVisible()&&(new gvjs_3C(this.j(),9,!0)).Yf(this.ka.j(),8)};function gvjs_uO(a){a.ka.setVisible(!1);gvjs_ZB(a.j(),gvjs_jN)}gvjs_.pN=function(){this.oq&&(gvjs_mm(this.oq),this.oq=null)};gvjs_.bua=function(a){this.yg&&(a.target==this.j()||a.target==this.Qf||gvjs_Eh(this.NB,a.target))&&(this.ka.isVisible()?this.gC():(gvjs_vO(this,!0),gvjs_Yg&&this.Qf.focus(),this.Qf.select(),this.ka.dr=!0,a.preventDefault()));a.stopPropagation()};
gvjs_.cua=function(a){gvjs_Eh(this.ka.j(),a.target)||this.gC()};gvjs_.mua=function(a){var b=a.target;this.dispatchEvent(new gvjs_nO(gvjs_Xs,this,b))&&(b=b.jj(),this.tj.getValue()!=b&&(this.tj.Wa(b),this.dispatchEvent(gvjs_Lt)),this.gC());a.stopPropagation()};gvjs_.jua=function(){this.pN();this.oq=gvjs_lm(this.gC,250,this)};
gvjs_.oj=function(a){var b=this.ka.isVisible();if(b&&this.ka.oj(a))return!0;var c=!1;switch(a.keyCode){case 27:b&&(this.gC(),c=!0);break;case 9:b&&(b=gvjs_cD(this.ka))&&(b.gi(a),c=!0);break;case 38:case 40:b||(gvjs_vO(this,!0),c=!0)}c&&a.preventDefault();return c};gvjs_.kua=function(){this.sP()};gvjs_.sP=function(){var a=gvjs_Kf(this.tj.getValue().toLowerCase());this.VK(a);gvjs_Nx(this.xa().pc())==this.Qf&&gvjs_vO(this,!1);var b=gvjs_cD(this.ka);""!=a&&b&&b.isVisible()||this.eT(a);this.tD=a;this.dispatchEvent(gvjs_Lt)};
gvjs_.VK=function(a){for(var b=!1,c=0,d=!this.$_(a,this.tD),e=0,f=this.ka.Ee();e<f;e++){var g=this.ka.gf(e);if(g instanceof gvjs_0C){if(!g.isVisible()&&!d)continue;var h=g.jj();h=typeof g.isa==gvjs_c&&g.iba||h&&this.$_(h.toLowerCase(),a);typeof g.bT==gvjs_c&&g.bT(a);g.setVisible(!!h);b=h||b}else b=g.isVisible()||b;g.isVisible()&&c++}this.jB=c};
gvjs_.eT=function(a){if(""!=a)for(var b=0,c=this.ka.Ee();b<c;b++){var d=this.ka.gf(b),e=d.jj();if(e&&this.$_(e.toLowerCase(),a)){this.ka.fh(b);d.bT&&d.bT(a);return}}this.ka.fh(-1)};function gvjs_wO(a,b,c,d){gvjs_0C.call(this,a,b,c,d)}gvjs_r(gvjs_wO,gvjs_0C);gvjs_JC("goog-combobox-item",function(){return new gvjs_wO(null)});gvjs_wO.prototype.iba=!1;gvjs_wO.prototype.isa=function(){return this.iba};
gvjs_wO.prototype.bT=function(a){if(this.isEnabled()){var b=this.jj(),c=b.toLowerCase().indexOf(a);if(0<=c){var d=this.xa();this.setContent([d.createTextNode(b.substr(0,c)),d.K("B",null,b.substr(c,a.length)),d.createTextNode(b.substr(c+a.length))])}}};function gvjs_xO(){}gvjs_r(gvjs_xO,gvjs_4C);gvjs_oe(gvjs_xO);gvjs_=gvjs_xO.prototype;gvjs_.K=function(a){var b=this.cm(a);b=a.xa().K(gvjs_b,gvjs_Ms+b.join(" "),a.getContent());this.zl(b,a.xn());return b};gvjs_.dl=function(){return gvjs_Ct};gvjs_.Rh=function(a){return a.tagName==gvjs_b};gvjs_.cb=function(a,b){gvjs_XB(b,gvjs_Y);return gvjs_xO.o.cb.call(this,a,b)};gvjs_.getValue=function(){return""};gvjs_.ra=function(){return gvjs_kN};gvjs_JC(gvjs_kN,function(){return new gvjs_6C(null,gvjs_xO.kc())});function gvjs_yO(){}gvjs_r(gvjs_yO,gvjs_xO);gvjs_oe(gvjs_yO);gvjs_yO.prototype.ra=function(){return gvjs_lN};gvjs_JC(gvjs_lN,function(){return new gvjs_6C(null,gvjs_yO.kc())});function gvjs_zO(a,b,c){gvjs_0C.call(this,a,b,c);this.Z2(!0)}gvjs_r(gvjs_zO,gvjs_0C);gvjs_zO.prototype.gi=function(){return this.dispatchEvent(gvjs_Xs)};gvjs_JC(gvjs_Rs,function(){return new gvjs_zO(null)});function gvjs_AO(a){gvjs_WN.call(this,a);this.uc=[];this.Hg=new gvjs_uq}gvjs_r(gvjs_AO,gvjs_WN);gvjs_AO.prototype.m=null;gvjs_AO.prototype.CH=null;var gvjs_BO={kza:gvjs_mN,pza:gvjs_tt,rza:"belowWrapping",qza:gvjs_nN};gvjs_AO.prototype.O=function(){gvjs_J(this.CH);gvjs_AO.o.O.call(this)};gvjs_AO.prototype.getState=function(){for(var a={selectedValues:[]},b=this.Hg.La(),c=0;c<b.length;c++)a.selectedValues.push(b[c].get());return a};
gvjs_AO.prototype.draw=function(a,b){b=gvjs_w(b||{});b.caption||(b.caption="Choose a value...");b.valuesMediator=b.valuesMediator||new gvjs_jO;b.cssClass=b.cssClass?String(b.cssClass):"google-visualization-controls-categoryfilter";"allowMultiple"in b||(b.allowMultiple=!0);"allowNone"in b||(b.allowNone=!0);"allowTyping"in b||(b.allowTyping=!0);"sortValues"in b||(b.sortValues=!0);var c=!1,d;for(d in gvjs_BO)if(b.selectedValuesLayout==gvjs_BO[d]){c=!0;break}c||(b.selectedValuesLayout=gvjs_mN);this.m=
b;gvjs_yia(this,a);(a=gvjs_hO(this.m))||(a=new gvjs_OB);a.V(this.getContainer());gvjs_XB(a.j(),this.m.cssClass);gvjs_J(this.CH);this.CH=this.m.allowTyping?this.m.allowMultiple?new gvjs_CO(this):new gvjs_DO(this):this.m.allowMultiple?new gvjs_EO(this):new gvjs_FO(this);this.CH.V(a);this.Hg.isEmpty()||this.CH.GE()};
function gvjs_yia(a,b){b=b||{};var c=a.m.valuesMediator,d=new gvjs_C;if(null!=b.selectedValues){if(!Array.isArray(b.selectedValues))throw Error(gvjs_gN);a.m.allowMultiple?gvjs_s(b.selectedValues,function(g){d.add((new gvjs_iO(g,c)).getId())}):b.selectedValues.length&&d.add((new gvjs_iO(b.selectedValues[0],c)).getId())}b=Array.isArray(a.m.values)?a.m.values:[];for(var e=0;e<b.length;e++){var f=new gvjs_iO(b[e],c);a.uc.push(f);d.contains(f.getId())&&a.Hg.set(f.getId(),f)}a.m.sortValues&&gvjs_Ve(a.uc,
gvjs_xia);!gvjs_GO(a)&&0<a.uc.length&&0==a.Hg.tb()&&a.Hg.set(a.uc[0].getId(),a.uc[0])}gvjs_AO.prototype.wu=function(){gvjs_N(this,gvjs_sN,null)};function gvjs_HO(a){return a.Hg.tb()==a.uc.length}function gvjs_GO(a){return!!a.m.allowNone}function gvjs_IO(a){gvjs_I.call(this);this.dc=a;this.Je=null}gvjs_r(gvjs_IO,gvjs_I);gvjs_=gvjs_IO.prototype;gvjs_.O=function(){gvjs_J(this.Je);gvjs_IO.o.O.call(this)};
gvjs_.V=function(a){gvjs_J(this.Je);this.Je=new gvjs_FD(this.dc.m.caption);this.UW();a.Ja(this.Je,!0);this.dc.addEventListener(this.Je,gvjs_Xs,this.Xo,!1,this);this.Je.Hb(0<this.dc.uc.length)};gvjs_.UW=function(){for(var a=this.dc.uc,b=0;b<a.length;b++)this.Je.Oj(new gvjs_zO(a[b].Fd(),a[b]))};gvjs_.GE=function(){};gvjs_.Xo=function(){this.dc.wu()};function gvjs_FO(a){gvjs_IO.call(this,a)}gvjs_r(gvjs_FO,gvjs_IO);
gvjs_FO.prototype.UW=function(){var a=this.dc;gvjs_GO(a)&&this.Je.Oj(new gvjs_zO(a.m.caption));gvjs_FO.o.UW.call(this)};gvjs_FO.prototype.GE=function(){for(var a=this.dc.Hg.La()[0],b=0,c=this.Je.sh();b<c;b++)if(this.Je.ud(b).fi==a){this.Je.Bk(b);break}};gvjs_FO.prototype.Xo=function(a){this.dc.Hg.clear();var b=this.Je.Ge().fi;b&&this.dc.Hg.set(b.getId(),b);gvjs_FO.o.Xo.call(this,a)};function gvjs_EO(a){gvjs_IO.call(this,a);this.Ak=null}gvjs_r(gvjs_EO,gvjs_IO);gvjs_=gvjs_EO.prototype;
gvjs_.O=function(){gvjs_J(this.Ak);gvjs_EO.o.O.call(this)};gvjs_.V=function(a){gvjs_EO.o.V.call(this,a);var b=this.dc.m.selectedValuesLayout;b==gvjs_mN&&this.Je.gs(gvjs_Y);gvjs_J(this.Ak);this.Ak=new gvjs_JO(b,gvjs_ey(this.Je.j()).width,gvjs_GO(this.dc)?0:1);a.Ja(this.Ak,!0);this.dc.addEventListener(this.Ak,gvjs_Xs,this.xI,!1,this)};
gvjs_.GE=function(){for(var a=this.dc.Hg,b=0,c=this.Je.sh();b<c;b++)a.Pe(this.Je.ud(b).fi.getId())&&this.Je.ud(b).setVisible(!1);gvjs_KO(this.Ak,a.La());this.Je.xl(null);this.Je.Hb(!gvjs_HO(this.dc))};gvjs_.Xo=function(a){var b=this.Je.Ge().fi;this.Je.Ge().setVisible(!1);this.Je.xl(null);this.dc.Hg.set(b.getId(),b);this.Je.Hb(!gvjs_HO(this.dc));gvjs_KO(this.Ak,this.dc.Hg.La());gvjs_EO.o.Xo.call(this,a)};
gvjs_.xI=function(a){(a=a.item)&&this.dc.Hg.remove(a.getId());this.Je.Hb(!0);for(var b=0,c=this.Je.sh();b<c;b++)if(this.Je.ud(b).fi==a){this.Je.ud(b).setVisible(!0);break}this.dc.wu()};function gvjs_LO(a){gvjs_I.call(this);this.dc=a;this.ee=null}gvjs_r(gvjs_LO,gvjs_I);gvjs_=gvjs_LO.prototype;gvjs_.O=function(){gvjs_J(this.ee);gvjs_LO.o.O.call(this)};
gvjs_.V=function(a){var b=this.dc.uc;gvjs_J(this.ee);this.ee=new gvjs_tO;this.ee.Vga=!0;var c=this.ee;c.rX=this.dc.m.caption;c.tj&&c.tj.Wn(c.rX);for(c=0;c<b.length;c++)this.ee.Oj(new gvjs_wO(b[c].Fd(),b[c]));a.Ja(this.ee,!0);this.ee.Hb(0<b.length);this.dc.addEventListener(this.ee,gvjs_Xs,this.Xo,!1,this);a=gvjs_Mh(gvjs_rl(),gvjs_hv,null,this.ee.j())[0];this.dc.addEventListener(a,gvjs_1o,this.jZ,!1,this)};gvjs_.GE=function(){};gvjs_.Xo=function(){this.dc.wu()};gvjs_.jZ=function(){};
function gvjs_DO(a){gvjs_LO.call(this,a)}gvjs_r(gvjs_DO,gvjs_LO);gvjs_DO.prototype.GE=function(){this.ee.Wa(this.dc.Hg.La()[0].Fd())};gvjs_DO.prototype.Xo=function(a){this.dc.Hg.clear();var b=a.item.getValue();b&&this.dc.Hg.set(b.getId(),b);gvjs_DO.o.Xo.call(this,a)};gvjs_DO.prototype.jZ=function(){var a=this.dc.Hg;if(!this.ee.getValue()&&gvjs_GO(this.dc)){var b=!a.isEmpty();a.clear();b&&this.dc.wu()}else a.isEmpty()?this.ee.Wa(""):this.ee.Wa(a.La()[0].Fd())};
function gvjs_CO(a){gvjs_LO.call(this,a);this.Ak=null}gvjs_r(gvjs_CO,gvjs_LO);gvjs_=gvjs_CO.prototype;gvjs_.O=function(){gvjs_J(this.Ak);gvjs_CO.o.O.call(this)};gvjs_.V=function(a){gvjs_CO.o.V.call(this,a);var b=this.dc.m.selectedValuesLayout;b==gvjs_mN&&gvjs_XB(this.ee.j(),gvjs_Y);gvjs_J(this.Ak);this.Ak=new gvjs_JO(b,gvjs_ey(this.ee.j()).width,gvjs_GO(this.dc)?0:1);a.Ja(this.Ak,!0);this.dc.addEventListener(this.Ak,gvjs_Xs,this.xI,!1,this)};
gvjs_.GE=function(){for(var a=this.dc.Hg,b=0,c=this.ee.sh();b<c;b++)a.Pe(this.ee.ud(b).fi.getId())&&this.ee.ud(b).Hb(!1);gvjs_KO(this.Ak,a.La());this.ee.Wa("");this.ee.Hb(!gvjs_HO(this.dc))};gvjs_.Xo=function(a){var b=a.item.getValue();a.item.Hb(!1);a.preventDefault();this.ee.gC();this.ee.Wa("");this.dc.Hg.set(b.getId(),b);this.ee.Hb(!gvjs_HO(this.dc));gvjs_KO(this.Ak,this.dc.Hg.La());gvjs_CO.o.Xo.call(this,a)};
gvjs_.xI=function(a){a=a.item;this.dc.Hg.remove(a.getId());this.ee.Hb(!0);for(var b=0,c=this.ee.sh();b<c;b++)if(this.ee.ud(b).fi==a){this.ee.ud(b).Hb(!0);break}this.dc.wu()};gvjs_.jZ=function(){this.ee.Wa("")};function gvjs_JO(a,b,c,d){gvjs_OB.call(this,d);this.KE=a;this.Yq=b;this.u0=c;this.Vz=0;this.LT=[]}gvjs_r(gvjs_JO,gvjs_OB);gvjs_JO.prototype.K=function(){var a=this.G.K("UL");this.H=a;this.Jf(a)};gvjs_JO.prototype.Rh=function(a){return"UL"==a.tagName};
gvjs_JO.prototype.Jf=function(a){gvjs_XB(a,"google-visualization-controls-categoryfilter-selected");this.KE==gvjs_mN?gvjs_XB(a,gvjs_Y):("belowWrapping"==this.KE||this.KE==gvjs_nN)&&gvjs_H(a,gvjs_Gv,this.Yq+gvjs_U)};
function gvjs_KO(a,b){a.Ac(!0);a.LT=[];a.Vz=b.length;for(var c=0;c<a.Vz;c++){var d=a,e=b[c];var f=new gvjs_$C(gvjs_0,new gvjs_MO(d.KE));f.xp(!1);var g=new gvjs_6C("\u00d7",new gvjs_yO);gvjs_K(g,gvjs_Xs,gvjs_ve(d.xI,e,f),!1,d);f.Ja(g,!0);g.j().setAttribute(gvjs_8w,0);g.Hb(d.Vz>d.u0);d=new gvjs_NC(e.Fd());d.gs(gvjs_Y);f.Ja(d,!0);a.LT.push(f);a.Ja(f,!0)}}
gvjs_JO.prototype.xI=function(a,b,c){this.Vz<=this.u0||(this.removeChild(c.target.getParent(),!0),gvjs_Ne(this.LT,b),this.Vz--,this.Vz<=this.u0&&0<this.Vz&&gvjs_s(this.LT,function(d){d.gf(0).Hb(!1)}),this.dispatchEvent(new gvjs_nO(gvjs_Xs,this,a)),c.stopPropagation())};function gvjs_MO(a){this.JM=void 0;this.KE=a}gvjs_r(gvjs_MO,gvjs_7C);gvjs_MO.prototype.K=function(a){var b=this.KE==gvjs_nN?"":gvjs_Y;return a.xa().K("LI",this.cm(a).join(" ")+" "+b)};gvjs_MO.prototype.Rh=function(a){return"LI"==a.tagName};function gvjs_NO(a){gvjs_fO.call(this,a)}gvjs_r(gvjs_NO,gvjs_fO);gvjs_NO.prototype.gt=function(){return"SelectorUi"};function gvjs_OO(a){gvjs_XN.call(this,a);this.De=null}gvjs_r(gvjs_OO,gvjs_8N);gvjs_OO.prototype.gt=function(){return"ChartRangeFilterUi"};gvjs_OO.prototype.nr=function(a,b,c){this.clear();this.De=gvjs_eO(a,b);b=a.Y(this.De);if(b==gvjs_j||b==gvjs_Db)throw Error("The filter cannot operate on a column of type "+b+". Column type must be one of: number, date, datetime or timeofday. Column role must be domain, and correlate to a continuous axis.");c.__data__=a};
gvjs_OO.prototype.pG=function(a,b,c){a=new gvjs_L(a);b=c.range;if(gvjs_pe(b)!=gvjs_vd)return a;c=b.start;b=b.end;if(null==c&&null==b)return a;a.Ap(a.it([{column:this.De,minValue:c,maxValue:b}]));return a};function gvjs_PO(a){gvjs_WN.call(this,a)}gvjs_r(gvjs_PO,gvjs_WN);gvjs_=gvjs_PO.prototype;gvjs_.sE=null;gvjs_.rK=null;gvjs_.Tv=null;gvjs_.O=function(){this.sE&&this.sE.Lb();gvjs_PO.o.O.call(this)};
gvjs_.getState=function(){function a(){return null===b.Tv?{}:{range:b.Tv.range}}var b=this;if(!this.sE)return a();var c=this.sE.bP();return null==c.start||null==c.end?a():{range:c}};gvjs_.draw=function(a,b){this.Tv=a;this.rK||(this.rK=new gvjs_Q({chartType:"RangeSelector",dataTable:a.__data__,options:b,state:a,view:b.chartView}),gvjs_Ym(this.rK,gvjs_g,gvjs_q(this.pua,this)));this.rK.draw(this.getContainer())};gvjs_.pua=function(){this.sE=this.rK.vf();gvjs_Ym(this.sE,gvjs_tw,gvjs_q(this.oua,this))};
gvjs_.oua=function(a){gvjs_N(this,gvjs_sN,{startChanged:a.startChanged,endChanged:a.endChanged,inProgress:a.inProgress})};function gvjs_QO(a){gvjs_6N.call(this,a);this.Xp=-1;this.GW=null}gvjs_r(gvjs_QO,gvjs_6N);gvjs_=gvjs_QO.prototype;gvjs_.mW=null;gvjs_.pf=null;gvjs_.Mf=function(){return{columns:null}};gvjs_.hm=function(a,b){a=gvjs_QO.o.hm.call(this,a,b);a.values=this.pf;b=a.label;null==b&&(b=this.VO(),1<=b.length&&(b=b[0].Xa(),null!=this.Xp&&(b=b.Ca(this.Xp),a.label=b)));return a};
gvjs_.nr=function(a,b,c){this.clear();this.Xp=b.Da("chartColumnIndex");this.mW=b.mb("chartColumnId");if(null==this.Xp){if(null==this.mW)throw Error("Either chartColumnIndex or chartColumnId must be specified.");for(var d=a.Z(),e=0;e<d;e++)a.nd(e)===this.mW&&(this.Xp=e);if(null==this.Xp||0>this.Xp)throw Error("Invalid column id");}if(null==this.Xp||0>this.Xp)throw Error("Invalid column index");d=b.ea("columns");if(Array.isArray(d)&&d.length)this.pf=d;else{d={string:{string:!0},discrete:{string:!0},
number:{number:!0},dateortime:{date:!0,datetime:!0,timeofday:!0},continuous:{number:!0,date:!0,datetime:!0,timeofday:!0}};b=(b=gvjs_D(b,"columnType"))&&d[b];this.GW={};d=[];e=a.Z();for(var f=0;f<e;f++){var g=a.Ca(f),h=a.nd(f),k=a.Y(f);if(!b||b[k])this.GW[g]={index:f,id:h,label:g},d.push(g)}this.pf=d}this.oT=[{input:"dataColumnIndex",mg:"view.columns."+this.Xp}];this.WL(c)};
gvjs_.WL=function(a){a=a.selectedValues;if(null!=a&&(!Array.isArray(a)||1<a.length))throw Error("Invalid selectedValues: should be an array of length zero or one.");};gvjs_.vV=function(a,b,c){var d=c.selectedValues;return Array.isArray(d)&&1===d.length?(c.dataColumnIndex=this.GW[d[0]].index,gvjs_QO.o.vV.call(this,a,b,c)):a};function gvjs_RO(a){gvjs_QO.call(this,a)}gvjs_r(gvjs_RO,gvjs_QO);gvjs_RO.prototype.gt=function(){return"SelectorUi"};var gvjs_zia={day:864E5,hour:36E5,minute:6E4,second:1E3,millisecond:1};function gvjs_SO(a){var b=gvjs_TO(a);var c=a.split(" ");if(2===c.length){if(c=Number(c[0]),typeof c!==gvjs_f||isNaN(c))throw Error('Invalid number for increment: "'+a+'".');}else c=1;b=gvjs_zia[b];if(!b)throw Error('Invalid number for increment "'+a+'".');return c*b}function gvjs_TO(a){var b=a.length-1;a="s"===a.charAt(b)?a.substring(0,b):a;a=a.split(" ");return 2===a.length?a[1]:a[0]}
function gvjs_UO(a,b,c){a=Number(a);b=(a-c)%gvjs_SO(b);return a=new Date(a-b)}function gvjs_VO(a,b,c){a=Number(a);c=a-c;b=gvjs_SO(b);c%=b;return a=0===c?new Date(a):new Date(a+b-c)};function gvjs_WO(a){gvjs_bO.call(this,a);this.Dj=this.bd=null}gvjs_r(gvjs_WO,gvjs_bO);gvjs_=gvjs_WO.prototype;gvjs_.U4=function(){var a=this.Lc.getValue()+this.Tp,b=a+this.Lc.em();this.gw&&gvjs_Gh(this.gw,this.bd.$b(new Date(a)));this.Pv&&gvjs_Gh(this.Pv,this.bd.$b(new Date(b)))};gvjs_.I1=function(a){var b=a.ob(gvjs_Ku);(a=String(a.ea("step")))&&!b.pattern&&(b.pattern=gvjs_Aia[gvjs_TO(a)]);this.bd=new gvjs_Oi(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs_ji([b,gvjs_XO]);(b=gvjs_hO(b))||(b=new gvjs_OB);b.V(this.getContainer());var d=gvjs_D(c,"cssClass");d&&gvjs_XB(b.j(),d);gvjs_dO(this,b,a,c,gvjs_XO)};gvjs_.rfa=function(a){this.Dj=String(a.ea("step",gvjs_XO.step));var b=gvjs_SO(this.Dj);this.Lc.mT(b);b=gvjs_SO(String(a.ea("unitIncrement",gvjs_XO.unitIncrement)));this.Lc.aB=b;a=gvjs_SO(String(a.ea(gvjs_oN,gvjs_XO.blockIncrement)));this.Lc.Sm=a};gvjs_.SY=function(a,b){return a.Da(b)};
gvjs_.Qda=function(a,b,c){var d=String(this.Dj);a=new Date(a);var e=gvjs_TO(d);a=gvjs_UO(a,e,Number(new Date(1970,0,1))).valueOf();b=gvjs_VO(new Date(b),d,a).valueOf();c.lowValue=gvjs_UO(new Date(c.lowValue),d,a).valueOf();c.highValue=gvjs_VO(new Date(c.highValue),d,a).valueOf();return{minValue:a,maxValue:b,state:c}};gvjs_.getState=function(){var a=gvjs_WO.o.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};
var gvjs_Aia={year:"yyyy",month:"yyyy-MM",day:"yyyy-MM-dd",hour:gvjs_uN,minute:gvjs_uN,second:"yy/MM/dd hh:mm:ssa",millisecond:"yy/MM/dd hh:mm:ss:SSSSa"},gvjs_XO={showRangeValues:!0,minValue:null,maxValue:null,cssClass:gvjs_pN,step:"day",unitIncrement:"day",blockIncrement:"day",orientation:gvjs_0};function gvjs_YO(a){gvjs_9N.call(this,a)}gvjs_r(gvjs_YO,gvjs_9N);gvjs_=gvjs_YO.prototype;gvjs_.gt=function(){return"DateRangeFilterUi"};gvjs_.hm=function(a,b){a=gvjs_YO.o.hm.call(this,a,b);a.minValue=this.Ya;a.maxValue=this.Cb;null==a.label&&(a.label=this.zq);return a};gvjs_.SZ=function(a,b){this.hT(gvjs_F(b,gvjs_id,gvjs_ZO(this,a,gvjs_Nv)));this.gT(gvjs_F(b,gvjs_gd,gvjs_ZO(this,a,gvjs_Fv)))};
gvjs_.nr=function(a,b,c){this.clear();this.De=gvjs_eO(a,b);this.zq=a.Ca(this.De);var d=a.Y(this.De);if(d!=gvjs_Pb&&d!=gvjs_Qb)throw Error(gvjs_za+this.De+" is not a date");this.SZ(a,b);gvjs_$N(this,c)};function gvjs_ZO(a,b,c){a=b.ck(a.De)[c];return Number(a)}gvjs_.d5=function(a){return Number(a)};gvjs_.getState=function(){var a=gvjs_YO.o.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};
gvjs_.MY=function(a,b,c){(a=gvjs_Gy(a,"ui",{}).step)||(a="day");return function(d){d=Number(d);return b<=d&&c>=d}};function gvjs__O(a){gvjs_WN.call(this,a);this.J={}}gvjs_r(gvjs__O,gvjs_WN);gvjs__O.prototype.draw=function(a){this.J=a};gvjs__O.prototype.getState=function(){return this.J};function gvjs_0O(a){gvjs_9N.call(this,a)}gvjs_r(gvjs_0O,gvjs_9N);gvjs_=gvjs_0O.prototype;gvjs_.gt=function(){return"NumberRangeUi"};gvjs_.hm=function(a,b){a=gvjs_0O.o.hm.call(this,a,b);a.minValue=this.Ya;a.maxValue=this.Cb;null==a.label&&(a.label=this.zq);return a};gvjs_.SZ=function(a,b){this.hT(gvjs_F(b,gvjs_id,a.ck(this.De).min));this.gT(gvjs_F(b,gvjs_gd,a.ck(this.De).max))};
gvjs_.nr=function(a,b,c){this.clear();this.De=gvjs_eO(a,b);this.zq=a.Ca(this.De);if(a.Y(this.De)!==gvjs_f)throw Error(gvjs_za+this.De+" is not numeric");this.SZ(a,b);gvjs_$N(this,c)};gvjs_.d5=function(a){return gvjs_Lg(String(a))};gvjs_.MY=function(a,b,c){(a=gvjs_Gy(a,"ui",{}).step)||(a=1);return function(d){return b<=d&&c>=d}};function gvjs_1O(a){gvjs_bO.call(this,a);this.Dj=this.bd=null;this.Nn=0}gvjs_r(gvjs_1O,gvjs_bO);gvjs_=gvjs_1O.prototype;gvjs_.U4=function(){var a=this.Lc.getValue()+this.Tp,b=a+this.Lc.em();a/=this.Nn;b/=this.Nn;this.gw&&gvjs_Gh(this.gw,this.bd.$b(a));this.Pv&&gvjs_Gh(this.Pv,this.bd.$b(b))};gvjs_.I1=function(a){var b=a.ob(gvjs_Ku);(a=Number(a.Da("step")))&&null==b.fractionDigits&&(b.fractionDigits=a);this.bd=new gvjs_bj(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs_ji([b,gvjs_2O]);(b=gvjs_hO(b))||(b=new gvjs_OB);b.V(this.getContainer());var d=gvjs_D(c,"cssClass");d&&gvjs_XB(b.j(),d);gvjs_dO(this,b,a,c,gvjs_2O)};
gvjs_.rfa=function(a){var b=gvjs_2O.step,c=a.Da(gvjs_dx);null!=c&&(c=Math.max(2,c),b=(this.Lc.xf()-this.Lc.yf())/c);b=Number(gvjs_F(a,"step",b));c=gvjs_F(a,"unitIncrement",gvjs_2O.unitIncrement);a=gvjs_F(a,gvjs_oN,gvjs_2O.blockIncrement);this.Nn=Math.pow(10,gvjs__z(b));b=Math.round(b*this.Nn);c=Math.round(c*this.Nn);a=Math.round(a*this.Nn);this.Lc.mT(b);this.Lc.aB=c;this.Lc.Sm=a;this.Dj=b};gvjs_.SY=function(a,b){return a.Da(b)};
gvjs_.Qda=function(a,b,c){var d=this.Dj;a=Math.floor(a*this.Nn);a-=(a-0)%d;b=gvjs_3O(Math.ceil(b*this.Nn),d,a);var e=c.lowValue*this.Nn;c.lowValue=e-(e-a)%d;c.highValue=gvjs_3O(c.highValue*this.Nn,d,a);return{minValue:a,maxValue:b,state:c}};
gvjs_.getState=function(){var a=this.Lc;if(!a)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var b=a.getValue(),c=a.em();return{lowValue:(b+this.Tp)/this.Nn,highValue:(b+c+this.Tp)/this.Nn,lowThumbAtMinimum:b===a.yf(),highThumbAtMaximum:b+c===a.xf()}};function gvjs_3O(a,b,c){c=(a-c)%b;return 0===c?a:a+b-c}var gvjs_2O={showRangeValues:!0,minValue:null,maxValue:null,ticks:null,cssClass:gvjs_pN,format:{},step:1,unitIncrement:1,blockIncrement:10,orientation:gvjs_0};function gvjs_4O(a){gvjs_6N.call(this,a)}gvjs_r(gvjs_4O,gvjs_7N);gvjs_4O.prototype.gt=function(){return"NumberRangeUi"};function gvjs_5O(a){gvjs_XN.call(this,a);this.De=-1}gvjs_r(gvjs_5O,gvjs_8N);gvjs_=gvjs_5O.prototype;gvjs_.zq=null;gvjs_.Mf=function(){return{matchType:gvjs_Ad,caseSensitive:!1,useFormattedValue:!1}};gvjs_.hm=function(a,b){a=gvjs_5O.o.hm.call(this,a,b);null==a.label&&(a.label=this.zq);return a};gvjs_.nr=function(a,b){this.clear();this.De=gvjs_eO(a,b);this.zq=a.Ca(this.De)};
gvjs_.pG=function(a,b,c){var d=gvjs_E(b,"caseSensitive"),e=gvjs_D(b,"matchType");gvjs_E(b,"prefixMatch");var f=gvjs_E(b,gvjs_tN),g=this.De;b=[];c=c.value.toString();if(!c)return new gvjs_L(a);d||(c=c.toLowerCase());for(var h=0;h<a.ca();h++){var k=f?a.Ha(h,g):""+a.getValue(h,g);d||(k=k.toLowerCase());switch(e){case "exact":k==c&&b.push(h);break;case "any":-1!=k.indexOf(c)&&b.push(h);break;default:0==k.indexOf(c)&&b.push(h)}}a=new gvjs_L(a);a.Ap(b);return a};
function gvjs_6O(a){gvjs_5O.call(this,a)}gvjs_r(gvjs_6O,gvjs_5O);gvjs_6O.prototype.gt=function(){return"StringFilterUi"};function gvjs_7O(a){gvjs_WN.call(this,a);this.Jm=0}gvjs_r(gvjs_7O,gvjs_WN);gvjs_=gvjs_7O.prototype;gvjs_.Qf=null;gvjs_.getState=function(){return{value:this.Qf?this.Qf.value:null}};
gvjs_.draw=function(a,b){b=b||{};var c=gvjs_hO(b);c||(c=new gvjs_OB);c.V(this.getContainer());var d=b.cssClass?String(b.cssClass):"google-visualization-controls-stringfilter";gvjs_XB(c.j(),d);this.Qf=this.PW(a,b);c.ib().appendChild(this.Qf)};
gvjs_.PW=function(a,b){var c=gvjs_z(gvjs_Qa);c.setAttribute(gvjs_9c,gvjs_te(this.getContainer())+"-input");gvjs_Xd in a&&a.value&&(c.value=String(a.value));gvjs_rN in b&&c.setAttribute(gvjs_rN,b.placeholder);"realtimeTrigger"in b&&!b.realtimeTrigger?(this.addEventListener(c,gvjs_nv,this.Maa,!1,this),this.addEventListener(c,gvjs_Lt,this.wu,!1,this)):this.addEventListener(c,gvjs_ov,this.Maa);return c};
gvjs_.Maa=function(a){this.Jm&&gvjs_mm(this.Jm);13==a.keyCode?(this.wu(),a.preventDefault()):this.Jm=gvjs_lm(function(){this.Jm=0;this.wu()},200,this)};gvjs_.wu=function(){gvjs_N(this,gvjs_sN,null)};gvjs_o("google.visualization.Choreographer",gvjs_ao,void 0);gvjs_ao.prototype.bind=gvjs_ao.prototype.bind;gvjs_ao.prototype.clear=gvjs_ao.prototype.clear;gvjs_ao.prototype.dispose=gvjs_ao.prototype.ma;gvjs_ao.prototype.isDisposed=gvjs_ao.prototype.Bg;gvjs_ao.prototype.draw=gvjs_ao.prototype.draw;gvjs_o(gvjs_kc,gvjs_lo,void 0);gvjs_lo.prototype.bind=gvjs_lo.prototype.bind;gvjs_lo.prototype.getSelection=gvjs_lo.prototype.getSelection;gvjs_lo.prototype.clear=gvjs_lo.prototype.clear;
gvjs_lo.prototype.dispose=gvjs_lo.prototype.ma;gvjs_lo.prototype.isDisposed=gvjs_lo.prototype.Bg;gvjs_lo.prototype.draw=gvjs_lo.prototype.draw;gvjs_o("google.visualization.Control",gvjs_XN,void 0);gvjs_XN.prototype.draw=gvjs_XN.prototype.draw;gvjs_XN.prototype.getState=gvjs_XN.prototype.getState;gvjs_XN.prototype.resetControl=gvjs_XN.prototype.Yt;gvjs_XN.prototype.clear=gvjs_XN.prototype.clear;gvjs_XN.prototype.dispose=gvjs_XN.prototype.ma;gvjs_XN.prototype.isDisposed=gvjs_XN.prototype.Bg;
gvjs_o(gvjs_pc,gvjs_8N,void 0);gvjs_8N.prototype.applyFilter=gvjs_8N.prototype.yB;gvjs_o(gvjs_Mc,gvjs_3N,void 0);gvjs_3N.prototype.applyOperator=gvjs_3N.prototype.qG;gvjs_o("google.visualization.ControlUi",gvjs_WN,void 0);gvjs_WN.prototype.draw=gvjs_WN.prototype.draw;gvjs_WN.prototype.getState=gvjs_WN.prototype.getState;gvjs_WN.prototype.clear=gvjs_WN.prototype.clear;gvjs_WN.prototype.dispose=gvjs_WN.prototype.ma;gvjs_WN.prototype.isDisposed=gvjs_WN.prototype.Bg;gvjs_o(gvjs_Xc,gvjs_6O,void 0);
gvjs_6O.prototype.draw=gvjs_6O.prototype.draw;gvjs_6O.prototype.applyFilter=gvjs_6O.prototype.yB;gvjs_6O.prototype.getState=gvjs_6O.prototype.getState;gvjs_6O.prototype.resetControl=gvjs_6O.prototype.Yt;gvjs_6O.prototype.clear=gvjs_6O.prototype.clear;gvjs_6O.prototype.dispose=gvjs_6O.prototype.ma;gvjs_6O.prototype.isDisposed=gvjs_6O.prototype.Bg;gvjs_o(gvjs_Yc,gvjs_7O,void 0);gvjs_7O.prototype.draw=gvjs_7O.prototype.draw;gvjs_7O.prototype.getState=gvjs_7O.prototype.getState;
gvjs_7O.prototype.clear=gvjs_7O.prototype.clear;gvjs_7O.prototype.isDisposed=gvjs_7O.prototype.Bg;gvjs_o(gvjs_Jc,gvjs_0O,void 0);gvjs_0O.prototype.draw=gvjs_0O.prototype.draw;gvjs_0O.prototype.applyFilter=gvjs_0O.prototype.yB;gvjs_0O.prototype.getState=gvjs_0O.prototype.getState;gvjs_0O.prototype.resetControl=gvjs_0O.prototype.Yt;gvjs_0O.prototype.clear=gvjs_0O.prototype.clear;gvjs_0O.prototype.dispose=gvjs_0O.prototype.ma;gvjs_0O.prototype.isDisposed=gvjs_0O.prototype.Bg;gvjs_o(gvjs_lc,gvjs_YO,void 0);
gvjs_YO.prototype.draw=gvjs_YO.prototype.draw;gvjs_YO.prototype.applyFilter=gvjs_YO.prototype.yB;gvjs_YO.prototype.getState=gvjs_YO.prototype.getState;gvjs_YO.prototype.resetControl=gvjs_YO.prototype.Yt;gvjs_YO.prototype.clear=gvjs_YO.prototype.clear;gvjs_YO.prototype.dispose=gvjs_YO.prototype.ma;gvjs_YO.prototype.isDisposed=gvjs_YO.prototype.Bg;gvjs_o(gvjs_Lc,gvjs_1O,void 0);gvjs_1O.prototype.draw=gvjs_1O.prototype.draw;gvjs_1O.prototype.getState=gvjs_1O.prototype.getState;
gvjs_1O.prototype.clear=gvjs_1O.prototype.clear;gvjs_1O.prototype.dispose=gvjs_1O.prototype.ma;gvjs_1O.prototype.isDisposed=gvjs_1O.prototype.Bg;gvjs_o(gvjs_mc,gvjs_WO,void 0);gvjs_WO.prototype.draw=gvjs_WO.prototype.draw;gvjs_WO.prototype.getState=gvjs_WO.prototype.getState;gvjs_WO.prototype.clear=gvjs_WO.prototype.clear;gvjs_WO.prototype.dispose=gvjs_WO.prototype.ma;gvjs_WO.prototype.isDisposed=gvjs_WO.prototype.Bg;gvjs_o(gvjs_Kc,gvjs_4O,void 0);gvjs_4O.prototype.draw=gvjs_4O.prototype.draw;
gvjs_4O.prototype.apply=gvjs_4O.prototype.apply;gvjs_4O.prototype.getState=gvjs_4O.prototype.getState;gvjs_4O.prototype.resetControl=gvjs_4O.prototype.Yt;gvjs_4O.prototype.clear=gvjs_4O.prototype.clear;gvjs_4O.prototype.dispose=gvjs_4O.prototype.ma;gvjs_4O.prototype.isDisposed=gvjs_4O.prototype.Bg;gvjs_o(gvjs_hc,gvjs_RO,void 0);gvjs_RO.prototype.draw=gvjs_RO.prototype.draw;gvjs_RO.prototype.apply=gvjs_RO.prototype.apply;gvjs_RO.prototype.getState=gvjs_RO.prototype.getState;
gvjs_RO.prototype.resetControl=gvjs_RO.prototype.Yt;gvjs_RO.prototype.clear=gvjs_RO.prototype.clear;gvjs_RO.prototype.dispose=gvjs_RO.prototype.ma;gvjs_RO.prototype.isDisposed=gvjs_RO.prototype.Bg;gvjs_o(gvjs_cc,gvjs_NO,void 0);gvjs_NO.prototype.draw=gvjs_NO.prototype.draw;gvjs_NO.prototype.applyFilter=gvjs_NO.prototype.yB;gvjs_NO.prototype.getState=gvjs_NO.prototype.getState;gvjs_NO.prototype.resetControl=gvjs_NO.prototype.Yt;gvjs_NO.prototype.clear=gvjs_NO.prototype.clear;
gvjs_NO.prototype.dispose=gvjs_NO.prototype.ma;gvjs_NO.prototype.isDisposed=gvjs_NO.prototype.Bg;gvjs_o(gvjs_Tc,gvjs_AO,void 0);gvjs_AO.prototype.draw=gvjs_AO.prototype.draw;gvjs_AO.prototype.getState=gvjs_AO.prototype.getState;gvjs_AO.prototype.clear=gvjs_AO.prototype.clear;gvjs_AO.prototype.dispose=gvjs_AO.prototype.ma;gvjs_AO.prototype.isDisposed=gvjs_AO.prototype.Bg;gvjs_o(gvjs_dc,gvjs_OO,void 0);gvjs_OO.prototype.draw=gvjs_OO.prototype.draw;gvjs_OO.prototype.applyFilter=gvjs_OO.prototype.yB;
gvjs_OO.prototype.getState=gvjs_OO.prototype.getState;gvjs_OO.prototype.resetControl=gvjs_OO.prototype.Yt;gvjs_OO.prototype.clear=gvjs_OO.prototype.clear;gvjs_OO.prototype.dispose=gvjs_OO.prototype.ma;gvjs_OO.prototype.isDisposed=gvjs_OO.prototype.Bg;gvjs_o(gvjs_ec,gvjs_PO,void 0);gvjs_PO.prototype.draw=gvjs_PO.prototype.draw;gvjs_PO.prototype.getState=gvjs_PO.prototype.getState;gvjs_PO.prototype.clear=gvjs_PO.prototype.clear;gvjs_PO.prototype.dispose=gvjs_PO.prototype.ma;
gvjs_PO.prototype.isDisposed=gvjs_PO.prototype.Bg;gvjs_o(gvjs_uc,gvjs__O,void 0);gvjs__O.prototype.draw=gvjs__O.prototype.draw;gvjs__O.prototype.getState=gvjs__O.prototype.getState;gvjs__O.prototype.clear=gvjs__O.prototype.clear;gvjs__O.prototype.dispose=gvjs__O.prototype.ma;gvjs__O.prototype.isDisposed=gvjs__O.prototype.Bg;gvjs_o(gvjs_nc,gvjs_4N,void 0);gvjs_4N.prototype.draw=gvjs_4N.prototype.draw;gvjs_4N.prototype.applyOperator=gvjs_4N.prototype.qG;gvjs_4N.prototype.getState=gvjs_4N.prototype.getState;
gvjs_4N.prototype.resetControl=gvjs_4N.prototype.Yt;gvjs_4N.prototype.clear=gvjs_4N.prototype.clear;gvjs_4N.prototype.dispose=gvjs_4N.prototype.ma;gvjs_4N.prototype.isDisposed=gvjs_4N.prototype.Bg;gvjs_o(gvjs_oc,gvjs_5N,void 0);gvjs_5N.prototype.draw=gvjs_5N.prototype.draw;gvjs_5N.prototype.getState=gvjs_5N.prototype.getState;gvjs_5N.prototype.clear=gvjs_5N.prototype.clear;gvjs_5N.prototype.dispose=gvjs_5N.prototype.ma;gvjs_5N.prototype.isDisposed=gvjs_5N.prototype.Bg;
gvjs_o("google.visualization.drawDrilldown",function(a,b,c){var d=new gvjs_2N(a);gvjs_K(c,gvjs_1t,function(){d.rollup()});d.draw(b)},void 0);gvjs_o("google.visualization.RemoteDataSource",gvjs_YN,void 0);gvjs_YN.prototype.getUrl=gvjs_YN.prototype.getUrl;gvjs_YN.prototype.getColumnId=gvjs_YN.prototype.nd;gvjs_YN.prototype.getColumnType=gvjs_YN.prototype.Y;gvjs_YN.prototype.getNumberOfColumns=gvjs_YN.prototype.Z;
