var gvjs_zX='Failed geocoding "',gvjs_AX="Requested map does not exist.",gvjs_BX="The visualization is not ready yet.",gvjs_CX="bottom_left",gvjs_DX="feature",gvjs_EX="featureClick",gvjs_FX="featureHover",gvjs_GX="featureMove",gvjs_HX="google.visualization.GeoChart.mapExists",gvjs_IX="google.visualization.GeoChart.setMapsSource",gvjs_JX="kavrayskiy-vii",gvjs_KX="magnifyingGlassBorder",gvjs_LX="magnifyingGlassTriangle",gvjs_MX="marker",gvjs_NX="markerClick",gvjs_OX="markerHover",gvjs_PX="mercator",
gvjs_QX="natural",gvjs_RX="top_left";gvjs_aG.prototype.ZV=gvjs_W(133,function(){var a=this,b=gvjs_t(this.lines,function(c){var d=a.anchor?a.anchor:{x:0,y:0},e=gvjs_iy(c.x+d.x,c.length,a.rd);c=gvjs_iy(c.y+d.y,a.oa.fontSize,a.Rc);return e.start==e.end||c.start==c.end?null:new gvjs_A(c.start,e.end,c.end,e.start)});b=gvjs_Fe(b,function(c){return null!=c});return gvjs_FA(b)});gvjs_Gq.prototype.bw=gvjs_W(69,function(){return!1});gvjs_Uq.prototype.bw=gvjs_W(68,function(){return!0});
function gvjs_SX(a){return Math.min(a.width,a.height)}
var gvjs_2ka={$Aa:gvjs_Cd,yAa:gvjs_fd,TEXT:gvjs_k,$F:gvjs_yb},gvjs_3ka={nM:gvjs_0,rM:gvjs_V},gvjs_4ka=["AD","AE","AF","AG","AL","AM","AO","AR","AT","AU","AZ","BA","BB","BD","BE","BF","BG","BH","BI","BJ","BN","BO","BR","BS","BT","BW","BY","BZ","CA","CD","CF","CG","CH","CI","CL","CM","CN","CO","CR","CS","CU","CV","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE","EG","ER","ES","ET","FI","FJ","FM","FR","GA","GB","GD","GE","GH","GM","GN","GQ","GR","GT","GW","GY","HN","HR","HT","HU","ID","IE","IL","IN",
"IQ","IR","IS","IT","JM","JO","JP","KE","KG","KH","KI","KM","KN","KP","KR","KW","KZ","LA","LB","LI","LK","LR","LS","LT","LU","LV","LY","MA","MD","ME","MG","MH","MK","ML","MM","MN","MR","MT","MU","MV","MW","MX","MY","MZ","NA","NE","NG","NI","NL","NO","NP","NR","NZ","OM","PA","PE","PG","PH","PK","PL","PT","PW","PY","QA","RO","RS","RU","RW","SA","SB","SC","SD","SE","SG","SH","SI","SK","SL","SM","SN","SO","SR","ST","SV","SY","SZ",gvjs_As,"TG","TH","TJ","TL","TM","TN","TO",gvjs_Bs,"TT","TV","TW","TZ",
"UA","UG","UM","US","UY","UZ","VC","VE","VN","VU","WS","YE","YU","ZA","ZM","ZW"],gvjs_5ka=["ad","ae","af","ag","al","am","ao","ar","as","at","au","ax","az","ba","bb","bd","be","bf","bg","bh","bi","bj","bm","bn","bo","bq","br","bs","bt","bw","by","bz","ca","cd","cf","cg","ch","ci","cl","cm","co","cr","cu","cv","cw","cy","cz","de","dj","dk","dm","do","dz","ec","ee","eg","eh","er","es","et","fi","fj","fm","fo","fr","ga","gb","gd","ge","gf","gg","gh","gl","gm","gn","gp","gq","gr","gt","gw","gy","hk",
"hn","hr","ht","hu",gvjs_9c,"ie","il",gvjs_Fp,"iq","ir","is","it","je","jm","jo","jp","ke","kg","kh","ki","km","kn","kp","kw","ky","kz","la","lb","lc","li","lk","lr","ls","lt","lu","lv","ly","ma","md","me","mf","mg","mh","mk","ml","mm","mn","mp","mq","mr","ms","mu","mv","mw","mx","my","mz","na","nc","ne","ng","ni","nl","no","np","nr","nu","nz","om","pa","pe","pf","pg","ph","pk","pl","pm","pr","ps","pt","pw","py","qa","re","ro","rs","ru","rw","sa","sb","sc","sd","se","sh","si","sj","sk","sl","sm",
"sn","so","sr","ss","st","sv","sx","sy","sz","tc","td","tg","th","tj","tk","tl","tm","tn","to","tr","tt","tv","tw","tz","ua","ug","us","uy","uz","vc","ve","vg","vi","vn","vu","wf","ws","xk","ye","yt","za","zm","zw"];function gvjs_6ka(a){var b=gvjs_4ka;"1"===gvjs_US&&(b=gvjs_5ka,a=a.toLowerCase());return 0<=gvjs_Bz(b,a)};function gvjs_TX(a){this.selection=new gvjs_In;this.hw=this.$j=this.aI=this.sf=null;if(null!=a){this.selection.setSelection(a.selection);var b=new gvjs_ji([a]);this.sf=b.mb("focusedFeature");this.aI=b.mb("focusedMarker");if(null!=b.ob("elaborated")){a=b.Da("elaborated.rowId");var c=b.Mq("elaborated.isDisputed"),d=b.Da("elaborated.origin.x");b=b.Da("elaborated.origin.y");null!=a&&null!=d&&null!=b&&null!=c&&(this.$j={yj:a,ZI:c,origin:{x:d,y:b}})}}}
gvjs_TX.prototype.clone=function(){var a=new gvjs_TX;a.selection=this.selection.clone();a.sf=gvjs_cf(this.sf);a.$j=gvjs_cf(this.$j);a.hw=gvjs_cf(this.hw);return a};gvjs_TX.prototype.equals=function(a){return gvjs_jf(this)==gvjs_jf(a)};var gvjs_UX={Lza:"continents",xBa:"subcontinents",Mza:gvjs_yS,YAa:gvjs_FS,EAa:"metros"};function gvjs_VX(a){this.m=a||{}}gvjs_VX.prototype.jA=function(){return[]};gvjs_VX.prototype.yY=function(){return 1.618};gvjs_VX.prototype.set=function(a,b){this.m[a]=b};gvjs_VX.prototype.cd=function(){return gvjs_cf(this.m)};function gvjs_WX(a){var b=0,c=0;if(a.boundingBox){var d=a.boundingBox.lo;c=a.boundingBox.hi;b=(c[0]-d[0])/2+d[0];c=(c[1]-d[1])/2+d[1]}d=[29.5,45.5];b={parallels:d,origin:{lat:b,lng:c}};c=b.origin;a.origin&&Object.assign(c,a.origin);Object.assign(b,a);b.origin=c;b.parallels&&0!==b.parallels.length?2>b.parallels.length&&(b.parallels[1]=Math.abs(b.parallels[0]-d[0])>Math.abs(b.parallels[0]-d[1])?d[0]:d[1]):b.parallels=d;this.m=a||{};this.g1=b.origin.lat/(180/Math.PI);this.AR=b.origin.lng/(180/Math.PI);
this.np=gvjs_t(b.parallels,function(e){return e/(180/Math.PI)})}gvjs_m(gvjs_WX,gvjs_VX);gvjs_WX.prototype.jA=function(a){var b=this;return gvjs_t(arguments,function(c){var d=c[0]/(180/Math.PI),e=.5*(Math.sin(b.np[0])+Math.sin(b.np[1]));c=e*(c[1]/(180/Math.PI)-b.AR);var f=Math.cos(b.np[0]);f=f*f+2*e*Math.sin(b.np[0]);d=Math.sqrt(f-2*e*Math.sin(d))/e;return{x:180/Math.PI*Math.sin(c)*d,y:180/Math.PI*(Math.sqrt(f-2*e*Math.sin(b.g1))/e-d*Math.cos(c))}})};function gvjs_XX(a){this.m=a||{}}gvjs_m(gvjs_XX,gvjs_VX);gvjs_XX.prototype.yY=function(){return 2.2};gvjs_XX.prototype.jA=function(a){return gvjs_t(arguments,function(b){var c=b[0]/(180/Math.PI);return{x:b[1]/(180/Math.PI)*3/(2*Math.PI)*Math.sqrt(Math.PI*Math.PI/3-c*c)*(180/Math.PI),y:c}})};function gvjs_YX(a){var b=0,c=0;if(a.boundingBox){var d=a.boundingBox.lo;c=a.boundingBox.hi;b=(c[0]-d[0])/2+d[0];c=(c[1]-d[1])/2+d[1]}d=[20,50];b={parallels:d,origin:{lat:b,lng:c}};c=b.origin;a.origin&&Object.assign(c,a.origin);Object.assign(b,a);b.origin=c;b.parallels&&0!==b.parallels.length?2>b.parallels.length&&(b.parallels[1]=Math.abs(b.parallels[0]-d[0])>Math.abs(b.parallels[0]-d[1])?d[0]:d[1]):b.parallels=d;this.m=a||{};this.g1=b.origin.lat/(180/Math.PI);this.AR=b.origin.lng/(180/Math.PI);this.np=
gvjs_t(b.parallels,function(e){return e/(180/Math.PI)})}gvjs_m(gvjs_YX,gvjs_VX);
gvjs_YX.prototype.jA=function(a){var b=this;return gvjs_t(arguments,function(c){var d=c[1]/(180/Math.PI),e=Math.log(1/Math.cos(b.np[1])*Math.cos(b.np[0]))/Math.log(1/Math.tan(.25*Math.PI+.5*b.np[0])*Math.tan(.25*Math.PI+.5*b.np[1])),f=Math.cos(b.np[0])*Math.pow(Math.tan(.25*Math.PI+.5*b.np[0]),e)/e;c=f*Math.pow(1/Math.tan(.25*Math.PI+c[0]/(180/Math.PI)*.5),e);return{x:180/Math.PI*Math.sin(e*(d-b.AR))*c,y:f*Math.pow(1/Math.tan(.25*Math.PI+.5*b.g1),e)-180/Math.PI*Math.cos(e*(d-b.AR))*c}})};function gvjs_ZX(a){return 180/Math.PI*(Math.atan(Math.exp(a/(180/Math.PI)))-Math.PI/4)*2}function gvjs__X(){this.Tr={}}gvjs__X.prototype.track=function(a){var b=this;gvjs_s(arguments,function(c){for(var d in c)if(c.hasOwnProperty(d)){d in b.Tr||(b.Tr[d]={min:Infinity,max:-Infinity});if(!b.Tr[d].min||c[d]<b.Tr[d].min)b.Tr[d].min=c[d];if(!b.Tr[d].max||c[d]>b.Tr[d].max)b.Tr[d].max=c[d]}})};gvjs__X.prototype.getBounds=function(a){return{min:this.Tr[a].min,max:this.Tr[a].max}};function gvjs_0X(a){this.m=a||{}}gvjs_m(gvjs_0X,gvjs_VX);gvjs_0X.prototype.jA=function(a){return gvjs_t(arguments,function(b){return{x:b[1],y:180/Math.PI*Math.log(Math.tan(b[0]/180*.5*Math.PI+Math.PI/4))}})};var gvjs_7ka={hza:"albers",oAa:gvjs_JX,rAa:"lambert",DAa:gvjs_PX},gvjs_1X={};gvjs_1X.mercator=gvjs_0X;gvjs_1X[gvjs_JX]=gvjs_XX;gvjs_1X.albers=gvjs_WX;gvjs_1X.lambert=gvjs_YX;var gvjs_8ka={NONE:gvjs_e,TOP_LEFT:gvjs_RX,TOP_RIGHT:"top_right",BOTTOM_LEFT:gvjs_CX,BOTTOM_RIGHT:"bottom_right"},gvjs_9ka={NONE:gvjs_e,ZAa:gvjs_GS,vza:"bounds",mM:gvjs_vt};function gvjs_$ka(a){return gvjs_Gy(a,"projection",{name:gvjs_PX},function(b){b=typeof b===gvjs_j?b:(gvjs_ai(b)||{}).name;b=gvjs_qi(b,gvjs_7ka);if(!b)throw Error('The projection you specified, "'+b+'", is not valid.');return{name:b}})}
var gvjs_2X={region:gvjs_LS,resolution:gvjs_yS,domain:"COM",displayMode:gvjs_yb,showGeocodeWarnings:!1,backgroundColor:{fill:gvjs_Ix,stroke:"#666",strokeWidth:0},datalessRegionColor:"F5F5F5",defaultColor:"267114",markerOpacity:1,selectionMode:gvjs_Zp,fontName:gvjs_Uo,geocodingContext:gvjs_GS,tooltip:{isHtml:!1,textStyle:{fontName:gvjs_Uo,fontSize:13,color:gvjs_0o},trigger:gvjs_Cu,showDisputedText:!1,showTitle:!0},colorAxis:{minValue:null,maxValue:null,values:null},sizeAxis:{minValue:null,maxValue:null,
minSize:3,maxSize:12},legend:{position:gvjs_CX,orientation:gvjs_0,textStyle:{color:gvjs_0o,auraColor:gvjs_Ix}},marker:{style:{stroke:{color:gvjs_Nr,width:1}}},projection:gvjs_PX,keepAspectRatio:!0,magnifyingGlass:{enable:!0,zoomFactor:5}};function gvjs_3X(a){gvjs_I.call(this);this.qe=a;this.gF=null;this.Efa=!0;this.fI=null;this.rr=new gvjs_SS;this.asa=/^([a-zA-Z][a-zA-Z]|[a-zA-Z][a-zA-Z]\-[a-zA-Z0-9](|[a-zA-Z0-9](|[a-zA-Z0-9]))|\d\d\d)$/;this.gsa=/^\d\d\d$/}gvjs_m(gvjs_3X,gvjs_I);gvjs_=gvjs_3X.prototype;gvjs_.b3=function(a){this.gF=a;null!=this.Psa&&this.Psa(a)};
function gvjs_ala(a,b,c,d,e,f){a.Efa=e;if(0===b.ca())gvjs_lm(function(){f([],[],!0)});else switch(c.iV){case gvjs_cd:a.SW(b,c,f);break;case gvjs_Bd:gvjs_bla(a,b,c,d,f);break;case "address":a.RW(b,c,d,f)}}gvjs_.SW=function(a,b,c){for(var d=[],e=0;e<a.ca();e++){var f=a.getValue(e,b.uD),g=a.getValue(e,b.BD);d[e]=null==f||null==g?null:{lat:gvjs_Ig(f),lng:gvjs_Ig(g)}}gvjs_lm(function(){c([],d,!0)})};
function gvjs_bla(a,b,c,d,e){for(var f=[],g=0;g<b.ca();g++)f.push(b.getValue(g,c.tK));"metros"==d.resolution||"continents"==d.resolution||"subcontinents"==d.resolution?a.QW(d,f,e):a.TW(d,f,e)}gvjs_.QW=function(a,b,c){a=gvjs_Hf(a.region,"US")&&"metros"==a.resolution;for(var d=[],e=0;e<b.length;e++){var f=gvjs_Ig(b[e]);a&&this.gsa.test(f)&&(f="US-"+f);d.push(f.toUpperCase())}gvjs_lm(function(){c(d,[],!0)})};
gvjs_.TW=function(a,b,c){var d=this,e=a.region;var f=a.resolution==gvjs_FS&&gvjs_6ka(e)?e:"countries_en";if(a.resolution==gvjs_FS&&"US"==e)for(a=0;a<b.length;++a){var g=b[a];2==g.length&&(b[a]="US-"+g)}gvjs_XS(f,function(h){h=d.xW(b,h);for(var k=[],l=0;l<b.length;l++)if(null==h[l]){var m=b[l];k.push({address:m,mea:l,Wba:null});h[l]=m}gvjs_Me(k)?c(h,[],!0):(c(h,[],!1),gvjs_4X(d,k,e,c,h))})};
gvjs_.xW=function(a,b){for(var c=[],d=0;d<a.length;++d){var e=gvjs_Kf(gvjs_Ig(a[d])).toLowerCase(),f=b&&gvjs_ZS(b,e);e=f?f:this.asa.test(e)?e.toUpperCase():null;c.push(e)}return c};function gvjs_5X(a,b){a.Efa&&a.qe&&gvjs_Py(a.qe,b)}
gvjs_.RW=function(a,b,c,d){var e=[];c=c.region;2==c.length&&(c=c.toUpperCase(),c=c.replace(/GB/,"UK"),c=c.replace(/RU/,"SU"),c=c.replace(/TP/,"TL"));for(var f=0;f<a.ca();f++){var g=gvjs_Ig(a.getValue(f,b.fG));gvjs_6X(this,c)&&(g+=" "+c);e.push({address:g,Wba:f,mea:null})}gvjs_4X(this,e,c,d,[])};function gvjs_6X(a,b){return b==gvjs_LS||gvjs_jA(b)?!1:a.fI===gvjs_GS||a.fI===gvjs_vt}
function gvjs_cla(a){var b=Infinity,c=Infinity,d=-Infinity,e=-Infinity;if(null!=a.gF&&0!==a.gF.views.length)return gvjs_s(a.gF.views,function(f){f=f.Mu;b=Math.min(b,f.zh[0]);c=Math.min(b,f.zh[1]);d=Math.max(d,f.Gi[0]);e=Math.max(d,f.Gi[1])}),{lo:{lat:b,lng:c},hi:{lat:d,lng:e}}}
function gvjs_4X(a,b,c,d,e){for(var f=[],g=[],h=0;h<b.length;h++){var k={address:b[h].address};gvjs_6X(a,c)&&(k.region=c);"bounds"!==a.fI&&a.fI!==gvjs_vt||(k.bounds=gvjs_cla(a));g.push(k)}var l=gvjs_Qe(b);a.rr.create(g,function(m){return a.qZ(l,d,e,f,m)},1)}
gvjs_.qZ=function(a,b,c,d,e){for(var f=e.length,g=0;g<f;g++){var h=a[g],k=h.address,l=h.mea;h=h.Wba;if(e[g]&&e[g][0]){var m=e[g][0];null!=l&&(c[l]=gvjs_dla(m),c[l]||(gvjs_5X(this,gvjs_zX+k+'"'),c[l]=k));null!=h&&(d[h]={lat:m.geometry.location.lat(),lng:m.geometry.location.lng()})}else null!=l&&(c[l]=null),null!=h&&(d[h]=null),gvjs_5X(this,gvjs_zX+k+'"')}gvjs_Se(a,0,f);(a=gvjs_Me(a))&&gvjs_Ie(c,function(n){return null===n})&&gvjs_Ie(d,function(n){return null===n})&&gvjs_5X(this,gvjs_wS);b(c,d,a)};
function gvjs_dla(a){var b=gvjs_Je(a.address_components,function(c){return 0<=gvjs_De(c.types,"country")});if(!b)return null;b=b.short_name;"US"==b&&(a=gvjs_Je(a.address_components,function(c){return 0<=gvjs_De(c.types,"administrative_area_level_1")}))&&(b="US-"+a.short_name);return b}gvjs_.O=function(){this.rr.cancel();gvjs_I.prototype.O.call(this)};function gvjs_7X(a,b,c){gvjs_I.call(this);var d=this;this.C=b;this.hf=function(e,f){return d.C.hf(e,f)};this.Ti=a;this.XA=[];this.fb=c;this.Jd={};this.vc=new gvjs_jm;this.Q_=this.iw=this.mh=this.Xv=this.bt=this.lw=this.rD=null}gvjs_m(gvjs_7X,gvjs_I);gvjs_7X.prototype.D=function(a,b){gvjs_K(this.vc,a,b)};
function gvjs_8X(a,b){var c=a.C;c.clear();var d=c.Ql(b.width,b.height);a.Jd={};var e=c.Sa();gvjs_9X(a,e,b,new gvjs_3(0,0,b.width,b.height),!1);var f=c.Sa(),g=a.C,h=g.Sa();a.bt=g.Sa();for(var k=0;k<b.views.length;++k)gvjs_$X(a,h,b,b.views[k],!1),gvjs_aY(a,b,b.views[k]);a.lw=g.Sa();gvjs_bY(a,a.lw,b.ID,!1,b.Tk);g.appendChild(f,h);a.bt&&g.appendChild(f,a.bt);g.appendChild(f,a.lw);g=b.Qsa;f=c.Tx(f,a.bw()?new gvjs_3(g.left,g.top,g.width-1,g.height-1):g);a.mh=c.Sa();gvjs_cY(a,b);a.iw=c.Sa();gvjs_dY(a,b);
a.Xv=c.Sa();gvjs_eY(a,b);c.appendChild(d,e);c.appendChild(e,f);c.appendChild(e,a.mh);c.appendChild(e,a.iw);c.appendChild(e,a.Xv);a.rD=b;gvjs_ela(a,d)}function gvjs_fY(a,b,c){c=void 0===c?!1:c;a.Xv&&a.C.Ac(a.Xv);gvjs_eY(a,b);if(c||!gvjs_NA(a.rD.NC,b.NC))for(a.bt&&a.C.Ac(a.bt),c=0;c<b.views.length;++c)gvjs_aY(a,b,b.views[c]);gvjs_fla(a,b);a.mh&&a.C.Ac(a.mh);gvjs_cY(a,b);a.Q_!=(b.yJ?b.yJ.hp:null)&&a.iw&&(a.C.Ac(a.iw),gvjs_dY(a,b));a.rD=b}
function gvjs_aY(a,b,c){var d=a.C.Sa();c=gvjs_Fe(c.features,function(f){return gvjs_Le(b.NC,f.id)});for(var e=0;e<c.length;++e)gvjs_gla(a,d,b,c[e]);a.C.appendChild(a.bt,d)}function gvjs_gY(a,b){var c=a.C;gvjs_s(gvjs_yh(a.lw.j()),function(d){gvjs_s(gvjs_yh(d),function(e){c.Ie(e)},this)},a);gvjs_bY(a,a.lw,b.ID,!1,b.Tk)}function gvjs_gla(a,b,c,d){a.bw()||(c=c.qC[d.id].Vb,gvjs_hY(a,b,d,!1,!1,[gvjs_iY,gvjs_hla,c.fill]),gvjs_Me(d.gn)||(gvjs_hY(a,b,d,!0,!1,[c.gn]),gvjs_hY(a,b,d,!1,!1,[c.border])))}
function gvjs_dY(a,b){var c=b.yJ;if(c){var d=a.iw,e=a.C,f=c.view.$D,g=f.left+f.width/2,h=f.top+f.height/2,k=f.width/2,l=f.height/2,m=c.Xba.x,n=c.Xba.y,p=new gvjs_2({fill:"808080",fillOpacity:.25}),q=new gvjs_hy;q.move(m,n);q.va(m,n+(h>n?l:-l));q.va(m+(g>m?k:-k),n);q.close();m=e.Ga(q,p,d);gvjs_jY(a,m,gvjs_LX,!0);m=new gvjs_2({fill:gvjs_Ix});m=e.Yk(g,h,k,l,m,d);gvjs_jY(a,m,gvjs_KX,!0);m=new gvjs_2({stroke:"bfbfbf",strokeWidth:1.5});m=e.Yk(g,h,k,l,m,d);gvjs_jY(a,m,gvjs_KX,!0);m=e.Sa();f=e.Tx(m,new gvjs_3(f.left+
3.5,f.top+3.5,f.width-7,f.height-7),!0);e.appendChild(d,f);f=new gvjs_2({stroke:"cccccc",strokeWidth:1.5});d=e.Yk(g,h,k-3.5,l-3.5,f,d);gvjs_jY(a,d,gvjs_KX,!0);d=c.view;gvjs_9X(a,m,b,d.$D,!0);gvjs_$X(a,m,b,d,!0);gvjs_bY(a,m,c.ID,!0,b.Tk);a.Q_=c.hp}else a.Q_=null}function gvjs_eY(a,b){0<a.XA.length&&(gvjs_s(a.XA,function(c){this.C.Ie(c)},a),a.XA=[]);a.XA=0<b.vu.length?gvjs_t(b.vu,function(c){return c.html?gvjs_uI(c,this.Ti.getContainer()):gvjs_vI(c,this.C,this.Xv).j()},a):[]}
function gvjs_kY(a,b){gvjs_v(b.qC,function(c,d){c=c.Vb;gvjs_lY(this,d,gvjs_DX,c.fill);gvjs_lY(this,d,"disputed",c.gn);gvjs_lY(this,d,"border",c.border)},a)}function gvjs_lY(a,b,c,d){b=[c,b].join(".");b=a.Jd[b];if(null!=b)for(c=0;c<b.length;++c)a.C.ji(b[c],d)}
function gvjs_ela(a,b){function c(e){var f=gvjs_ila(a,e.target);if(f&&f.xO){var g=gvjs_jla(e.type,f.type),h=f.elementType;f=gvjs_w(f.data);e.type==gvjs_od?f.ap=!1:e.type==gvjs_pd&&(f.ap=!0);f.yb=gvjs_rz(e);a.vc.dispatchEvent({type:g,elementType:h,data:f})}}var d=a.C;d.ec(b,gvjs_nd,c);d.ec(b,gvjs_od,c);d.ec(b,gvjs_pd,c);d.ec(b,gvjs_1t,c)}
function gvjs_jla(a,b){switch(b){case gvjs_DX:switch(a){case gvjs_1t:return gvjs_EX;case gvjs_nd:return gvjs_GX;case gvjs_od:case gvjs_pd:return gvjs_FX}case gvjs_MX:switch(a){case gvjs_1t:return gvjs_NX;case gvjs_nd:return"markerMove";case gvjs_od:case gvjs_pd:return gvjs_OX}}return null}function gvjs_jY(a,b,c,d){gvjs_mY(a,b,["F",c,"1",d?"1":"0","","0"])}function gvjs_mY(a,b,c){c=c.join("#");a.C.Cm(b,c)}
function gvjs_ila(a,b){a=a.C.Fq(b);if(!a||a==gvjs_Fs)return null;a=a.split("#");b=a[1];var c="1"==a[2]?!0:!1,d="1"==a[3]?!0:!1;switch(a[0]){case "F":return{type:gvjs_DX,elementType:b,xO:c,data:{bJ:d,featureId:a[4]?a[4]:null,ZI:"1"==a[5]?!0:!1}};case "M":return{type:gvjs_MX,elementType:b,xO:c,data:{bJ:d,hp:a[4],yj:gvjs_Lg(a[5]),jD:"1"==a[6]?!0:!1}};default:return null}}function gvjs_9X(a,b,c,d,e){b=a.C.rb(d.left,d.top,d.width,d.height,c.xG,b);gvjs_jY(a,b,"ocean",e)}
function gvjs_$X(a,b,c,d,e){for(var f=a.C.Sa(),g=0;g<d.features.length;++g){var h=a,k=d.features[g],l=e,m=c.qC[k.id].Vb;gvjs_hY(h,f,k,!1,l,[m.fill],gvjs_DX);gvjs_Me(k.gn)||(gvjs_hY(h,f,k,!0,l,[m.gn],"disputed"),gvjs_hY(h,f,k,!1,l,[m.border],"border"))}a.C.appendChild(b,f)}
function gvjs_hY(a,b,c,d,e,f,g){var h=d?c.gn:c.polygons,k=c.id;(g=null!=g?[g,k].join("."):null)&&(a.Jd[g]=a.Jd[g]||[]);for(k=0;k<h.length;++k){var l=h[k],m=new gvjs_hy;gvjs_nY(m,l.ZK,gvjs_QX);for(var n=0;n<l.GI.length;n++)gvjs_nY(m,l.GI[n],"reverse");l=m;if(0<l.Fc.length)for(m=0;m<f.length;++m)if(n=a.C.Ga(l,f[m],b))gvjs_mY(a,n,["F",gvjs_DX,c.xO?"1":"0",e?"1":"0",c.id,d?"1":"0"]),g&&a.Jd[g].push(n)}}
function gvjs_nY(a,b,c){b=b.points;var d=b.length;if(!(1>=d)){var e=c==gvjs_QX?0:d-1;d=c==gvjs_QX?d:-1;c=c==gvjs_QX?1:-1;for(var f=e;f!=d;f+=c){var g=b[f][0],h=b[f][1];f==e?a.move(g,h):a.va(g,h)}a.close()}}
function gvjs_bY(a,b,c,d,e){var f=a.C;c=gvjs_Qe(c);gvjs_Ve(c,function(m,n){return n.size-m.size});for(var g=0;g<c.length;++g){var h=c[g],k=f.Sa();gvjs_mY(a,k,["M",gvjs_MX,"1",d?"1":"0",h.hp,h.yj,h.jD?"1":"0"]);f.appendChild(b,k);if(a.fb.zX===gvjs_k){var l=new gvjs_Ay({hb:e,fontSize:h.size,color:h.brush.nb(),opacity:h.brush.ff,Pb:"",bold:!1,lf:!1,ed:!1});f.Ud(h.label,h.x,h.y,20,gvjs__,gvjs__,l,k)}else f.ze(h.x,h.y,h.size,h.brush,k);h=[gvjs_MX,h.hp].join(".");a.Jd[h]=k.j()}}
function gvjs_fla(a,b){var c=a.C,d=a.rD.OC;gvjs_s(d,function(e){if(!gvjs_Le(b.OC,e)){e=[gvjs_MX,e].join(".");e=gvjs_yh(this.Jd[e]);for(var f=1;f<e.length;++f)c.Ie(e[f])}},a);gvjs_s(b.OC,function(e){if(!gvjs_Le(d,e)){e=[gvjs_MX,e].join(".");e=this.Jd[e];var f=gvjs_zh(e).cloneNode(!0);c.ji(f,gvjs_iY);e.appendChild(f)}},a)}function gvjs_cY(a,b){if(b.ej){b=b.ej;var c=a.C;a=a.mh;gvjs_nI(b.yW,c,a);gvjs_oI(b.Y_,c,a);gvjs_pI(b.h4,c,a)}}
gvjs_7X.prototype.O=function(){gvjs_fm(this.vc);0<this.XA.length&&(gvjs_s(this.XA,function(a){this.C.Ie(a)},this),this.XA=[]);this.C.clear();gvjs_J(this.rD);this.rD=null;this.lw&&this.C.Ie(this.lw.j());this.lw=null;this.bt&&this.C.Ie(this.bt.j());this.bt=null;this.Xv&&this.C.Ie(this.Xv.j());this.Xv=null;this.mh&&this.C.Ie(this.mh.j());this.mh=null;this.iw&&this.C.Ie(this.iw.j());this.iw=null;gvjs_I.prototype.O.call(this)};gvjs_7X.prototype.bw=function(){return this.C.bw()};
var gvjs_iY=new gvjs_2({strokeWidth:"3",stroke:gvjs_0o,strokeOpacity:"0.2"}),gvjs_hla=new gvjs_2({strokeWidth:"1",stroke:gvjs_0o,strokeOpacity:"0.1"});function gvjs_oY(a,b){var c=new gvjs_A(-5,-5,-5,-5);this.mf=b.clone().expand(c);a=2*gvjs_SX(a)/5;this.q$=new gvjs_y(a,a)}function gvjs_kla(a,b){var c=a.mf;a=a.q$;var d=b.x;d+a.width>c.right&&(d=b.x-a.width);var e=b.y-a.height;e<c.top&&(e=b.y);return new gvjs_3(d,e,a.width,a.height)}
gvjs_oY.prototype.ZV=function(a,b,c){var d=b.V_,e=b.$D.Xb();b=parseFloat(a.lat);a=parseFloat(a.lng);a<d.zh[1]?a+=360:a>d.Gi[1]&&(a-=360);c=gvjs_SX(this.q$)/2/c/(e.height/(d.Gi[0]-d.zh[0]));return{Gi:[b+c,a+c],zh:[b-c,a-c]}};function gvjs_lla(a,b){var c=gvjs_Je(a.ID,function(d){return d.yj==b});if(!c)return!1;a=a.view.$D;c=gvjs_Gz(new gvjs_u(c.x,c.y),new gvjs_u(a.left+a.width/2,a.top+a.height/2));a=gvjs_SX(a.Xb())/2;return c<.9*a};function gvjs_pY(a,b,c,d){this.yg=!a.bw()&&gvjs_E(b,"magnifyingGlass.enable");this.J=c;this.Db=d;this.TB=this.$J=null}gvjs_pY.prototype.handleEvent=function(a,b){if(!this.yg)return!1;if(gvjs_mla(this,a)||this.rZ(a,b))return!0;b=a.elementType==gvjs_DX;return a.data.bJ&&b?!0:!1};
gvjs_pY.prototype.rZ=function(a,b){var c=this;if(a.type!=gvjs_OX)return!1;if(a.data.ap){if(!a.data.jD)return!1;if(b&&gvjs_lla(b,a.data.yj))return!0;gvjs_qY(this);this.$J=setTimeout(function(){c.$J=null;c.J.hw={hp:a.data.hp,yj:a.data.yj};gvjs_WJ(c.Db,0)},300);return!0}gvjs_qY(this);return!1};
function gvjs_mla(a,b){if(!a.J.hw)return!1;switch(b.type){case gvjs_NX:case gvjs_EX:return b.data.bJ?a=!1:(gvjs_rY(a),a=!0),a;case gvjs_OX:case gvjs_FX:if(b.data.ap){var c=b.elementType==gvjs_MX,d=b.elementType==gvjs_LX;b.data.bJ&&!d?gvjs_sY(a):c&&(b.data.jD?gvjs_sY(a):gvjs_rY(a))}else null===a.TB&&(c=b.elementType==gvjs_MX,(b.data.bJ||c)&&gvjs_tY(a));return!1;case gvjs_GX:return b.elementType==gvjs_LX?(gvjs_tY(a),a=!0):a=!1,a;default:return!1}}
function gvjs_tY(a){gvjs_sY(a);a.TB=setTimeout(function(){a.TB=null;gvjs_rY(a)},500)}function gvjs_rY(a){a.J.hw=null;gvjs_WJ(a.Db,0)}function gvjs_qY(a){var b=gvjs_rl().ek();null!==a.$J&&(b.clearTimeout(a.$J),a.$J=null)}function gvjs_sY(a){var b=gvjs_rl().ek();null!==a.TB&&(b.clearTimeout(a.TB),a.TB=null)};function gvjs_uY(a){this.m=a||{}}gvjs_m(gvjs_uY,gvjs_VX);gvjs_uY.prototype.yY=function(){return 1};gvjs_uY.prototype.jA=function(a){return gvjs_t(arguments,function(b){return{x:b[1],y:b[0]}})};function gvjs_nla(a,b,c,d,e,f){this.m=a;var g=gvjs_$ka(a);this.P1=new gvjs_1X[g.name](g);this.da=b;this.Pa=c;var h=gvjs_xy(gvjs_Ly(a,gvjs_kt));g=b-h;h=c-h;this.us=new gvjs_3(Math.round((b-g)/2),Math.round((c-h)/2),g,h);g=this.us;if(a.Mq("keepAspectRatio")){h=g.width;var k=g.height,l=this.P1.yY(),m=Math.min(h,Math.round(k*l));l=Math.min(k,Math.round(h/l));g=new gvjs_3(Math.round((h-m)/2)+g.left,Math.round((k-l)/2)+g.top,m,l)}else g=g.clone();this.kw=g;this.be=d;this.W=e;this.fb=f;this.C8=gvjs_xi(a,
gvjs_xp,Math.round(Math.pow(2*(this.us.width+this.us.height),1/3)));this.Ssa=gvjs_Jy(a,["marker.style.stroke.color","marker.style.stroke"],gvjs_Nr);this.Tsa=gvjs_xi(a,"marker.style.stroke.width",1);this.oX=gvjs_D(a,gvjs_wp);this.zs=gvjs_vY(this);this.bL=gvjs_wY(this);d=a.ea(gvjs_tv);this.ara=gvjs_pe(d)==gvjs_vd;this.CQ=gvjs_D(a,gvjs_wv,gvjs_CX,gvjs_8ka);this.Bba=gvjs_Iy(a,"legend.bar.length",1/3);this.AQ=gvjs_D(a,"legend.orientation",gvjs_0,gvjs_3ka);this.Eba=gvjs_My(a,gvjs_xv,{hb:this.oX,fontSize:this.C8});
this.T0=a.mb("legend.numberFormat");this.pma=gvjs_Jy(a,gvjs_zS,"");this.YN=gvjs_Jy(a,gvjs_AS,"");this.M7=gvjs_ola(this);this.fxa=gvjs_pla(this);d=gvjs_My(a,gvjs_mx);e=gvjs_My(a,gvjs_mx,{bold:!0});this.zF=gvjs_D(a,gvjs_nx,gvjs_Cu,gvjs_AF);this.yz=this.zF!=gvjs_e;this.uu={Kd:d,bold:e};d=gvjs_E(a,"tooltip.showDisputedText");this.fya=gvjs_E(a,"tooltip.showTitle");this.dya=d?"%s's administration (under dispute)":"%s";this.l_=gvjs_E(a,gvjs_kx);this.uma=10;this.Y1=this.Wq=this.MF=null;this.JB=gvjs_Nr;this.oK=
null;this.Rsa=gvjs_Iy(a,"markerOpacity");this.Osa=new gvjs_oY(this.kw.Xb(),new gvjs_A(0,b,c,0))}function gvjs_qla(a,b){for(var c=0,d=a.MF.length;c<d;c++)for(var e=a.MF[c].mX.features,f=0,g=e.length;f<g;f++){var h=e[f];if(h.id==b)return h}return null}function gvjs_rla(a,b){var c=gvjs_xY(a,a.pma),d={};gvjs_s(b.views,function(e){gvjs_s(e.features,function(f){d[f.id]={Vb:c}},this)},a);return d}
function gvjs_yY(a,b){for(var c=new gvjs__X,d=1;10>d;d++){var e=(a.Gi[1]-a.zh[1])/10*d+a.zh[1],f=(a.Gi[0]-a.zh[0])/10*d+a.zh[0];e=b.jA([f,a.zh[1]],[f,a.Gi[1]],[a.zh[0],e],[a.Gi[0],e]);c.track.apply(c,e)}a=c.getBounds("x");c=c.getBounds("y");return{Gi:[c.max,a.max],zh:[c.min,a.min]}}
function gvjs_sla(a,b,c){var d=new gvjs_3(b.Xya*a.kw.width+a.kw.left,b.eza*a.kw.height+a.kw.top,b.scale*a.kw.width,b.scale*a.kw.height),e=a.oK[c],f=gvjs_yY(b.Mu,e);return{id:String(c),Mu:f,V_:b.Mu,$D:d,features:gvjs_t(b.features,function(g){return gvjs_zY(a,f,d,e,g)})}}
function gvjs_zY(a,b,c,d,e){for(a=gvjs_tla(a,gvjs_LA(gvjs_By(e.polygons),gvjs_By(e.gn)));a[1]>b.Gi[1];)a[1]-=360;for(;a[1]<b.zh[1];)a[1]+=360;return{id:e.id,center:gvjs_AY(b,c,d,a),polygons:gvjs_t(e.polygons,function(f){return gvjs_BY(b,c,d,f)}),gn:gvjs_t(e.gn,function(f){return gvjs_BY(b,c,d,f)}),xO:"__DISPUTED__All"!=e.id}}function gvjs_tla(a,b){var c=0,d=0,e=0;gvjs_Cy(b,function(f){gvjs_s(f.ZK,function(g){c+=g[0];d+=gvjs_Yx(g[1],360);e++},this)},a);return[c/e,d/e]}
function gvjs_BY(a,b,c,d){return{ZK:gvjs_CY(a,b,c,d.ZK),GI:gvjs_t(d.GI,function(e){return gvjs_CY(a,b,c,e)})}}function gvjs_CY(a,b,c,d){return{points:gvjs_t(d,function(e){return gvjs_AY(a,b,c,e)})}}function gvjs_AY(a,b,c,d){var e=a.zh;a=a.Gi;var f=b.width,g=b.height,h=b.left;b=b.top;c=c.jA(d)[0];return[h+f*(c.x-e[1])/(a[1]-e[1]),b+g*(1-(c.y-e[0])/(a[0]-e[0]))]}
function gvjs_ula(a,b){var c=[];a.Wq=[];for(var d=gvjs_t(a.MF,function(l){return l.mX}),e=0;e<b.length;++e){var f=b[e],g={location:f,sX:{}};if(null!=f){f=gvjs_DY(a,e,f,d);gvjs_Re(c,f);for(var h=0;h<f.length;h++){var k=f[h];g.sX[k.hp]=k}}a.Wq.push(g)}gvjs_vla(c);return c}function gvjs_vla(a){for(var b=0;b<a.length;b++){for(var c=a[b],d=new gvjs_u(c.x,c.y),e=0,f=0;f<a.length;f++)if(b!=f){var g=a[f],h=gvjs_Gz(d,new gvjs_u(g.x,g.y));h<c.size+g.size&&(e+=c.size+g.size-h)}c.jD=e>c.size}}
function gvjs_DY(a,b,c,d){var e=a.fxa(b),f=a.M7(b);if(null==f)return[];f=new gvjs_2({stroke:a.Ssa,strokeWidth:a.Tsa,fill:f,fillOpacity:a.Rsa});var g=parseFloat(c.lat),h=[];c=parseFloat(c.lng);c=[c,c+360,c-360];for(var k=0;k<d.length;++k){var l=d[k],m=a.oK[k],n=l.V_;if(!(g<n.zh[0]||g>n.Gi[0])){for(var p=0;p<c.length;++p){var q=c[p];if(!(q<n.zh[1]||q>n.Gi[1])){q=gvjs_AY(l.Mu,l.$D,m,[g,q]);var r=String(b+"-"+l.id+"-"+p),t=gvjs_MX;if(null!=a.fb.wJ&&0<=a.fb.wJ)t=a.W.Ha(b,a.fb.wJ);else if(null!=a.fb.fG&&
0<=a.fb.fG)t=a.W.Ha(b,a.fb.fG);else if(null!=a.fb.tK&&0<=a.fb.tK)t=a.W.Ha(b,a.fb.tK);else if(null!=a.fb.uD&&null!=a.fb.BD&&0<=a.fb.uD&&0<=a.fb.BD){t=a.W.getValue(b,a.fb.uD);var u=a.W.getValue(b,a.fb.BD);t=gvjs_EY(t,"S","N")+" "+gvjs_EY(u,"W","E")}h.push({hp:r,label:t,yj:b,x:q[0],y:q[1],size:e,brush:f,jD:!1})}}if(0<h.length)break}}return h}
function gvjs_wla(a,b,c){var d=a.Wq,e=d[c],f=e.sX[b];if(!f.jD)return null;var g=Number(b.split("-")[1]),h=a.MF[g],k=a.oK[g],l=gvjs_F(a.m,"magnifyingGlass.zoomFactor"),m=a.Osa,n=m.ZV(e.location,h.mX,l);e=new gvjs_u(f.x,f.y);var p=gvjs_kla(m,e);k=gvjs_yY(n,k);var q=new gvjs_uY;c={id:g+"-"+c+"-mag",Mu:k,V_:n,$D:p,features:gvjs_t(h.features,function(r){return gvjs_zY(a,n,p,q,r)})};g=[];for(h=0;h<d.length;h++)k=d[h].location,null!=k&&gvjs_Re(g,gvjs_DY(a,h,k,[c]));return{hp:b,Xba:e,view:c,ID:g}}
function gvjs_FY(a,b){if(!a.ara||null==a.zs||!a.zs.Gl)return null;var c=a.Eba.fontSize,d=a.us.width,e=a.us.height,f={top:0,left:0,width:a.AQ==gvjs_0?d*a.Bba:e*a.Bba,height:1.5*c,orientation:a.AQ,oa:a.Eba,Vba:gvjs_0o,Qca:a.T0};f.top=a.CQ===gvjs_RX||"top_right"===a.CQ?3*c:a.AQ===gvjs_V?e-c-f.width:e-c-f.height;f.left=a.CQ===gvjs_RX||a.CQ===gvjs_CX?.5*c:a.AQ==gvjs_V?d-c-f.height:d-c-f.width;f.left+=a.us.left;f.top+=a.us.top;return gvjs_SG(a.zs,f,b,a.be)}
function gvjs_GY(a,b){for(var c=null,d=0;d<a.W.ca();++d){var e=a.W.getValue(d,b);c=gvjs_DA(c,e)}return c}function gvjs_ola(a){var b=a.fb.Zu;return null!=b?function(c){c=a.W.getValue(c,b);return null!=c?gvjs_OG(a.zs,c):a.YN}:function(){return a.YN}}function gvjs_pla(a){var b=a.fb.cF;return null!=b?function(c){c=a.W.getValue(c,b);return gvjs_qH(a.bL,c)}:function(){return a.uma}}function gvjs_vY(a){var b=a.fb.Zu;if(null==b)return null;b=gvjs_GY(a,b);return gvjs_RG(a.m,b)}
function gvjs_wY(a){var b=a.fb.cF;b=null!=b?gvjs_GY(a,b):null;return gvjs_rH(a.m,b)}
function gvjs_xla(a,b){var c={NC:[],OC:[]};null!=b.sf&&(c.NC=[b.sf]);null!=b.aI&&(c.OC=[b.aI]);c.vu=[];var d=a.yz&&(a.zF===gvjs_vt||a.zF===gvjs_Jw);gvjs_s(gvjs_Kn(b.selection),function(h){var k=gvjs_HY(this,h,!1),l=this.be,m=this.uu.Kd.fontSize,n=new gvjs_A(0,this.da-1,this.Pa-1,0),p=this.Wq[h];h=(h=this.Y1[h])&&gvjs_qla(this,h);var q=null,r=null;h?(c.NC.push(h.id),d&&(q=r=new gvjs_u(h.center[0],h.center[1]),c.vu.push(gvjs_pE(k,l,!1,r,n,q,void 0,this.l_)))):p&&gvjs_v(p.sX,function(t,u){c.OC.push(u);
d&&c.vu.push(gvjs_pE(k,l,!1,new gvjs_u(t.x-m,t.y-m),n,new gvjs_u(t.x,t.y),void 0,this.l_))},this)},a);if(null!=b.$j){if(a.yz&&(a.zF===gvjs_vt||a.zF===gvjs_Cu)){var e=gvjs_HY(a,b.$j.yj,b.$j.ZI),f=a.uu.Kd.fontSize,g=new gvjs_u(b.$j.origin.x,b.$j.origin.y);c.vu.push(gvjs_pE(e,a.be,!1,new gvjs_u(g.x-f,g.y-f),new gvjs_A(0,a.da-1,a.Pa-1,0),g,void 0,a.l_))}null!=a.fb.Zu&&(e={value:a.W.getValue(b.$j.yj,a.fb.Zu)},c.ej=gvjs_FY(a,[e]))}null!=b.hw&&(c.yJ=gvjs_wla(a,b.hw.hp,b.hw.yj));return c}
function gvjs_EY(a,b,c){b=0<=a?c:b;a=Math.abs(a);c=Math.floor(a);a=60*(a-c);var d=Math.floor(a);return c+"\u00b0"+d+"'"+Math.round(60*(a-d))+'"'+b}
function gvjs_HY(a,b,c){var d=a.fb,e=a.W,f={entries:[]};if(null!=d.wJ)var g=e.Ha(b,d.wJ);else switch(d.iV){case gvjs_cd:c=e.getValue(b,d.uD);g=e.getValue(b,d.BD);g=gvjs_EY(c,"S","N")+" "+gvjs_EY(g,"W","E");break;case gvjs_Bd:g=e.Ha(b,d.tK);c&&(g=gvjs_Qq(a.dya,g));break;case "address":g=e.Ha(b,d.fG);break;default:g=""}a.fya&&(c=gvjs_mE(g,a.uu.bold),f.entries.push(c));c=null!=d.y4?e.getStringValue(b,d.y4):null;if(null!=c)if(d=d.y4,e.Xe(d,gvjs_dv)||e.getProperty(b,d,gvjs_dv))f.entries.push(gvjs_mE(c,
a.uu.Kd,void 0,void 0,void 0,void 0,void 0,!0));else for(b=c.split("\n"),e=0;e<b.length;e++)d=gvjs_mE(b[e],a.uu.Kd),f.entries.push(d);else null!=d.Zu&&(c=e.Ca(d.Zu),g=e.Ha(b,d.Zu),c=gvjs_mE(g,a.uu.bold,c,a.uu.Kd),f.entries.push(c)),null!=d.cF&&d.cF!=d.Zu&&(c=e.Ca(d.cF),b=e.Ha(b,d.cF),a=gvjs_mE(b,a.uu.bold,c,a.uu.Kd),f.entries.push(a));return f}
function gvjs_xY(a,b){var c=b===gvjs_e?[255,255,255]:gvjs_Th(b);c=gvjs_Sh(gvjs_wA(c,.1));return{fill:new gvjs_2({stroke:c,fill:b}),gn:new gvjs_2({stroke:gvjs_e,pattern:new gvjs_Qx(gvjs_rw,b,b==a.JB?gvjs_Qr:a.JB)}),border:new gvjs_2({stroke:c})}};function gvjs_IY(a,b,c,d,e,f,g,h,k){gvjs_I.call(this);var l=this;this.om=a;this.m=b;this.da=c;this.Pa=d;this.fb=f;this.J=g;this.kn=null;this.V1=!1;this.kva=h;this.mn=k;this.V3=!1;this.uX=null;this.d6=!1;this.Db=new gvjs_VJ(function(){return l.Vt()});this.GD=new gvjs_qI(3);this.$N=[!1,!1,!1];this.FD=new gvjs_nla(this.m,this.da,this.Pa,this.om.hf,e,this.fb);this.Lba=new gvjs_pY(a,b,g,this.Db);this.h9=gvjs_E(b,"enableRegionInteractivity",f.zX==gvjs_Cd);this.e9=gvjs_E(b,"enableMarkerInteractivity",f.zX==
gvjs_fd);this.Z1()}gvjs_m(gvjs_IY,gvjs_I);gvjs_=gvjs_IY.prototype;
gvjs_.b3=function(a,b){var c=this.FD,d=c.m;c.MF=[];c.oK=[];for(var e=[],f=0,g=a.views.length;f<g;f++){var h=a.views[f],k=c.P1.cd();k.boundingBox={lo:h.Mu.zh,hi:h.Mu.Gi};k=new c.P1.constructor(k);c.oK.push(k);k=gvjs_sla(c,h,f);e.push(k);c.MF.push({features:h.features,mX:k})}a={width:c.da,height:c.Pa,Qsa:c.kw,LE:gvjs_D(d,gvjs_Kw,gvjs_Zp,gvjs_zF),yDa:c.zF,xG:gvjs_Ly(d,gvjs_kt),w$:d.rz(gvjs_Vu),title:{text:gvjs_D(d,gvjs_ex),oa:gvjs_My(d,gvjs_gx,{hb:c.oX,fontSize:c.C8}),lines:[],align:gvjs_1,tooltip:""},
views:e,qC:gvjs_rla(c,a),NC:[],OC:[],ID:[],ej:null,yJ:null,Tk:c.oX};this.WK(0,a);this.V3=!0;this.mn("mapLoaded",b);null!=this.uX?this.uX():this.Vt()};
function gvjs_yla(a,b,c,d,e,f){function g(){a.d6=d;if(null!=e){a.kn=null;var h=a.FD;h.W=e;h.zs=gvjs_vY(h);h.bL=gvjs_wY(h)}null!=f&&(a.J=f,a.Lba.J=f);h=a.FD;h.Y1=[];for(var k={},l=0;l<h.W.ca();++l){var m=b[l];h.Y1.push(m);if(null!=m){var n=h.M7(l);null!=n&&(k[m]={yj:l,Vb:gvjs_xY(h,n)})}}h={qC:k,ID:gvjs_ula(h,c),ej:gvjs_FY(h,[])};a.WK(1,h);a.Vt()}a.V1=!1;a.V3?g():a.uX=g}gvjs_.setSelection=function(a){this.J.selection.setSelection(a);gvjs_WJ(this.Db,1)};gvjs_.getSelection=function(){return this.J.selection.getSelection()};
gvjs_.Vt=function(){if(this.V3){if(null==this.kn||!this.kn.equals(this.J)){var a=gvjs_xla(this.FD,this.J);this.WK(2,a)}a=this.GD.compact();if(this.$N[0])gvjs_8X(this.om,a);else if(this.$N[1]){var b=this.om;gvjs_kY(b,a);gvjs_gY(b,a);gvjs_fY(b,a,!0)}else gvjs_fY(this.om,a);this.$N=[!1,!1,!1];this.kn=this.J.clone();!this.V1&&this.d6&&(this.kva(),this.V1=!0)}};function gvjs_JY(a,b){null!=a.J.$j&&b.data.yb&&(a.J.$j.origin={x:b.data.yb.x,y:b.data.yb.y},gvjs_WJ(a.Db,3))}
gvjs_.mt=function(a,b){a=this.GD.compact().LE==gvjs_Zp;null!=b?(gvjs_Ry(this.J.selection,b,a),this.mn(gvjs_i,{})):(b=0<this.J.selection.getSelection().length,this.J.selection.clear(),b&&this.mn(gvjs_i,{}));this.Db&&gvjs_WJ(this.Db,50)};function gvjs_KY(a,b){var c=a.GD.compact();return a.Lba.handleEvent(b,c?c.yJ:null)}
gvjs_.Z1=function(){var a=this;this.om.D(gvjs_EX,function(b){if(!gvjs_KY(a,b)&&a.h9){var c=b.data.featureId;null!==c&&a.mn("regionClick",{region:c});c=gvjs_LY(a,c);a.mt(b,c)}});this.om.D(gvjs_FX,function(b){if(!gvjs_KY(a,b)&&a.h9){var c=b.data.featureId;null!==c&&(b.data.ap?(a.J.sf=c,c=gvjs_LY(a,c),a.J.$j=null!=c?{yj:c,ZI:b.data.ZI,origin:{x:b.data.yb.x,y:b.data.yb.y}}:null):(a.J.sf=null,a.J.$j=null),gvjs_WJ(a.Db,50))}});this.om.D(gvjs_GX,function(b){gvjs_KY(a,b)||gvjs_JY(a,b)});this.om.D(gvjs_NX,
function(b){gvjs_KY(a,b)||a.e9&&a.mt(b,b.data.yj)});this.om.D(gvjs_OX,function(b){!gvjs_KY(a,b)&&a.e9&&(b.data.ap?(a.J.aI=b.data.hp,a.J.$j={yj:b.data.yj,ZI:!1,origin:{x:b.data.yb.x,y:b.data.yb.y}}):(a.J.aI=null,a.J.$j=null),gvjs_WJ(a.Db,50))});this.om.D("markerMove",function(b){gvjs_JY(a,b)})};function gvjs_LY(a,b){if(null===b)return null;a=a.GD.compact();return a.qC[b]?a.qC[b].yj:null}gvjs_.WK=function(a,b){gvjs_rI(this.GD,a,b);this.$N[a]=!0};
gvjs_.O=function(){gvjs_J(this.Db);this.Db=null;gvjs_J(this.om);this.om=null;gvjs_J(this.FD);this.FD=null;gvjs_I.prototype.O.call(this)};var gvjs_MY={},gvjs_NY={},gvjs_OY=null,gvjs_PY=null;function gvjs_zla(a,b,c){""!==a&&(gvjs_PY=a=a.replace(/\/$/,""));gvjs_NY={};gvjs_QY=null;gvjs_RY("info","mapList",function(d){gvjs_SY=d;b()},c)}function gvjs_TY(a){gvjs_PY="https://www.gstatic.com/charts/geochart/"+a}gvjs_TY("10");
function gvjs_RY(a,b,c,d){gvjs_Rl(gvjs_PY+"/"+a+"/"+(b+".js")).then(function(e){e=e.replace(/^[\s\S]*google_visualization_geochart_[^=]*\s*=\s*/g,"");e=e.replace(/;[\s]*$/g,"");e=JSON.parse(e);c&&c(e);return e},function(e){d&&d(e)})}
function gvjs_Ala(a,b){if(null==b)throw Error("Callback is null or undefined");var c=gvjs_Bla(a);void 0!==gvjs_NY[c]?setTimeout(function(){return b(gvjs_NY[c])},0):void 0!==gvjs_MY[c]?gvjs_MY[c].push(b):(gvjs_MY[c]=[b],gvjs_RY("mapfiles",c,function(d){var e={views:gvjs_t(d.views,gvjs_Cla)};gvjs_NY[c]=e;gvjs_s(gvjs_MY[c],function(f){f(e)});delete gvjs_MY[c]},function(){gvjs_s(gvjs_MY[c],function(d){d(null)});delete gvjs_MY[c]}))}
function gvjs_Bla(a){var b="";"COM"!=a.domain&&(b=a.domain+"_");return b+a.region+"_"+gvjs_UY(a.resolution)}function gvjs_UY(a){null==gvjs_OY&&(gvjs_OY={continents:"REGIONS",subcontinents:"SUBREGIONS",countries:gvjs_uS,provinces:"PROVINCES",metros:"METROS"});return gvjs_OY[a]}var gvjs_SY=null;function gvjs_VY(a){if(!gvjs_SY)return!1;var b=a.domain,c=a.region;a=gvjs_UY(a.resolution);if(b=gvjs_SY[b])if(b=b[a])return 0<=gvjs_Bz(b,c);return!1}var gvjs_QY=null;
function gvjs_Dla(a){null!=gvjs_QY?a(gvjs_QY):gvjs_RY("info","boundingBoxes",function(b){gvjs_QY=b=gvjs_t(b,gvjs_Ela);a(b)},function(){a(null)})}
function gvjs_Cla(a){for(var b=gvjs_t(a.features,gvjs_Fla),c={},d=[],e=0;e<b.length;e++){var f=b[e],g=f.id;gvjs_Hf(g,"__DISPUTED__")?c[g]=f:d.push(f)}for(b=0;b<d.length;b++)e=d[b],f=c["__DISPUTED__"+e.id],e.gn=f?f.polygons:[];if(c=c.__DISPUTED__All)c.gn=c.polygons,d.push(c);return{features:d,Mu:gvjs_WY(a.boundingBox),Xya:a.xoffset,eza:a.yoffset,scale:a.scale}}function gvjs_Fla(a){return{id:a.id,polygons:gvjs_t(a.polygons,gvjs_Gla),gn:[]}}
function gvjs_Gla(a){return gvjs_qe(a)?{ZK:gvjs_XY(a),GI:[]}:{ZK:gvjs_XY(a.shell),GI:gvjs_t(a.holes,gvjs_XY)}}function gvjs_XY(a){return gvjs_t(a,function(b){return[gvjs_ZX(b[0]),parseFloat(b[1])]})}function gvjs_WY(a){return{Gi:[gvjs_ZX(a.hi[0]),parseFloat(a.hi[1])],zh:[gvjs_ZX(a.lo[0]),parseFloat(a.lo[1])]}}function gvjs_Ela(a){return{region:a.region,resolution:a.resolution,domain:a.domain,Lka:gvjs_t(a.boundingBoxes,gvjs_WY)}};function gvjs_YY(a,b,c,d){var e=gvjs_D(c,gvjs_GS);if(e!=gvjs_yb)d(gvjs_ZY(e,c));else if(b.iV!=gvjs_cd)d(gvjs_ZY(gvjs_LS,c));else{var f=c.mb(gvjs_HS,gvjs_UX),g=c.mb(gvjs_ru),h=[];for(e=0;e<a.ca();++e)h.push({lat:a.getValue(e,b.uD),lng:a.getValue(e,b.BD)});gvjs_Dla(function(k){if(k){a:{for(var l=0;l<k.length;++l){var m=k[l];if(null==f||m.resolution==f)if(null==g||m.domain==g){for(var n=!0,p=0;p<h.length;++p){for(var q=h[p],r=!1,t=m.Lka,u=0;u<t.length;++u)if(gvjs_Hla(q,t[u])){r=!0;break}if(!r){n=!1;
break}}if(n){k={region:m.region,resolution:m.resolution,domain:m.domain};break a}}}k=null}null!=k?d(k):d(gvjs_ZY(gvjs_LS,c))}else d(null)})}}function gvjs_ZY(a,b){var c=gvjs_D(b,gvjs_HS,gvjs_yS,gvjs_UX);b=gvjs_D(b,gvjs_ru);a={region:a,resolution:c,domain:b};return gvjs_VY(a)||"COM"!=a.domain&&(a.domain="COM",gvjs_VY(a))?a:null}function gvjs_Hla(a,b){return a.lat>b.zh[0]&&a.lat<b.Gi[0]&&gvjs_He([-360,0,360],function(c){return a.lng+c>b.zh[1]&&a.lng+c<b.Gi[1]})};var gvjs_Ila=gvjs_M.removeAll;function gvjs__Y(a){gvjs_O.call(this,a);this.Jk=this.Ta=null;this.Jz=new gvjs_3X(this.Ai);this.B_="";this.bb=this.Qj=null}gvjs_m(gvjs__Y,gvjs_O);function gvjs_0Y(a){null==a&&(a={});a=new gvjs_ji([a,gvjs_2X]);var b=gvjs_D(a,gvjs_GS);return null!=gvjs_ZY(b,a)}function gvjs_1Y(a,b,c){a=a||"";var d=gvjs_2Y&&a===gvjs_3Y;gvjs_3Y=a;b?d?b():gvjs_zla(a,function(){gvjs_2Y=!0;b()},c):gvjs_2Y=!1}gvjs_=gvjs__Y.prototype;
gvjs_.hg=function(a,b,c,d){var e=this;c=void 0===c?{}:c;gvjs_Ila(this.container);this.Qj=a;gvjs_J(this.Jz);this.Jz=new gvjs_3X(this.Ai);c=gvjs_Sg(gvjs_Pg(c));a=[c];var f=c.theme||[];Array.isArray(f)||(f=[f]);for(var g=0;g<f.length;++g){var h=void 0;if(typeof f[g]===gvjs_j)h=gvjs_oH(f[g]);else if(gvjs_p(f[g]))h=f[g];else throw Error("Theme should be a theme name or an options object.");a.push(h)}a.push(gvjs_2X);var k=gvjs_jK(),l=[];gvjs_s(a,function(t){l.push.apply(l,gvjs_OA(t,k))});var m=new gvjs_ji(a),
n=new gvjs_TX(d);this.bb=this.Bv(this.container,m);d=gvjs_D(m,"displayMode",gvjs_yb,gvjs_2ka);var p=(new gvjs_tn).Ic(b,d,this.Ai);if(null!=p){var q=gvjs_jf({options:c,format:p,size:this.bb}),r=this.Qj(function(t){if(null==t)throw Error(gvjs_AX);gvjs_Jla(this,b,p,m,q,n,t)},this);c=gvjs_3Y;c=gvjs_D(m,"mapsSource",c);""===c&&(d=gvjs_D(m,"geochartVersion","10"),gvjs_TY(d));d=gvjs_D(m,"regioncoderVersion","0");gvjs_WS(d);gvjs_1Y(c,function(){l.length&&e.al?(e.al.Bw.then(function(){gvjs_YY(b,p,m,r)},null,
e),gvjs_Qy(e,function(){gvjs_YY(b,p,m,r)}),new gvjs_iK(l,e.al)):gvjs_YY(b,p,m,r)})}};gvjs_.Di=function(){if(!this.Jk)throw Error("Must draw chart before calling getImageURI.");var a=gvjs_fh(this.container).createElement(gvjs_Sb),b=gvjs__q(a,this.bb),c=new gvjs_Pq(a),d=new gvjs_8A(a,b);b=this.Jk;c=new gvjs_7X(c,d,b.om.fb);b=b.GD.compact();gvjs_8X(c,b);gvjs_kY(c,b);gvjs_gY(c,b);gvjs_fY(c,b,!0);gvjs_fY(c,b);return a.childNodes[0].toDataURL("image/png")};
gvjs_.Bv=function(a,b){a=this.Oa(b,-1);b=this.getHeight(b,-1);-1==a&&-1==b?(a=556,b=347):-1==a?a=Math.round(556*b/347):-1==b&&(b=Math.round(347*a/556));return new gvjs_y(a,b)};function gvjs_Jla(a,b,c,d,e,f,g){var h=gvjs_E(d,"showGeocodeWarnings");if(a.B_==e)gvjs_4Y(a,!1,d,b,c,g,h,f,e);else{if(null!=a.Ta)a.Ta.update(a.bb,a.Qj);else{var k=gvjs_E(d,gvjs_Ju);a.Ta=new gvjs_Xq(a.container,a.bb,a.Qj,k)}a.Ta.fo(function(){var l=a.Ta.$a(),m=a.Ta.xv();gvjs_Kla(a,b,c,d,e,f,g,h,m,l)},a.Qj)}}
function gvjs_Kla(a,b,c,d,e,f,g,h,k,l){k=new gvjs_7X(k,l,c);null!=a.Jk&&gvjs_J(a.Jk);l=a.bb;gvjs_J(a.Jk);a.Jk=new gvjs_IY(k,d,l.width,l.height,b,c,f,function(){gvjs_N(a,gvjs_g,{})},function(m,n){gvjs_N(a,m,n)});gvjs_4Y(a,!0,d,b,c,g,h,f,e)}
function gvjs_4Y(a,b,c,d,e,f,g,h,k){function l(){gvjs_ala(a.Jz,d,e,f,g,n)}c=gvjs_D(c,"geocodingContext",gvjs_GS,gvjs_9ka);var m="bounds"===c||c===gvjs_vt,n=a.Qj(function(p,q,r){gvjs_yla(a.Jk,p,q,r,d,h)});a.Jz.fI=c;b&&(a.Jz.gF=null,gvjs_Ala(f,a.Qj(function(p){null!=p?(a.Jk.b3(p,f),m&&(a.Jz.b3(p),l()),a.B_=k):a.Ai.pe(gvjs_AX)})));m||(a.Jz.gF=null,l())}gvjs_.setSelection=function(a){null!=this.Jk?this.Jk.setSelection(a):this.Ai.pe(gvjs_BX)};
gvjs_.getSelection=function(){if(null!=this.Jk)return this.Jk.getSelection();this.Ai.pe(gvjs_BX);return[]};gvjs_.nf=function(){this.B_="";gvjs_J(this.Jk);this.Jk=null;gvjs_J(this.Ta);this.Ta=null};var gvjs_3Y="",gvjs_2Y=!1;gvjs_o(gvjs_sc,gvjs__Y,void 0);gvjs__Y.prototype.draw=gvjs__Y.prototype.draw;gvjs__Y.prototype.getImageURI=gvjs__Y.prototype.Di;gvjs__Y.prototype.setSelection=gvjs__Y.prototype.setSelection;gvjs__Y.prototype.getSelection=gvjs__Y.prototype.getSelection;
gvjs__Y.prototype.clearChart=gvjs__Y.prototype.Lb;gvjs_o(gvjs_HX,gvjs_0Y,void 0);gvjs_o(gvjs_IX,gvjs_1Y,void 0);gvjs_o(gvjs_sc,gvjs__Y,void 0);gvjs__Y.prototype.draw=gvjs__Y.prototype.draw;gvjs__Y.prototype.getImageURI=gvjs__Y.prototype.Di;gvjs__Y.prototype.setSelection=gvjs__Y.prototype.setSelection;gvjs__Y.prototype.getSelection=gvjs__Y.prototype.getSelection;gvjs__Y.prototype.clearChart=gvjs__Y.prototype.Lb;gvjs_o(gvjs_HX,gvjs_0Y,void 0);gvjs_o(gvjs_IX,gvjs_1Y,void 0);
