var gvjs_uS="COUNTRIES",gvjs_vS="Data has no columns.",gvjs_wS="Geocoding failed for all data points",gvjs_xS="The columns type does not match the supported data format. See documentation for supported formats.",gvjs_yS="countries",gvjs_zS="datalessRegionColor",gvjs_AS="defaultColor",gvjs_BS="enableScrollWheel",gvjs_CS="gviz.util.RegionCoder.dictionaryReady",gvjs_DS="hybrid",gvjs_ES="mapType",gvjs_FS="provinces",gvjs_GS="region",gvjs_HS="resolution",gvjs_IS="showLine",gvjs_JS="useLargeControl",gvjs_KS=
"useMapTypeControl",gvjs_LS="world";function gvjs_MS(a,b,c){if(gvjs_p(b)&&(b=gvjs_cf(b),b.bounds)){var d=b.bounds;b.bounds=new google.maps.LatLngBounds(new google.maps.LatLng(d.lo.lat,d.lo.lng),new google.maps.LatLng(d.hi.lat,d.hi.lng))}a.yC.geocode(b,c)}function gvjs_NS(a,b,c){var d=gvjs_Og(b),e=a.Ew.get(d);null!=e&&gvjs_s(e,function(f){f.fN||f.finish(b,c)});a.xx.remove(d);a.Ew.remove(d)}
gvjs_bn.prototype.vI=gvjs_W(18,function(a,b,c){var d=0;if(c==google.maps.GeocoderStatus.OVER_QUERY_LIMIT)d=520;else if(c==google.maps.GeocoderStatus.OK){var e=gvjs_Og(a);b={response:b,status:c};this.Dd[e]=b;gvjs_NS(this,a,b)}else gvjs_NS(this,a,{response:null,status:c});this.YI=!1;gvjs_lm(gvjs_q(this.xY,this),d,this)});
gvjs_bn.prototype.xY=gvjs_W(17,function(){if(0!==this.fE.tb()||0!==this.xx.tb()){var a=0<this.xx.tb()?gvjs_Ng(this.xx.La()[0]):this.fE.peek(),b=gvjs_Og(a);if(b in this.Dd){var c=this.Ew.get(b);c=this.Dd[b];gvjs_Ox(this.fE);this.vI(a,c.response,c.status);this.Ew.remove(b)}else 0===this.xx.tb()&&0<this.fE.tb()?(gvjs_Ox(this.fE),c=this.Ew.get(b),gvjs_Ie(c,function(d){return d.fN})?this.vI(a,null,null):(this.xx.add(b),gvjs_MS(this,a,gvjs_q(this.vI,this,a)))):0<this.xx.tb()&&gvjs_MS(this,a,gvjs_q(this.vI,
this,a))}});function gvjs_hja(a,b){gvjs_s(b.Xt,gvjs_q(function(c){var d=gvjs_Og(c);d in this.Dd?b.finish(c,this.Dd[d]):(this.Ew.Pe(d)||(this.fE.enqueue(c),this.Ew.set(d,[])),this.Ew.get(d).push(b))},a));a.xY()}var gvjs_OS=[];function gvjs_PS(){return!!gvjs_me("google.maps.DirectionsService")}
function gvjs_QS(a,b){function c(){if(gvjs_PS()){var d=gvjs_OS;gvjs_OS=[];gvjs_s(d,function(e){e()})}else throw Error("Error: cannot load Maps API.");}gvjs_PS()?a():(gvjs_OS.push(a),1==gvjs_OS.length&&(a=b||gvjs_me("google.visualization.mapsApiKey"),gvjs_zba(gvjs_hca,{key:typeof a===gvjs_j?a:""}).then(c)))}function gvjs_RS(a,b,c){this.Xt=a||[];this.BK=0;this.Kx=b;this.fN=!1;this.oS=new gvjs__h;this.Dka=c||this.Xt.length}gvjs_RS.prototype.cancel=function(){this.fN=!0};
gvjs_RS.prototype.finish=function(a,b){a=gvjs_Og(a);this.oS.Pe(a)||this.oS.set(a,b);b=[];if(!this.fN){a=this.Xt.length;for(var c=this.BK;c<a;c++){var d=gvjs_Og(this.Xt[c]);if(!this.oS.Pe(d))break;d=this.oS.get(d);null!=d&&(d=d.response);b.push(d)}b.length<this.Dka&&this.BK+b.length<a||(this.BK+=b.length,this.Kx(b),this.BK>=this.Xt.length&&this.cancel())}};function gvjs_SS(){this.Xt=[];this.yC=null}gvjs_SS.prototype.add=function(a){this.Xt.push(a)};
gvjs_SS.prototype.create=function(a,b,c,d){if(null!=this.yC)d=new gvjs_RS(a,b,c),this.add(d),gvjs_hja(this.yC,d);else{var e=gvjs_q(function(){null==this.yC&&(this.yC=gvjs_bn.kc());this.create(a,b,c)},this);gvjs_QS(e,d)}};gvjs_SS.prototype.cancel=function(){gvjs_s(this.Xt,function(a){a.cancel()});this.Xt=[]};function gvjs_ija(a){this.Gma=a}var gvjs_TS={},gvjs_US="0",gvjs_VS="https://www.gstatic.com/charts/regioncoder/0/";
function gvjs_WS(a){gvjs_US=a;gvjs_VS="https://www.gstatic.com/charts/regioncoder/"+a+"/"}gvjs_WS(gvjs_US);function gvjs_XS(a,b){a=gvjs_Kf(a.toLowerCase());a=encodeURIComponent(String(a));var c=gvjs_TS[a];null==c?(c=[b],gvjs_TS[a]=c,gvjs_jja(a,function(d){gvjs_YS(a,d)},function(){gvjs_YS(a,null)})):Array.isArray(c)?gvjs_Uy(c,b):gvjs_lm(gvjs_ve(b,c),0)}
function gvjs_jja(a,b,c){gvjs_Rl(gvjs_VS+"/geocodes/"+(a+".js")).then(function(d){d=d.replace(/^[\s\S]*var results\s*=\s*/g,"");d=d.replace(/;\s*gviz\.util\.RegionCoder\.dictionaryReady[\s\S]*$/g,"");d=JSON.parse(d);b&&b(d);return d},function(d){c&&c(d)})}function gvjs_YS(a,b){var c=gvjs_TS[a];if(b){if(b=new gvjs_ija(b),Array.isArray(c))for(gvjs_TS[a]=b,a=0;a<c.length;a++)c[a](b)}else if(Array.isArray(c))for(gvjs_TS[a]=null,a=0;a<c.length;a++)c[a](null)}gvjs_o(gvjs_CS,gvjs_YS,void 0);
function gvjs_ZS(a,b){b=gvjs_Kf(b.toLowerCase());return a.Gma[b]};gvjs_o(gvjs_CS,gvjs_YS,void 0);
