---
title: "Introduction"
output: pdf_document
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Introduction \label{section:introduction}

Over 800 universities in the United States accommodate fraternities [@hechinger_true_2017]. Many have documented benefits of membership which include higher future income [@mara_social_2018] and significantly more hours spent participating in community service and volunteering [@hayek_triumph_2002;asel_effects_2009]. Moreover, according to a Gallup survey in 2021, over 80 percent of fraternity alumni agreed that they would join their fraternity if they were to redo their college experience.

Despite these benefits, membership has been shown to cause risky behaviors. In particular, at least one hazing-related death has occurred between the years 2000 and 2019^[This is based on the online repository of hazing deaths from journalist Hank Nuwer. See here:https://www.hanknuwer.com/hazing-destroying-young-lives/] and studies have found that fraternity members binge drink and party more frequently than their non-member peers [@desimone_fraternity_2007;@routon_impact_2014]. While universities have commonly banned specific misbehaving fraternities from their campuses, the past decade popularized a new policy tool called moratoriums—campus-wide halts on fraternity social events with alcohol—as a way to change member behavior. 

This paper is the first to estimate the causal effects of moratoriums on campus-wide police reports of alcohol offenses and sexual assaults. Since 2010, over 50 moratoriums have been enacted across university campuses, thus becoming a common policy used among school administrators. However, no prior research has investigated this topic; moratorium dates are difficult to find/confirm and there does not exist a centralized data source for university-specific crime with fine enough detail for casual inference. Despite this lack of research, administrators continue to use moratoriums as a disciplinary action on their fraternities.

Nonetheless, how these moratoriums affect student behavior, and thus on-campus crime, is theoretically unclear. On one hand, prohibiting alcohol from fraternity social events may reduce incidences of crime. Fraternities are a common source of alcohol for underage drinking, as fraternities are typically a mix of lower and upperclassmen [@armstrong_sexual_2006]. The inclusion of legal-age drinkers and large social events allows for easy access to alcohol for underage students. Given that the literature has documented that alcohol causes higher prevalence of crimes such as assaults and alcohol offenses [@carpenter_minimum_2015], road accidents and arrests [@francesconi_liquid_2019], and reports of rape [@zimmerman_alcohol_2007;@lindo_college_2018], prohibiting such events could reduce the incidence of on-campus crime. On the other hand, moratoriums may have the opposite effect. Without alcohol-fueled fraternity parties, students may substitute away from consuming alcohol at fraternity houses to potentially riskier places off-campus where behavior is less regulated. As a result, the net effect of moratoriums is ambiguous. 

In this paper, I estimate the causal effect of 45 fraternity moratoriums across 38 universities over a six-year period (2014-2019) on university police reports of alcohol, drug, and sexual assaults offenses. I use a difference-in-differences identification strategy, leveraging the variation in timing of moratoriums. Intuitively, I compare academic-calendar days (e.g., excluding summer and winter breaks) with a moratorium to academic-calendar days without a moratorium while accounting for expected differences across days of the week and different times of the year. I construct a novel data set, merging together two particularly unique data sources: university-specific Daily Crime Logs, which contain the universe of all reported incidences of crime to the university police at the incident-level, and moratorium start and end dates obtained through school newspapers and public records requests. 

Using these data, I find that moratoriums significantly decrease alcohol offenses campus-wide on academic-calendar days by 27%. This effect is driven by weekends (Fridays-Sundays) when college partying is more frequent and is robust across various specifications, estimation methods, and sensitivity tests. Furthermore, I find weaker evidence that reports of sexual assaults decrease by 26% on the weekends. Both of these decreases are concentrated only when a moratorium is in place suggesting that moratoriums possess no long-run effects on student behavior.

Importantly, I am not able to directly attribute these decreases to fraternity members themselves. Hence, while a working paper by @raghav_greek_2021 shows that a larger percentage of enrolled students in fraternities is associated with an increase in the number of drug-law arrests, the results in this paper cannot claim that the reductions are ascribed to members only. However, similarly to [@liang_go_2008], this paper does provide evidence that stronger sanctions on alcohol decreases risky behavior. Hence, this paper more broadly relates to the literature relating to the effects of alcohol on college-aged individuals which include increases in mortality [@carpenter_effect_2009], emergency room visits [@francesconi_liquid_2019],and crime [@carpenter_minimum_2015], in addition to hindering academic performance [@carrell_does_2011;@ha_legal_2019].

Most closely related to this paper is @lindo_college_2018 whom find a large 28% increase in daily reports of rape on days with college football games. This paper differs from this work on several levels. First, while college football games intensify binge drinking and partying behavior, studies have also linked such increases with fraternity membership [@desimone_fraternity_2007;@routon_impact_2014]. As such, fraternities are an important component to party culture within universities since fraternities are a reliable source of alcohol for underage students [@armstrong_sexual_2006]. Moratoriums therefore represent an understudied policy lever that university officials can use to reduce campus-wide partying, which in-turn, may reduce reports of sexual assaults. Second, since this study focuses on sanctions against university fraternities and uses only university-police crime reports, I am able to more closely link moratoriums with changes in *student* behavior rather than *non-student* behavior—college football attracts a large demographic whom are not necessarily students of the university. Last, as shown in @cunningham_decriminalizing_2018 who study the effects of decriminalizing and criminalizing prostitution on rape, there is reason to anticipate asymmetries in *increases* of partying (football games) and *decreases* in partying (moratoriums). However, the daily reductions in reports of sexual assault I find (26%) are similar to those of @lindo_college_2018 (28%).

This paper proceeds as follows: Section \ref{section:background} discusses the background on fraternities and moratoriums. Section \ref{section:data} describes the construction of the data. Section \ref{section:strategy} describes the empirical strategy used to estimate causal effects. Section \ref{section:results} presents the results. Section \ref{section:heterogeneity} explores the differences in effectiveness between different types of moratoriums. Section \ref{section:conclusion} concludes.

# Fraternities in the US \label{section:background}

## Background

Fraternities consist of students from families of higher-than-average educational attainment and income; they are predominantly white, and prior research has linked fraternity membership to positive outcomes such as increases in graduation rates [@routon_impact_2014], future income [@mara_social_2018]. On the other hand, membership has been found to decrease GPA [@de_donato_effects_2017;@even_greek_2020] and cause members to spend approximately two more hours per-week partying than nonmembers [@routon_impact_2014] and binge drink on approximately 2 additional days per-month [@desimone_fraternity_2007]. Additionally, @even_greek_2020 find that membership causes students to select into easier courses and complete less course credits. While not causal, there is survey evidence that fraternity members are more accepting of sexual violence than nonmembers [@seabrook_examining_2019] and that sorority women, whom frequently interact with fraternity men, are four times more likely to be a victim of sexual assault than nonmembers [@minow_sorority_2009].

This paper focuses on the Interfraternity Council (IFC) fraternities which are known as social fraternities. These fraternities are the most common at universities and differ from the professional, academic, or service fraternities. IFC fraternities participate in philanthropy and professional development and according to their creed, they “exist to promote the shared interests and values of our member fraternities: leadership, service, brotherhood and scholarship” [@hechinger_true_2017]. Importantly, it is the IFC fraternities that are restricted by a moratorium in the sample.

Each IFC fraternity chapter^[A chapter, or otherwise known as a "house" is a unique fraternity. A fraternity can have many chapters across the US, with usually one per-school.] has three sources of oversight: the chapter national headquarters, the parent university, and the parent university’s own IFC council—a group of student representatives from each recognized IFC fraternity chapter whom regularly meet with university staff to discuss rules/boundaries. Failure to abide by the rules outlined by these overseers' policies can result in a fraternity being unrecognized by the university which is costly—a fraternity relies on the university for new students to recruit.  

## Moratoriums

A moratorium is defined as a temporary ban on social events with alcohol for IFC fraternities.^[This is the minimum requirement for a moratorium in this paper. Some universities ban alcohol at social events for all IFC fraternities in addition to the rest of their Fraternity and Sorority Life. However, IFC fraternities are generally the main focus.] The timing and length of a moratorium varies substantially. Figure \ref{closure_distribution} shows the start and end dates of each moratorium over time. Moratoriums in the sample can last as few as 6 calendar-days, or as long as 848 calendar-days.^[Note the distinction between calendar-days and academic-calendar days. A calendar day represent the entire calendar, whereas an academic-calendar represents only the fall/spring semesters of the university school year.] Additionally, moratoriums are the generally implemented because of a triggering event (see Figure \ref{reasons_table}). This event can be a prominent sexual assault allegation, a fraternity-related death (usually due to alcohol poisoning), or an extreme behavior violation.^[A behavior violation is a catchall term for hazing, rule violations, offensive behavior, and other disorderly conduct that results in a moratorium.] Figure \ref{trigger_plot} shows the distribution of the triggering events: 18 are triggered by behavior violations, 10 by sexual assaults, 10 by a fraternity-related death, and 7 are unspecified. As alluded to in the introduction, moratoriums are enacted across the US. Figure \ref{map_of_schools} shows the locations of the 38 universities in the sample. While most universities are located in the mid-west and south, there are several universities from both the west and east coast.

Moratoriums can be implemented by two sources of jurisdiction: the university or the IFC. When a moratorium is implemented by the university, the university sets the guidelines that fraternities must abide by during the moratorium. The minimum guideline in the sample is that all social events with alcohol are prohibited, although other guidelines can be enforced (e.g., additional sexual harassment training). On the other hand, an IFC-implemented moratorium is student-enforced. This means that the IFC council is responsible for oversight. Figure \ref{trigger_plot} shows that IFC-implemented moratoriums are less frequent (17) than university-implemented moratoriums (28) and Section \ref{section:heterogeneity} examines the heterogeneous effects involving this difference in oversight.


