---
title: "Discussion and Conclusion"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Discussion and Conclusion

In this paper, I estimate the causal effect of temporary bans of fraternity social events with alcohol (moratoriums) on campus-wide alcohol, drug, and sexual assaults across 38 universities in the US. I construct a novel dataset which includes daily-level incidence reports from each university-specific police department. Using this data, I compare academic calendar days with a moratorium to academic calendar days without a moratorium while controlling for expected differences in the days of the week, holidays, semesters (spring/fall), academic years, and universities. I find that moratoriums decrease the average incidence of alcohol offenses on a given academic calendar day by approximately 27%. This result is most prominent on the weekends when partying is most frequent (29% reduction) while nonexistent on the weekdays. Moreover, I find weaker evidence of decreases in sexual assaults on the weekends with a 26% reduction from the mean, although only significant at the 10% level. Notably, the moratoriums show no lasting effects. Including an indicator for the week before and week after a moratorium shows a significant dip during the moratorium, but immediate returns to previous levels after the moratorium is lifted. These results demonstrate that moratoriums are only effective when in place; despite the motivation that moratoriums allow time for members to reevaluate and change their systematic behavior, the effects do not persist. 

One potential caveat to these results is that the decreases of alcohol and sexual assault observed in the Daily Crime Logs are being displaced to potentially riskier areas. For instance, while campus-wide alcohol is decreasing, it may be that fraternity members and other students are substituting their behaviors on-campus to off-campus areas that are less regulated. If this is true, a moratorium may cause more harm than the perceived benefits shown in this paper. Unfortunately, there does not exist a sufficient data source to explore such mechanism directly; the NIBRS data only reliably^[In this case, I consider a data source to be reliable if reporting of crime is consistent in the sample period. NIBRS features only 14 schools that continually report data without large missing periods.] covers 36% of the sample university's next-closest police department and includes alcohol arrests rather than all incidences. As an indirect test, I analyze the CSS data in Appendix BLANK. This data, while similar to the Daily Crime Logs, features all violations of liquor, drug, and sexual assaults that occur in a calendar-year, aggregated to the yearly level. Since the data is aggregated yearly, and moratoriums can last for as few as 6 days, the analysis should be taken only as speculative, not causal. Despite these shortcomings, there is evidence that moratoriums significantly move drinking from fraternity houses to residence halls. Residence halls show a 25% *increase* in alcohol offenses relative to the mean when a proportion of a calendar-year is in a moratorium. This is accompanied by a large 85% *decrease* from the mean in residence hall sexual assaults. These results point to the possibility that moratoriums cause a substitution effect of partying behavior; students substitute drinking from fraternity houses to residence halls. Since residence halls are far more regulated than fraternity houses, problematic alcoholic behavior is stopped (e.g., the increases in alcohol violations) before it can become dangerous to others (e.g., the decreases in sexual assaults). 

Taken together, these results support the notion that moratoriums are effective policy procedures in reducing campus-wide alcohol offenses provided that the moratoriums contain at least a month's worth of academic calendar days. However, moratoriums do not substantiate permanent behavior changes. The results show that fraternity and campus behavior returns to prior levels immediately after a moratorium has been lifted. Thus, further research is needed to understand how to permanently change risky behavior rather than temporarily mitigate it. Several universities have completely removed fraternities from their campuses or have implemented restrictions on recruitment strategies in their students' first semester. In particular, Duke University has implemented a deferred recruitment system in which students may not join fraternities until their sophomore year. As of this writing, there is only one study to my knowledge that evaluates such policy and this paper focused on academic benefits rather than crime (CITE EVEN).

It is important to understand that this paper does not provide evidence advocating for the removal of fraternity life. Within this study, none of the universities removed fraternity life, only restricted it. Hence, this paper does not provide support for national movements such as "Abolish Greek Life".  However, this study *does* quantify the effects that fraternities have on university-wide partying behavior. More specifically, this paper is the first to show the causal effect of temporarily restricting alcohol from fraternity social events which significantly reduce alcohol offenses and sexual assaults campus-wide. 




