---
title: "Introduction"
output: pdf_document
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Introduction \label{section:introduction}

This paper is the first to estimate the causal effects of temporary campus-wide bans on fraternity social events with alcohol (henceforth, moratoriums) on university-police reports of alcohol, drug, and sexual assault offenses. Since 2010, over 50 moratoriums have been enacted across university campuses, thus becoming a common policy tool among school administrators. However, no prior research has investigated this topic; moratorium dates are difficult to find/confirm and there does not exist a centralized data source for university-specific crime with fine enough detail for casual inference. Despite this lack of research, administrators continue to use moratoriums as a disciplinary action on their fraternities.

Nonetheless, how these moratoriums effect student behavior, and thus on-campus crime, is theoretically unclear. On one hand, prohibiting alcohol from fraternity social events may reduce reports of crime. Fraternities are a common source of alcohol for underage drinking, as fraternities are typically a mix of lower and upperclassmen [@armstrong_sexual_2006]. The inclusion of legal-age drinkers and large social events allows for easy access to alcohol for underage students. Given that the literature has documented that alcohol causes higher prevalence of crimes such as assaults and alcohol offenses [@carpenter_minimum_2015], road accidents and arrests [@francesconi_liquid_2019], and rape [@zimmerman_alcohol_2007;@lindo_college_2018], prohibiting such events could reduce the amount of on-campus crime. On the other hand, moratoriums may have the opposite effect. Without alcohol-fueled fraternity parties, students may substitute away from consuming alcohol at fraternity houses to potentially riskier places where behavior is less regulated. As a result, the net effect of moratoriums is ambiguous. 

In this paper, I estimate the causal effect of 45 fraternity moratoriums across 38 universities over a six-year period (2014-2019) on reports of alcohol, drug, and sexual assaults offenses. I use a difference-in-differences identification strategy, leveraging the unanticipated nature of moratoriums. Intuitively, I compare academic-calendar days with a moratorium to academic-calendar days without a moratorium while accounting for expected differences across days of the week and across different times of the year. I construct a novel data set, merging together two particularly unique data sources: university-specific Daily Crime Logs, which contain the universe of all reported incidences of crime to the university police at the incident-level, and moratorium start and end dates obtained through school newspapers and public records requests. Using this data, I find that moratoriums significantly decrease alcohol offenses campus-wide on academic-calendar days by 27%. This effect is driven by weekends (Fridays-Sundays) when college partying is more frequent and is robust across various specifications, estimation methods, and sensitively tests. Furthermore, I find weaker evidence that sexual assaults decrease by 26% on the weekends. Both of these decreases are concentrated only when a moratorium is in place suggesting that moratoriums contain no long-run effects.

Most closely related to this paper is @lindo_college_2018  who use increases in college partying from football games to estimate a 28% daily increase in rape. This paper differs from this work on several levels. First, I examine the effects of a *reduction* in partying coming from one prominent source (fraternities), rather than the effects of an *increase* in partying. As shown in @cunningham_decriminalizing_2018, who study the effects of decriminalizing and criminalizing prostitution on rape, the effects are not necessarily the same in each direction. Hence, there is little reason to believe an increase and decrease in partying results in the same magnitude of increase/decrease. Furthermore, this study focuses on sanctions against university fraternities which more exclusively affects university students—college football attracts a large demographic whom are not students of the university. Thus, the increases found may not be as attributed to the university students themselves. Lastly, the novel data constructed in this paper contains all reports of alcohol offenses by the university police rather than only alcohol-related arrests. Given that students are unlikely to be arrested for underage drinking, this is a major advancement in determining how university life is affected by decreases in partying.

Additionally, this paper advances a small, but growing literature relating to fraternities. Two papers show the effects of fraternity membership on GPA using variation from deferred recruitment—a policy which prohibits freshman students from joining a fraternity until their second semester [@de_donato_effects_2017; @even_greek_2020]. Each of the papers show that membership decreases GPA, while @even_greek_2020 additionally find that membership causes students to select into easier courses and complete less course credits. More related to this paper is a working paper by @raghav_greek_2021 who find that a larger percentage of students in fraternities is associated with an increase in the number of drug law arrests. However, this work does not consider the difference between IFC fraternities (see Section \ref{section:background}) and professional fraternities due to their data limitations. Each of these types of fraternities have vastly different contributions campus party culture. Furthermore, their data is aggregated to a calendar-year level, and thus unable to delineate between important differences in membership numbers between academic years and semesters.

Lastly, this paper more broadly contributes to a literature on the effects of restricting alcohol to college-aged students. Several studies have utilized the discontinuity in the minimum legal drinking age (MLDA) to show that alcohol causes large increases in mortality [@carpenter_effect_2009], emergency room visits [@francesconi_liquid_2019], and crime [@carpenter_minimum_2015]. In addition, two studies use the MLDA to show the academic effects of alcohol; @carrell_does_2011 find that drinking hinders the performance of the highest performing students, while @ha_legal_2019 find that alcohol most significantly affects the performance of students who did not previously have access to underage drinking. Finally, @liang_go_2008 finds that placing harsher penalties on drunk driving (zero-tolerance laws) resulted in a 26% reduction in the probability of drinking and driving for those who reported drinking away from home, although the results are based on survey-data.  

# Fraternities in the US \label{section:background}

## Background

Fraternities maintain a ubiquitous presence in the United States with chapters prevalent in over 800 universities [@hechinger_true_2017]. Fraternities consist of students from families of higher-than-average educational attainment and income; they are predominantly white, and prior research has linked fraternity membership to increases in graduation rates [@routon_impact_2014], future income [@mara_social_2018], and decreases in GPA [@de_donato_effects_2017;@even_greek_2020]. Moreover, members spend approximately two more hours partying than nonmembers [@routon_impact_2014], and binge drink on approximately 1.7 additional days [@desimone_fraternity_2007]. While not causal, there is survey evidence that fraternity members are more accepting of sexual violence than nonmembers [@seabrook_examining_2019] and that sorority women, whom frequently interact with fraternity men, are four times more likely to be a victim of sexual assault than nonmembers [@minow_sorority_2009].

This paper focuses on the Interfraternity Council (IFC) fraternities otherwise known as ‘social’ fraternities. These fraternities are the most common at universities, but differ from the professional, academic, or service fraternities. IFC fraternities participate in philanthropy and professional development, but according to their creed, they “exist to promote the shared interests and values of our member fraternities: leadership, service, brotherhood and scholarship” [@hechinger_true_2017]. Importantly, it is the IFC fraternities that are always restricted by a moratorium in the sample.

Each IFC fraternity chapter^[A chapter, or otherwise known as a "house" is a unique fraternity. A fraternity can have many chapters across the US, with usually one per-school.] has three sources of oversight: the chapter national headquarters, the parent university, and the parent university’s own IFC council—a group of student representatives from each recognized IFC fraternity chapter whom regularly meet with university staff to discuss rules/boundaries. Failure to abide by university policies can result in a fraternity being unrecognized by the university which is costly—a fraternity relies on the university for new students to recruit.  

## Moratoriums

A moratorium is defined as a temporary ban on alcohol at social events for IFC fraternities.^[This is the minimum requirement for a moratorium in this paper. Some universities ban alcohol at social events for all IFC fraternities in addition to the rest of their Fraternity and Sorority Life. However, IFC fraternities are generally the main focus.] The timing, and length of a moratorium varies substantially. Figure \ref{closure_distribution} shows the start and end dates of each moratorium over time. Moratoriums can last as few as 6 calendar-days, or as long as 848 calendar-days. Moratoriums are the generally implemented because of a triggering event (see Figure \ref{reasons_table}). This event can be a prominent sexual assault allegation, a fraternity-related death (usually due to alcohol poisoning), or an extreme behavior violation.^[A behavior violation is a catchall term for hazing, rule violations, offensive behavior, and other disorderly conduct that results in a moratorium.] Figure \ref{trigger_plot} shows the distribution of the triggering events: 18 are triggered by behavior violations, 10 by sexual assaults, 10 by a fraternity-related death, and 7 are unspecified. As alluded to in the introduction, moratoriums are a nation-wide policy. Figure \ref{map_of_schools} shows the locations of the 38 universities in the sample. While most universities are located in the mid-west and south, there are several universities from both the west and east coast.

Moratoriums can be implemented by two sources of jurisdictions: the university or the Interfraternity Council. When a moratorium is implemented by the university, the university sets the guidelines that fraternities must abide by during the moratorium. The minimum guideline in the sample is that all social events with alcohol are prohibited, although other guidelines can be enforced (e.g., additional sexual harassment training). On the other hand, an IFC-implemented moratorium is student-enforced. This means that the overarching IFC council is responsible for oversight. Figure \ref{trigger_plot} shows that IFC-implemented moratoriums are less frequent (17) than university-implemented moratoriums (28) and Section \ref{section:heterogeneity} examines the heterogeneous effects involving this difference in oversight.


