---
title: "Fraternities"
output: 
  pdf_document:
    number_sections: true
header-includes:
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{amsmath}
- \usepackage[english]{babel}
- \usepackage{bm}
- \usepackage{float}
- \usepackage[fontsize=12pt]{scrextend}
- \floatplacement{figure}{H}
- \usepackage{natbib}
- \usepackage{pdflscape}
linkcolor: blue
bibliography: "references.bib"
link-citations: yes
abstract: Fraternities maintain a presence at over 800 universities in the United States. While the literature has documented positive effects of membership such as increased graduation rates and future income, studies have shown fraternities to be a reliable source of alcohol for underage students in addition to their members exhibiting more partying behavior than their non-member peers. In this paper, I exploit the variation in timing from 45 temporary university-wide halts on all fraternity activity with alcohol (moratoriums) across 38 universities over a six-year period (2014-2019). I construct a novel data set, merging unique incidence-level crime logs from university police departments to provide the first causal estimates of the effect of moratoriums on campus-wide reports of alcohol, drug, and sexual assault offenses. In particular, I find strong and robust evidence that fraternity moratoriums lower alcohol violations campus-wide by 27%. This effect is driven by decreases in weekend reports, consistent with the timing of most fraternity parties.  Additionally, I find weaker evidence that moratoriums decrease reports of sexual assault on the weekends. However, these effects are transcient, with moratoriums showing no evidence of long-run changes in student behavior.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(kableExtra)
library(bookdown)
library(modelsummary)
library(fixest)
```



\newpage
\pagenumbering{arabic}
```{r, child = "introduction.Rmd"}

```

```{r, child="data.Rmd"}

```

```{r, child="empirical_strategy.Rmd"}

```

```{r, child = "results.Rmd"}

```

```{r, child = "heterogeneity.Rmd"}

```

```{r, child = "conclusion.Rmd"}

```

# References

<div id="refs"></div>


\newpage
```{r, child = "figures.Rmd"}

```
\newpage
```{r, child = "tables.Rmd"}

```



<!-- \newpage -->
<!-- ```{=tex} -->
<!-- \appendix -->
<!-- \renewcommand{\thefigure}{A\arabic{figure}} \setcounter{figure}{0} -->
<!-- \renewcommand{\thetable}{A\arabic{table}} \setcounter{table}{0} -->
<!-- \renewcommand{\theequation}{A\arabic{table}} \setcounter{equation}{0} -->
<!-- \setcounter{page}{1} -->
<!-- ``` -->

<!-- ```{r, child = "appendix.Rmd"} -->

<!-- ``` -->

<!-- \newpage -->
<!-- ```{=tex} -->
<!-- \appendix -->
<!-- \renewcommand{\thefigure}{B\arabic{figure}} \setcounter{figure}{0} -->
<!-- \renewcommand{\thetable}{B\arabic{table}} \setcounter{table}{0} -->
<!-- \renewcommand{\theequation}{B\arabic{table}} \setcounter{equation}{0} -->
<!-- \setcounter{page}{1} -->
<!-- ``` -->

<!-- ```{r, child = "appendix_twfe.Rmd"} -->

<!-- ``` -->

<!-- \newpage -->
<!-- ```{=tex} -->
<!-- \appendix -->
<!-- \renewcommand{\thefigure}{B\arabic{figure}} \setcounter{figure}{0} -->
<!-- \renewcommand{\thetable}{B\arabic{table}} \setcounter{table}{0} -->
<!-- \renewcommand{\theequation}{B\arabic{table}} \setcounter{equation}{0} -->
<!-- \setcounter{page}{1} -->
<!-- ``` -->

<!-- ```{r, child = "appendix_clery.Rmd"} -->

<!-- ``` -->

