---
title: "Results"
output: pdf_document
---

# Results

In this section, the causal effects of a fraternity moratorium on alcohol, drug, and sexual assault offenses are estimated using OLS. To reduce potential noise in the estimates, the sample is restricted to only the academic calendar days unique to each university.^[See the Data section for more details.] Furthermore, I perform numerous robustness and sensitivity checks—each resulting in estimates that are consistent with the main findings discussed above.

## Main Results

Table \ref{main_results} reports that fraternity moratoriums lead to substantially lower alcohol offenses across university campuses while showing weaker evidence of decreases in both drug offenses and sexual assaults. Column (1) exhibits the naive regression with no controls—it compares only the difference in means between moratorium and non-moratorium days. While none of the panels in this column contain significant results, this specification acts as a demonstration of the importance of accounting for the factors described in Section BLANK. On the other hand, Column (2) shows the baseline specification from Equation \ref{main_model}. This baseline specification includes day of the week, holiday, semester, and academic year fixed effects in order to address the potential concerns described earlier. Moreover, columns (3) and (4) show results from progressively adding more flexible fixed effects. In Panel A, alcohol offenses decrease during moratorium days relative to non-moratorium days in the academic calendar. In particular, an average moratorium day exhibits between 26 and 29 percent less alcohol offenses in comparison to an average academic calendar day. These estimates are statistically significant across each specification, maintaining that moratoriums decrease campus-wide alcohol offenses. Although alcohol offenses are robust, both drug offenses and sexual assaults fail to achieve statistical significance across each specification and the magnitude of each effect varies considerably; drug offenses exhibit a 3-17 percent reduction from the mean and sexual assaults show an 18-26 percent reduction. One reason for this discrepancy in magnitude may be that the inclusion of the university by academic year fixed effect (column (3)) changes the comparison groups; intuitively, a university by academic year fixed effect allows only for comparisons of moratorium days to non-moratoriums within a particular university's academic calendar. Similarly, interacting university, academic year, and semester fixed effects (column (4)) only allows for comparisons of moratorium days to non-moratorium days within a particular university's semester in a particular academic year. In light of these differences, all further analysis uses the controls from column (3) as the preferred specification due to their conservative estimates. Under this specification, alcohol offenses are the only offense that are significantly reduced in moratorium days.

The effects of moratoriums are most evident during the weekends (Friday-Sunday), consistent with the literature that most college partying occurs on weekends rather than weekdays CITE Lindo. Table \ref{weekend_table} shows column (3) from Table \ref{main_table} separated by weekends, and weekdays; the column "All Days" corresponds to the estimates from column (3) from Table \ref{main_table}. During the weekends, alcohol offenses decrease by 29% relative to an average academic calendar weekend as shown in Panel A. On the other hand, weekdays show no statistically significant decreases. This is due to the nature of alcohol drinking at universities—most consumption occurs on the weekends rather than weekdays. Likewise to alcohol, sexual assaults show larger decreases on the weekend in comparison to weekdays in Panel C. A weekend during a moratorium can expect 18% fewer sexual assaults relative to an average academic calendar weekend. These results align with previous literature that indicate that alcohol and sexual assaults are complementary offenses (CITE).

While both alcohol offenses and sexual assaults decrease significantly on the weekends, these effects are concentrated only within a moratorium. Figure \ref{} shows estimates from specification (3) in Table \ref{main_table} with the inclusion of an indicator variable for the week after and week before a moratorium. When considering the entire sample, each offense exhibits decreases that persist only during the moratorium period. This pattern persists when restricting the sample to weekends where the effects of the moratorium are most prominent. While drug offenses show significant increases in the week following a moratorium, these results are likely the result of multiple hypothesis testing as drug offenses showed the least amount of robustness in Table \ref{main_table} and there is little reason to suspect that only drug offenses increase after moratoriums without similar increases for alcohol offenses and sexual assaults. If this significant increase in drug offenses was the result of pent-up demand for hard partying, large increases in alcohol offenses and sexual assaults should also be expected. However, no accompanying increases are found.

## Robustness

Given the low number of universities in the sample (38), the results shown above lack precision—while both alcohol and sexual assault offenses show statistically significant decreases on the weekend, the standard errors are not small: weekend offenses for alcohol decrease by 17-41 percent from the mean, while sexual assaults decrease by 10-42 percent with 95% confidence. To address this issue and increase power, I include 14 additional universities in the sample that never underwent a moratorium in the period of analysis. This amounts to 52 total universities (and clusters) for a total of approximately 75 thousand academic calendar days. Each of the additional universities was chosen from the Colleges with the Best Greek Life list on niche.com.^[I use niche.com since it is the top search result on Google when searching for the ``best fraternity colleges''. The Princeton Review, notable for its annual list of party schools, does not a list regarding fraternity life.] Universities were selected if they were regarded as a top 50 Greek Life school.^[Notably, it is known that at least one university (Chico State) had a moratorium outside of the sample period (2013). This, however, only further validates the selection of the never-treated universities.] However, 17 of these universities were already included in the sample due to experiencing a fraternity moratorium. As such, 14 of remaining 33 universities were able to provide Daily Crime Logs for the 2014-2019 period. Table \ref{} shows the effects of moratoriums when including these never-treated universities. Overall, the results remain similar, with weekend decreases of alcohol between an 11-34 percent reduction from the mean and sexual assault decreases between 10-39 percent. While the precision is only enhanced by 1-3 percentage points, the stability of the estimates and significance instill further confidence in the results of the model.

Figures \ref{loo_alc_ols}, \ref{loos_drug_ols}, and \ref{loo_sex_ols} show leave-one-out coefficient estimates for each corresponding offense. This analysis ensures that the results described above are not driven by a single university. In particular, 38 unique regressions are estimated for every offense, omitting one university within each iteration. This exercise is repeated for the entire sample in addition to weekends and weekdays only. In each figure, the results remain consistent with the estimates shown in Table \ref{weekend_table}; alcohol offenses significantly decline overall (with particularly strong effects on the weekends) while there is weaker evidence of declines in sexual assaults on the weekends. This analysis verifies that the effect of the moratorium is not driven by only one particularly stringent university.

Furthermore, given the non-negative count nature of the offense data and the sensitivity of OLS estimation to outliers,  Tables \ref{main_table_p} and \ref{weekend_table_p} show Tables \ref{main_table} and \ref{weekend_table} using poisson estimation in lieu of OLS.^[Despite these advantages of poisson estimation, OLS is the preferred method since the results are more conservative.] The results are consistent, with Table \ref{weekend_table_p} showing the preferred specification leading to 27 and 16 percent average reductions for alcohol offenses and sexual assaults respectively. 

Lastly, several recent journal articles have found that using OLS in a two-way-fixed-effects (TWFE) difference-in-differences design can cause problematic issues with the coefficient estimates (CITE). In particular, the parameter of interest (e.g., the coefficient on the treatment variable) is a weighted sum of average treatment effects where some of the weights may be negative. This negative weighting issue can potentially lead to coefficient estimates switching signs. For instance, a negative-signed treatment effect implicating reductions may actually be positively-signed once correcting for the problematic negative weights. While this paper's research design is not a typical TWFE design since the preferred specification uses interacted fixed effects and university's switch between moratorium days and non-moratorium days (and in some cases multiple times), there maintains a possibility that the negative weights issue could extend to the preferred model used in this paper. Appendix BLANK analyzes a typical TWFE design in this setting using university and day by month by year fixed effects. I show that this design does not contain negative weights and that the coefficient estimates are consistent with the results described earlier. 



