---
title: "Football Games Continued"
output: pdf_document
editor_options: 
  chunk_output_type: console
link-citations: yes
linkcolor: blue
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(fixest)
library(modelsummary)
library(grid)
library(gridExtra)
library(patchwork)
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## The Raw Data Graph

Figure \ref{diff_average_offenses} shows the average difference in moratorium days vs. non moratorium days for each school. Toshio suggested maybe adding in a vertical line showing the effect that I have in each of these graphs, I'm not sure I necessarily want to do this, but it could be interesting. Thoughts on that?


<!-- ```{r} -->
<!-- source(paste0(here::here("tables/matching_word_table.R"))) -->
<!-- ``` -->


<!-- ```{r top_categories} -->
<!-- kable(top_categories, booktabs = T, caption = "\\label{top_categories}The Top 30 Most Frequently Reported Incidents") %>% -->
<!--   kable_styling(latex_options = c("scale_down", "HOLD_position")) %>% -->
<!--   footnote(list("Numbers in parenthesis denote the frequency of offense in the data. These offenses represent the  30 most frequent crimes in each category after the pattern-matching algorithm is applied."), -->
<!--                threeparttable = T) %>% -->
<!--   landscape() -->
<!-- ``` -->


```{r}

source(here::here(paste0("figures/event_study_final_dec13.R")))



moratorium_ids <- daily_crime %>% 
  group_by(university) %>% 
  mutate(treatment_na = ifelse(treatment == 0, NA, treatment)) %>% 
  mutate(treatment_na = ifelse(treatment_na > 0 & (!is.na(closure_2)) & date >= closure_2, 2, treatment_na)) %>% 
  mutate(treatment_na = ifelse(treatment_na > 1 & (!is.na(closure_3)) & date >= closure_3, 3, treatment_na)) %>% 
  mutate(treatment_na = ifelse(is.na(treatment_na), 0, treatment_na)) %>% 
  ungroup() %>% 
  filter(treatment_na >0) %>% 
  group_by(treatment_na, university) %>% 
  mutate(moratorium_id = cur_group_id()) %>% 
  ungroup() %>% 
  select(moratorium_id, university, treatment,date)

daily_crime <- daily_crime %>% 
  left_join(moratorium_ids) %>% 
  mutate(moratorium_id = ifelse(is.na(moratorium_id), 0, moratorium_id))


moratorium_lengths <- daily_crime %>% 
  group_by(moratorium_id) %>% 
  mutate(length_moratorium = sum(treatment)) %>% 
  select(moratorium_id, length_moratorium, university) %>% 
  ungroup() %>% 
  filter(moratorium_id != 0) %>% 
  distinct(length_moratorium, university, moratorium_id) 

quartiles <- quantile(moratorium_lengths$length_moratorium, c(0.33, .66, 1))

daily_crime <- daily_crime %>% 
  left_join(moratorium_lengths) %>% 
  mutate(length_moratorium = ifelse(is.na(length_moratorium), 0, length_moratorium)) %>% 
  mutate(below_q33 = if_else(between(length_moratorium, 0.1,quartiles[[1]]), 1,0)) %>% 
  mutate(between_q33_q66 = ifelse(between(length_moratorium, quartiles[[1]], quartiles[[2]]), 1, 0)) %>% 
  mutate(above_q66 = ifelse(between(length_moratorium, quartiles[[2]], quartiles[[3]]), 1, 0)) 





lower_quantiles <- daily_crime %>% 
  filter(below_q33 == 1) %>% 
  distinct(university) %>% 
  pull()

middle_quantiles <- daily_crime %>% 
  filter(between_q33_q66 == 1) %>% 
  distinct(university) %>% 
  pull()

last_quantiles <- daily_crime %>% 
  filter(above_q66 == 1) %>% 
  distinct(university) %>% 
  pull()

es_alc_14_lower <- ifc::reghdfe(es_14 %>% 
                                  filter(university %in% lower_quantiles), "alcohol_offense_per25", explanatory_vars_14, fixed_effects, cluster = "university")
es_alc_14_middle <- ifc::reghdfe(es_14 %>% 
                                   filter(university %in% middle_quantiles), "alcohol_offense_per25", explanatory_vars_14, fixed_effects, cluster = "university")
es_alc_14_last <- ifc::reghdfe(es_14 %>% 
                                 filter(university %in% last_quantiles), "alcohol_offense_per25", explanatory_vars_14, fixed_effects, cluster = "university")


ifc::event_study_graph(es_alc_14_lower, 5)
ifc::event_study_graph(es_alc_14_middle, 5)
ifc::event_study_graph(es_alc_14_last, 5)



es_sex_14_lower <- ifc::reghdfe(es_14 %>% 
                                  filter(university %in% lower_quantiles), "sexual_assault_per25", explanatory_vars_14, fixed_effects, cluster = "university")
es_sex_14_middle <- ifc::reghdfe(es_14 %>% 
                                   filter(university %in% middle_quantiles), "sexual_assault_per25", explanatory_vars_14, fixed_effects, cluster = "university")
es_sex_14_last <- ifc::reghdfe(es_14 %>% 
                                 filter(university %in% last_quantiles), "sexual_assault_per25", explanatory_vars_14, fixed_effects, cluster = "university")

ifc::event_study_graph(es_sex_14_lower, 5)
ifc::event_study_graph(es_sex_14_middle, 5)
ifc::event_study_graph(es_sex_14_last, 5)


alc_es <- list(es_alc_14, es_alc_14_lower, es_alc_14_middle, es_alc_14_last)

sex_es <- list(es_sex_14 , es_sex_14_lower, es_sex_14_middle, es_sex_14_last)


alc_lag_f <- map_df(alc_es, ~car::linearHypothesis(.,
                              c("beta_lag_1 = 0",
                                "beta_lag_2 =0",
                                "beta_lag_3 =0",
                                "beta_lag_4 =0")) %>% 
      broom::tidy()) %>% 
  filter(if_all(everything(), ~!is.na(.)))

sex_lag_f <- map_df(sex_es, ~car::linearHypothesis(.,
                                      c("beta_lag_1 = 0",
                                        "beta_lag_2 =0",
                                        "beta_lag_3 =0",
                                        "beta_lag_4 =0")) %>% 
         broom::tidy()) %>% 
  filter(if_all(everything(), ~!is.na(.)))

long_run_effects <- ifc::main_table(list(es_alc_14,es_sex_14),
                list(es_alc_14_lower, es_sex_14_lower),
                list(es_alc_14_middle, es_sex_14_middle), 
                last_panel =list(es_alc_14_last, es_sex_14_last)) %>% 
  slice(1:12) %>% 
  add_row(term = "F-test P-value of Lags", 
          `Model 1` = sprintf("%.3f",alc_lag_f$p.value[[1]]),
          `Model 2` = sprintf("%.3f",sex_lag_f$p.value[[1]]),
          .before = 4) %>% 
  add_row(term = "F-test P-value of Lags", 
          `Model 1` = sprintf("%.3f",alc_lag_f$p.value[[2]]),
          `Model 2` = sprintf("%.3f",sex_lag_f$p.value[[2]]),
          .before = 8) %>% 
  add_row(term = "F-test P-value of Lags", 
          `Model 1` = sprintf("%.3f",alc_lag_f$p.value[[3]]),
          `Model 2` = sprintf("%.3f",sex_lag_f$p.value[[3]]),
          .before = 12) %>% 
  add_row(term = "F-test P-value of Lags", 
          `Model 1` = sprintf("%.3f",alc_lag_f$p.value[[4]]),
          `Model 2` = sprintf("%.3f",sex_lag_f$p.value[[4]]),
          .before = 16) %>% 
  kbl(col.names = c(" ", "Alcohol Offenses", "Sexual Assaults"),
      booktabs = T,
      caption = "\\label{long_run_effects}Absence of Dynamic Effects of Moratoriums Split by Moratorium Length") %>% 
  kable_styling() %>% 
  group_rows("Panel A: Full Sample", 1,4, bold = F, italic = T) %>% 
  group_rows("Panel B: Quantiles by Moratorium Length", 5,16, bold = F, italic = T) %>% 
  pack_rows("Estimates from Figures 4 and 5", 1, 4, bold = F, italic = T) %>% 
  pack_rows("Moratorium Length: 1st Quantile", 5, 8, bold = F, italic = T, latex_gap_space = "0.5cm") %>% 
  pack_rows("Moratorium Length: 2nd Quantile", 9, 12, bold = F, italic = T, latex_gap_space = "0.5cm") %>% 
  pack_rows("Moratorium Length: 3rd Quantile", 13, 16, bold = F, italic = T, latex_gap_space = "0.5cm") %>% 
  add_header_above(c(" ", "Dependent Variable" = 2)) %>% 
  column_spec(1, width = "8cm") %>% 
  row_spec(0, hline_after = T) %>% 
  row_spec(4, hline_after = T) %>% 
  row_spec(4, hline_after = T) %>% 
  footnote(list("Point estimates of In Motratorium reflect the time 0 for `multiple event' event studies similar to Figures 4 and 5 with four leads and four lags of 14-day bins. Each offense is defined as per-25,000 enrolled students. Standard errors are clustered at the university level. All periods are normalized by the 14-day period before the moratorium. Panel A represents the same coefficient estimates as Figures 4 and 5, while Panels B,C, and D represent subsets of the sample split by three quantiles. The three quantiles represent the 33rd, 66th, and 100th percentile of a moratorium length which correspond to [0-32], [33-59], and [60-541] academic calendar days of a moratorium respectively. Hence, if a university has a moratorium that lasts 30 academic calendar days, then it is included in Panel B. P-values are reported from joint F-test of the four lags. Fixed effects include day of the week, holiday, semester number, football game-day, and university-by-academic-year.",
                "* p < 0.1, ** p < 0.05, *** p < 0.01"), threeparttable = T)
  


```

```{r}
long_run_effects
```

```{r}
library(tidyverse)
library(modelsummary)
library(fixest)
library(kableExtra)
library(fwildclusterboot)
if (!exists("daily_crime")){
  daily_crime <- read_csv("created_data/xmaster_data/daily_panel.csv")
}
if (!exists("daily_crime_weekends")){
  daily_crime_weekends <- read_csv("created_data/xmaster_data/daily_panel_weekends.csv")
}

if (!exists("daily_crime_weekdays")){
  daily_crime_weekdays <- read_csv("created_data/xmaster_data/daily_panel_weekdays.csv") 
}

## for bootstrapping
# set seed via dqset.seed for boot_algo = "R" & Rademacher, Webb & Normal weights
dqrng::dqset.seed(2352342)
# set 'familiar' seed for all other algorithms and weight types 
set.seed(23325)

explanatory_vars <- c("treatment")


# fixed effects for daily_level -------------------------------------------
fixed_effects_1 <- c("day_of_week", "academic_year", "spring_semester", "university", "holiday", "game_occurred")
fixed_effects_2 <- c("day_of_week", "university_by_academic_year", "holiday", "spring_semester", "game_occurred")
fixed_effects_3 <- c("day_of_week", "university_by_academic_year_by_semester", "holiday", "game_occurred")


daily_fixed_effects = list(fixed_effects_1, fixed_effects_2, fixed_effects_3)

alc <- map(daily_fixed_effects, ~ifc::reghdfe(daily_crime, c("alcohol_offense_per25"),explanatory_vars, ., "university")
)

alc_boot <- map(alc, ~boottest(., param = "treatment", clustid = "university", B = 1000))


sex <- map(daily_fixed_effects, ~ifc::reghdfe(daily_crime, c("sexual_assault_per25"),explanatory_vars, ., "university")
)

sex_boot <- map(sex, ~boottest(., param = "treatment", clustid = "university", B = 1000))



main_table <- ifc::main_table(alc, last_panel = sex) %>% 
  add_row(term = "Mean of Dependent Variable", 
          `Model 1` = sprintf("%.3f",mean(daily_crime$alcohol_offense_per25, na.rm = T)),
          `Model 2` = sprintf("%.3f",mean(daily_crime$alcohol_offense_per25, na.rm = T)),
          `Model 3` = sprintf("%.3f",mean(daily_crime$alcohol_offense_per25, na.rm = T)),
          .before = 4) %>% 
  add_row(term = "Wild Bootstrap P-Value", 
          `Model 1` = sprintf("%.3f",alc_boot[[1]]$p_val),
          `Model 2` = sprintf("%.3f",alc_boot[[2]]$p_val),
          `Model 3` = sprintf("%.3f",alc_boot[[3]]$p_val),
          .before = 5) %>% 
  add_row(term = "Mean of Dependent Variable", 
          `Model 1` = sprintf("%.3f",mean(daily_crime$sexual_assault_per25, na.rm = T)),
          `Model 2` = sprintf("%.3f",mean(daily_crime$sexual_assault_per25, na.rm = T)),
          `Model 3` = sprintf("%.3f",mean(daily_crime$sexual_assault_per25, na.rm = T)),
          .before = 9) %>% 
  add_row(term = "Wild Bootstrap P-Value", 
          `Model 1` = sprintf("%.3f",sex_boot[[1]]$p_val),
          `Model 2` = sprintf("%.3f",sex_boot[[2]]$p_val),
          `Model 3` = sprintf("%.3f",sex_boot[[3]]$p_val),
          .before = 10) %>% 
  kbl(booktabs = T, 
      col.names = c(" ", "(1)", "(2)", "(3)"),
      digits = 3,
      caption = "\\label{main_table}Effect of Moratoriums on Alcohol Offenses and Sexual Assaults (OLS).") %>% 
  kable_styling(latex_options = "HOLD_position") %>% 
  pack_rows("Panel A: Alcohol Offenses", 1, 5, bold = F, italic = T) %>%
  pack_rows("Panel B: Sexual Assaults", 6, 10, bold = F, italic = T, latex_gap_space = "0.5cm") %>% 
  row_spec(c(10),hline_after=TRUE) %>% 
  # pack_rows("",11, 18, bold = F, italic = T, hline_before = T ) %>% 
  # row_spec(5, italic = T) %>% 
  column_spec(1, width = "8cm") %>% 
  footnote(list("Estimates are obtained using OLS. Standard errors shown in paranthesis are clustered by university (37 clusters) and each offense is defined as per-25000 enrolled students. P-values from 1000 wild cluster bootstrap iterations are shown for the In Moratorium coefficient as suggested by @cameron_bootstrap-based_2008 in cases with a small number of clusters (typically lower than 30). This analysis is near, but not below this threshold. Holiday controls include controls for Veterans Day, Thanksgiving, Labor Day, Halloween, and MLK Day. Christmas/New Years/July 4th are not included since these holiday's are not on any university's academic calendar. Game Day controls consist of university football games within each university. A moratorium is a temporary halt on fraternity-related activities with alcohol. Specification (2) is the preferred specification due to the flexibility of the fixed effects and the conservativeness of the estimates.",
                "* p < 0.1, ** p < 0.05, *** p < 0.01"), threeparttable = T)
```

```{r}
main_table
```

