---
title: "Synthetic Control with Time Varying Coefficients"
subtitle: "A State Space Approach with Bayesian Shrinkage"
author: 
  - Danny Klinenberg^[Ph.D. student at University of California, Santa Barbara; dklinenberg@ucsb.edu. I'd like to thank Dick Startz, Jaime Ramirez-Cuellar, Ryan Sherrard,  and the UCSB Econometrics reading group for comments. All errors are my own.]
date: "Last Updated: `r Sys.Date()`"
output: 
  pdf_document:
    number_sections: true
    # latex_engine: xelatex # If i hashtag it out my code works? I'm not sure
indent: true
header-includes:
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{amsmath}
- \usepackage[english]{babel}
- \usepackage{bm}
- \usepackage{float}
- \usepackage[fontsize=12pt]{scrextend}
- \usepackage{graphicx}
- \usepackage{indentfirst}
- \usepackage[utf8]{inputenc}
- \usepackage{pdfpages}
- \usepackage[round,authoryear]{natbib}
- \usepackage{setspace}\doublespacing
- \usepackage{subfigure}
- \theoremstyle{definition}
- \newtheorem{definition}{Definition}[section]
- \newtheorem{assumption}{Assumption}
- \newtheorem{theorem}{Theorem}[section]
- \newtheorem{corollary}{Corollary}[theorem]
- \newtheorem{lemma}[theorem]{Lemma}
- \newtheorem*{remark}{Remark}
- \newcommand{\magenta}[1]{\textcolor{magenta}{#1}}
- \newcommand{\indep}{\perp \!\!\! \perp}
- \floatplacement{figure}{H}
- \bibliographystyle{plainnat}
bibliography: "Constant Weights SC.bib"
link-citations: yes
linkcolor: blue
abstract: Synthetic control methods are a popular tool for measuring the effects of policy interventions on a single treated unit. In practice, researchers create a counterfactual using a linear combination of untreated units that closely mimic the treated unit. Often times, creating a synthetic control is not possible due to untreated units' dynamic characteristics such as integrated processes or a time varying relationship. In this paper, I propose a new approach to estimate the synthetic control counterfactual by incorporating time varying parameters. This is done using a state space framework and Bayesian shrinkage. The dynamics allow for a closer pre-treatment fit leading to more precise counterfactual estimation. Monte Carlo simulations are performed to investigate the usefulness of the proposed model in a synthetic control setting. I then compare the proposed model to two existing approaches in classic synthetic control case studies. Results suggest the proposed model produces lower mean squared forecast error when dynamic relationships are present. In addition, the model performs similar to existing approaches when no dynamics are present.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(bookdown)
library(readr)
library(tidyverse)
library(dplyr)
```


\newpage

```{r, child="01-intro.Rmd"}

```

```{r, child="02-setup.Rmd"}

```

```{r, child="03-par_est.Rmd"}

```

```{r, child="04-mcmc.Rmd"}

```

```{r, child="06-ms_sim.Rmd"}

```

```{r, child="05-emp_res.Rmd"}

```

```{r, child="08-concl.Rmd"}

```

\newpage
# Work Cited 
<div id="refs"></div>
\newpage

```{r, child="appendix.Rmd"}

```