---
title: "appendix"
output: pdf_document
---

\appendix

# Appendix


## Deriving Distributions for the Gibbs Sampler

The derivations are based off of @park_bayesian_2008. Notable changes have been made for this specific application. Namely, the model is larger, $\beta$ and $\sqrt{\theta}$ are not conditioned on $\sigma^2$, and the hierarchical structure is redefined to be a *global-local* shrinkage estimator. @park_bayesian_2008 use a hierarchical formulation where the local shrinkage is dependent on the global shrinkage. @park_bayesian_2008 also use an inverse gamma distribution to represent the global shrinkage while this paper opts to use a half Cauchy distribution.

Recall: 

$$y_{0,t}(0)=\sum_{j=1}^{J+1}\left(\beta_{j}+\tilde{\beta}_{j,t}\sqrt{\theta_j}\right)y_{j,t}(0)+\epsilon_t$$


The conditional prior of $\mathbf{y_0}$ is defined as $\mathcal{N}\left( \mathbf{y}\beta_{j}+(\mathbf{y}*\tilde{\beta}_{j})\sqrt{\theta_j}), \sigma^2 I\right)$ where * denotes element wise multiplication. Conditional on $\alpha_i^2$ and $\xi_i^2$, the model follows a standard linear regression with normal priors. Textbook tools can be used to derive the distributions for the Gibbs sampler. The joint density is defined as:
$$
\begin{aligned}
f(\mathbf{y_0} | \beta, \sqrt{\theta},& \sigma^2)\pi(\sigma^2) \pi(\lambda^2)\pi(\kappa^2) \prod_{j=1}^{J+1} \pi(\beta_j | \alpha_j^2, \lambda^2) \pi(\alpha_j^2) \pi( \sqrt{\theta_j} | \xi_j^2, \kappa^2) \pi(\xi_j^2)  =\\
&\frac{1}{{(2\pi \sigma^2})^\frac{T_0-1}{2}}\ exp\left\{\frac{-1}{2\sigma^2}\left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)^T \left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right) \right\}\\
&\frac{a_2^{a_1}}{\Gamma(a_1)} (\sigma^2)^{-a_1-1} exp\left\{-\frac{a_2}{\sigma^2}\right\}\frac{\frac{1}{\zeta_{\beta}}^{\frac{1}{2}}}{\Gamma\left(\frac{1}{2}\right)} (\lambda^2)^{-\frac{1}{2}-1}exp\left\{-\frac{\frac{1}{\zeta_\beta}}{\lambda^2} \right\}\frac{ \frac{1}{\zeta_{\sqrt{\theta}}} ^{1/2}}{\Gamma\left(\frac{1}{2}\right)} (\kappa^2)^{\frac{-1}{2}-1}exp\left\{-\frac{\frac{1}{\zeta_{\sqrt{\theta}}}}{\kappa^2} \right\}\\
&\frac{1^{1/2}}{\Gamma(1/2)} \zeta_{\beta}^{-{\frac{1}{2}-1}} exp\left\{\frac{-1}{\zeta_{\beta}} \right\}\frac{1^{1/2}}{\Gamma(1/2)} \zeta_{\sqrt{\theta}}^{-{\frac{1}{2}-1}}
exp\left\{\frac{-1}{\zeta_{\sqrt{\theta}}} \right\}\\
&\prod_{j=1}^{J+1} \frac{1}{(2\pi  \alpha_j^2\lambda^2)^\frac{1}{2}} exp\left\{ \frac{-1}{(2 \alpha_j^2 \lambda^2)} \beta_j^2 \right\}  exp\left\{ -\alpha_j^2\right\}
 \frac{1}{(2\pi \xi_j^2 \kappa^2)^\frac{1}{2}}exp\left\{\frac{-1}{(2 \xi_j^2 \kappa^2)} \sqrt{\theta}_j^2 \right\}exp\left\{ \xi_j^2\right\} \\
\end{aligned}
$$

### Conditional Distribution of $\beta$ and $\sqrt{\theta}$

To solve for the conditional distribution of $\beta$ and $\sqrt{\theta}$, drop the terms that don't involve $\beta$ and $\sqrt{\theta}$. This only leaves 3 exponential terms:

$$
\begin{aligned}
exp\left\{\frac{-1}{2\sigma^2}\left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)^T \left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right) \right\}\\
\prod_{j=1}^{J+1} exp\left\{ \frac{-1}{(2 \alpha_j^2\lambda^2)} \beta_j^2 \right\}exp\left\{ \frac{-1}{(2 \xi_j^2\kappa^2)} \sqrt{\theta_j}^2 \right\}
\end{aligned}
$$
Combining exponents yields:

$$
\begin{aligned}
exp\left\{\frac{-1}{2\sigma^2}\left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)^T \left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right) + \sum_{j=1}^{J+1}\frac{-\sigma^2}{(2\alpha_j^2 \lambda^2)}\beta_j^2  + \sum_{j=1}^{J+1}\frac{-\sigma^2}{(2\xi_j^2 \kappa^2)}\sqrt{\theta_j}^2 \right\}
\end{aligned}
$$
Define:

$$\mathbf{\tilde{y}}=\left[\mathbf{y}, \mathbf{y}*\tilde{\beta}\right]_{T_0-1,2(J+1)}$$, 

$$\Theta=\left[\beta, \sqrt{\theta}\right]_{2(J+1), 2(J+1)}$$ and

$$D=diag\left[\lambda^2\alpha_1^2,...\lambda^2\alpha_{J+1}^2, \kappa^2 \xi_1^1,\dots, \kappa^2 \xi_{J+1}^2\right]_{2(J+1),2(J+1)}$$.


Focusing solely on the exponential term and rearranging yields:


$$\frac{-1}{2\sigma^2}\left[\left(\mathbf{y_0}-\mathbf{\tilde{y}}\Theta\right)^T \left(\mathbf{y_0}-\mathbf{\tilde{y}}\Theta\right) + \Theta^T \sigma^2 V^{-1} \Theta \right]$$
Multiplying out and rearranging yields:

$$
\begin{aligned}
&\frac{-1}{2\sigma^2}\left[\mathbf{y_0}^T \mathbf{y_0}- 2\mathbf{y_0}\mathbf{\tilde{y}}\Theta +\Theta^T(\mathbf{\tilde{y}}^T \mathbf{y_0} +\sigma^2 V^{-1})\Theta \right]
\end{aligned}
$$
Focus solely on the terms within the brackets including $\Theta$ for a moment. Setting $A=\mathbf{\tilde{y}}^T\mathbf{\tilde{y}}+\sigma^2 V^{-1}$ and completing the square yields:

$$
\begin{aligned}
&\left(\Theta - A^{-1}\mathbf{\tilde{y}}^Ty\right)^TA\left(\Theta - A^{-1}\mathbf{\tilde{y}}^Ty\right)\\
&+ y^T\left(I-\mathbf{\tilde{y}} A^{-1} \mathbf{\tilde{y}}^T\right)y
\end{aligned}
$$
Therefore, the part of the conditional distribution that relies on $\Theta$ can be written as:

$$\frac{1}{\sqrt{2\pi \sigma^2}} exp \left\{\frac{-1}{2\sigma^2} \left(\Theta - A^{-1}\mathbf{\tilde{y}}^T\mathbf{y_0}\right)^TA\left(\Theta - A^{-1}\mathbf{\tilde{y}}^T\mathbf{y_0}\right) \right\}$$
which can be summarized as $\Theta$ conditionally distributed as: 

$$ \mathcal{N}\left(A^{-1}\mathbf{\tilde{y}}^T\mathbf{y_0}, \sigma^2 A^{-1}\right)$$ 

### Conditional Distribution of $\sigma^2$

Now, I will derive the conditional distribution for $\sigma^2$. Returning to the joint probability, drop all terms that do not include $\sigma^2$:
$$
\begin{aligned}
&\frac{1}{{( \sigma^2})^\frac{T_0-1}{2}}\ exp\left\{\frac{-1}{2\sigma^2}\left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)^T \left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right) \right\}\\
&\ (\sigma^2)^{-a_1-1}exp\left\{-\frac{a_2}{\sigma^2}\right\}
\end{aligned}
$$
Rearranging yields:
$$
\begin{aligned}
&{{( \sigma^2})^{-\frac{T_0-1}{2}-a_1-1}}\ exp\left\{\frac{-1}{2\sigma^2}\left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)^T \left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)-\frac{a_2}{\sigma^2} \right\}\\
\end{aligned}
$$
which is an inverse gamma distribution without the scaling term. Therefore, $\sigma^2$ is conditionally inverse gamma with *shape* parameter $\frac{T_0-1}{2}+a_1$  and *scale* parameter $\frac{1}{2}\left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)^T \left(\mathbf{y_0}-\mathbf{y}\beta - (\mathbf{y}*\tilde{\beta})\sqrt{\theta}\right)+a_2$.

### Conditional Distribution of $\alpha_j^2$ and $\xi_j^2$

Focusing only on terms involving $\alpha_j^2$, the conditional distribution is:

$$
\begin{aligned}
\frac{1}{( \alpha_j^2)^{1/2}} exp\left\{\frac{-1}{(2\alpha_j^2\lambda^2)} \beta_j^2 - \alpha_j^2 \right\}
\end{aligned}
$$

@park_bayesian_2008 note that by setting $\frac{1}{\alpha_j^2}=\zeta^2$, the density can be rewritten proportionally as an inverse Gaussian:

$$
\begin{aligned}
(\zeta^2)^{-3/2}exp\left\{-\left(\frac{\beta_j^2 \zeta_j^2}{2\lambda^2} + \alpha_j^2 \right) \right\} \propto (\zeta^2)^{-3/2} exp\left\{ \frac{-\beta_j^2}{2\zeta^2 \lambda^2}\left[\zeta^2 -\sqrt{\frac{2\lambda^2}{\beta_j^2}}\right]^2 \right\} \\
= (\zeta^2)^{-3/2} exp\left\{ \frac{-2}{2\zeta^2 \frac{2\lambda^2}{\beta_j^2} }\left[\zeta^2 -\sqrt{\frac{2\lambda^2}{\beta_j^2}}\right]^2 \right\}
\end{aligned}
$$

This is one of many parameterizations of the Inverse Gaussian distribution. The Inverse Gaussian distribution can be written as:

$$f(x)=\sqrt{\frac{\lambda'}{2\pi}}\ x^{-3/2} exp\left\{ -\frac{\lambda'(x-\mu')^2}{2(\mu')^2 x}\right\}$$
with mean parameter $\mu'$ and scale parameter $\lambda$.

Therefore, $\frac{1}{\alpha_j^2}$ is conditionally distributed Inverse Gaussian with mean parameters $\frac{2\lambda^2}{\beta_j^2}$ and scale parameter $\lambda'=2$. $\xi_j^2$ is derived following the same steps.

### Conditional Distribution of $\lambda^2$ and $\kappa^2$

Focusing solely on $\lambda^2$ in the joint distribution yields:

$$\left(\lambda^2\right)^{-\frac{J+2}{2}-1} exp\left\{\left(-\frac{\sum_{j=1}^{J+1} \alpha_j^2}{2}-\frac{1}{\zeta_{\beta}}\right) \frac{1}{\lambda^2} \right\}$$
which is proportional to an inverse gamma distribution with *shape* parameter $\frac{J+1}{2}$ and *rate* parameter $\frac{1}{\zeta_{\beta}} + \frac{1}{2} \sum_{j=1}^{J+1} \frac{\beta_j^2}{\alpha_j^2}$. 

Similarly, $\kappa^2$ will follow an inverse gamma distribution with *shape* parameter $\frac{J+1}{2}$ and *rate* parameter $\frac{1}{\zeta_{\sqrt{\theta}}} + \frac{1}{2} \sum_{j=1}^{J+1} \frac{\sqrt{\theta_j} ^2}{\xi_j^2}$. 

### Sample $\zeta_{\sqrt{\theta}}$ and $\zeta_{\beta}$

Finally, $\zeta_{\beta}$ will follow an inverse gamma with shape 1 and rate $1+\frac{1}{\lambda^2}$. Similarly, $\zeta_{\sqrt{\theta}}$ will follow an inverse gamma with shape 1 and rate $1+\frac{1}{\kappa^2}$.