---
title: "Data"
output: pdf_document
bibliography: references.bib
linkcolor: blue
---

```{r, echo = F}
number_of_universities = 53
```

# Data

The main analysis utilizes Daily Crime Logs from `r number_of_universities` university-specific police departments over a six-year period (2014-2019). I omit the year 2020 due to the COVID-19 pandemic in which university activity varied substantially from the previous years. The data was obtained under the Jeanne Clery Act, which states that universities that receive federal funding are mandated to keep Daily Crime Logs which specify the universe of crimes that university police officers report or are reported to the university police department over the last seven years. Daily Crime Logs are unique in that the data is unaggregated; each Daily Crime Log contains the date reported at the hourly level, in addition to a short description of the crime. Moreover, the Daily Crime Logs contain all incidents reported by or to the university police. Therefore, the data includes offenses such as alcohol offenses which are missing from national databases such as the Uniform Crime Reporting System (UCR) and the National Incidence-Based Reporting System (NIBRS).^[NIBRS, as noted earlier, only has alcohol offenses for crimes that end in arrest.] Additionally, the by-day-by-hour reporting makes the Daily Crime Logs preferable to other university crime databases such as Campus Safety and Security Data provided by the US Department of Education which features only yearly-level data on offenses. 

## Data Collection

Under the Jeanne Clery Act, university police must allow their Daily Crime Logs to be ready for inspection within two business days of an inquiry. The universities must either send their Daily Crime Logs (usually in PDF format) electronically, direct you to a website that holds their records, or arrange a time to inspect records in-person.^[Universities do not have to allocate copies of the crime logs, they only have to make them available for inspection. Hence, there are two universities that had fraternity moratoriums, but were not able to be included in the sample due to this issue. Additionally, five universities provided Daily Crime Logs that were in formats that were completely unreadable by any software (e.g. scanned documents).] Each of these records were parsed using PDF extracting and webscraping techniques. Figure \ref{crime_log_example} shows a sample of a Daily Crime Log.^[Nearly every Daily Crime Log varied by university.] I use the date reported as the date of the crime rather than the date occurred, as the date reported is featured across every university Daily Crime Log and the date occurred is often missing. However, the differences between these two dates are negligible as the mean and median difference is 0 days between the date reported and date occurred.

## Data Harmonization

Each university's Daily Crime Log varies in the description of the crimes reported. For instance, the report of "driving while intoxicated" may be represented in several ways across university police departments such as "dwi", "operating while intoxicated", or "owi". To achieve harmonization across university police departments, I pattern-matched key words using regular expressions relating to specific categories of crimes that are reported in the US Department of Education Campus Safety and Security Data: sexual assault, alcohol offenses, and robbery. I focus primarily on sexual assault and alcohol offenses since these crimes have been previously linked to college partying [@lindo_college_2018] and fraternities [@foubert_behavior_2008] respectively. A combination of robberies and burglaries acts a placebo check; there is no literature pointing to robberies or burglaries being correlated with fraternity or college partying behavior, so there is no reason to believe moratoriums would cause increases or decreases. Table \ref{tab:matching_table} shows the keywords used to pattern match to each offense type. These keywords were derived from surveying the most frequent descriptions of crimes within each university police department. For instance, if the phrase "liquor law violation" was a common description in a university's crime logs, then the keyword "liquor" was used to match to an alcohol violation. This method is imperfect as it may underestimate the true reported offenses if particular keywords were not matched, or it may overestimate the true reported offenses if particular keywords systematically match to incorrect crimes. However, Table \ref{tab:top_categories} shows the 30 most frequently reported offenses after the pattern matching process. In each of the columns, there is no apparent mismatching.

Figure \ref{barplot} shows the distribution of means across alcohol offenses, reports of sexual assaults, and robbery/burglary by each day of the week. As expected, alcohol offenses are more frequent on Friday, Saturday, and Sunday, while sexual assaults and robberies/burglaries are relatively more consistent in reporting across the week. Notably, alcohol offenses show a large decrease in average counts on Saturdays when moratoriums are present. Table \ref{tab:summarystatscrime} shows summary statistics of alcohol offenses, reports of sexual assaults, and robbery/burglary, split by weekends and moratorium days. Moratoriums appear to have lower means across each of the crimes and tighter standard deviations on Friday-Sunday. Weekdays, on the other hand, show no systematic declines in means across any of the outcomes. 


