---
title: "Fraternity Moratoriums"
output: pdf_document
---
```{r, echo = F}
number_of_universities = 53
```

# Fraternity Moratoriums

## Collection of Dates and University Characteristics

University-wide fraternity moratoriums are defined as a temporary prohibition of fraternity-related social gatherings with alcohol. While there is variation in each university's guidelines (e.g. some universities may restrict third-party vendors for fraternity events during a moratorium, others may not), each of the universities in the sample restrict registered social events with alcohol.^[Fraternity social events typically need to be registered through their respective university. An example of the guidelines for UC Berkeley university can be found at https://lead.berkeley.edu/wp-content/uploads/2015/01/all-greek-social-code.pdf.] The existence of a moratorium was found searching school newspaper articles, Lexis Nexis, and a private repository of news articles relating to fraternities. Table \ref{tab:closure_table} shows each of the university's moratorium start and end dates. Each date in Table \ref{tab:closure_table} was verified using either newspaper articles, conversations with Fraternity and Sorority Life employees, or Freedom of Information Act requests. However, Table \ref{tab:closure_table} is not an exhaustive list of all moratoriums. Four universities were omitted from the sample^[These universities include Cal State Northridge, Miami University , Pennsylvania State University, and University of Texas at Arlington.] because either verification of exact start and end dates could not be achieved, their moratorium did not include prohibiting alcohol, or the university's police department did not provide Daily Crime Logs in a format readable by any software.^[One particularly notable omission from the sample is Pennsylvania State University which registered a fraternity moratorium on 2/7/17 due to the death of Timothy Piazza. The university police department did not allow copies of their Daily Crime Logs to be distributed- only inspected in person.] Hence, the `r number_of_universities` universities experiencing moratoriums in the sample are a subset of all university-wide fraternity moratoriums that occurred between 2014 and 2019. Additionally, `r 15` universities that *did not* experience a fraternity moratorium, but experienced a fraternity-activity-related death are included as a 'never treated' control group.^[While there are 19 of these universities, I could only complete the data for 15 of them. Texas Tech, Delaware State, Cal State Fullteron, and Bloomburg University of Pennsylvania all had either unreadable Daily Crime Logs, or did not provide them to me.] These universities were found using the journalist/professor Hank Nuwer's online repository of hazing deaths from 2000-2021.^[Hank Nuwer's website can be found at: https://www.hanknuwer.com/hazing-destroying-young-lives] This amounts to `r number_of_universities` universities that are widely dispersed among the US as shown in Figure \ref{map}. Table \ref{tab:university_characteristics} shows summary statistics of university characteristics using data from the Integrated Postsecondary Education Data System (IPEDS). On average, the universities are large (~28k enrollment), predominantly white (~59% of undergraduates), mostly public (84%) and have a wide variation in terms of selectivity and graduation rate. 

## Who oversees fraternity moratoriums and why do they occur? {#prediction}

Fraternities have three sources of oversight: the university's IFC council,^[There is an important distinction between an IFC fraternity and the university's IFC council. While an IFC fraternity belongs to the North American Interfraternity Conference, a trade group representing fraternities, the IFC council is a collection of undergraduates from various fraternity chapters that oversee fraternity-related activity on a particular campus.] the unique fraternity chapter's national headquarters, and the university itself. Of these three sources of oversight, only the IFC and university have the jurisdiction to impose a university-wide fraternity moratorium. IFC council-imposed moratoriums account for `r round(16/45,2)*100`% of the moratorium in the sample, while universities account for the remaining `r round(29/45,2)*100`%. IFC moratoriums are student-enforced; they are implemented by the university IFC which is a small council of undergraduate fraternity members representing each chapter. While these may be supported by the university, the only overseer of the guidelines are the fraternities themselves. In contrast, university-enacted moratoriums are the result of university officials imposing restrictions across all IFC fraternity chapters. They are regulated by the university itself and frequently require new guidelines and criteria to be met before lifting the moratorium (e.g. sexual assault training or a task-force investigation). 

Moratoriums are the result of a plausibly exogenous shock to a university such as fraternity-related deaths, sexual assaults, hazing violations, or racist activity gone viral. Figure \ref{trigger_plot} shows the `r 45` moratoriums in the sample by the event that triggered the moratorium. The most frequent (`r round(19/45,2)*100`%) are behavior violations which include alcohol violations, racist activity gone viral, and hazing allegations, while second are fraternity related deaths (`r round(10/45,2)*100`%), and third are sexual assault allegations (`r round(9/45,2)*100`%). Of these triggering events, death results in the longest average moratorium at approximately 103 university-calendar days, while behavior and sexual assault allegations result in approximately 58 and 31 average university-calendar days respectively. Seven (`r round(7/45,2)*100`%) of these moratoriums had no clarifying explanation for the resulting moratorium. 

To test the plausible exogeneity of these triggering events, I estimate both a linear probability and logit model on pre-treatment characteristics from each university in attempt to predict a fraternity moratorium. If there are observable characteristics of universities that correlate with the decision to impose a moratorium at strong statistically significance levels, then the moratoriums may not be exogenous. On the other hand, if there are none (or very few), the plausible exogeneity would still hold. I estimate Equation \ref{prediction_model} where $EverMoratorium_u$ represents whether university $u$ ever experiences a fraternity moratorium, $\mathbb{X}_u$ is a vector of observable characteristics including enrollment, demographics, pricing, and source of income for each university averaged over all years prior to the first moratorium, and $\epsilon_i$ is the error term. Standard errors are clustered by university, and an indicator for missing data is added to the model as revenues and SAT data is missing among a large portion of the sample.

```{=tex}
\begin{equation}\label{prediction_model}
EverMoratorium_u = \gamma \mathbb{X}_{u} + \epsilon_u
\end{equation}
```

Figure \ref{predict_moratorium} shows the results of this prediction exercise, plotting each coefficient estimate. Overall, there is little evidence that university characteristics can predict if a moratorium is implemented as the confidence intervals contain the standardized mean. While there appears to be slight evidence that selectivity (e.g. fraction admitted) and total cost are predictors of moratoriums, these are weakly significant, not robust across both estimation methods, and likely represent 'by-chance' significance due to the large number of hypothesis tests. A Bonferroni p-value correction (e.g. multiplying the p-value by the number of hypothesis tests) yields no statistical significance across any of the observable covariates, thus providing further evidence of the plausible exogeneity of moratoriums. 




