---
title: "Figures"
output: pdf_document
editor_options: 
  chunk_output_type: console
header-includes:
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{amsmath}
- \usepackage[english]{babel}
- \usepackage{bm}
- \usepackage{float}
- \usepackage[fontsize=12pt]{scrextend}
- \usepackage{graphicx}
- \usepackage{indentfirst}
- \usepackage[utf8]{inputenc}
- \usepackage{pdfpages}
- \usepackage[round,authoryear]{natbib}
- \usepackage{setspace}\doublespacing
- \usepackage{subfig}
- \theoremstyle{definition}
- \newtheorem{definition}{Definition}[section]
- \newtheorem{assumption}{Assumption}
- \newtheorem{theorem}{Theorem}[section]
- \newtheorem{corollary}{Corollary}[theorem]
- \newtheorem{lemma}[theorem]{Lemma}
- \newtheorem*{remark}{Remark}
- \newcommand{\magenta}[1]{\textcolor{magenta}{#1}}
- \newcommand{\indep}{\perp \!\!\! \perp}
- \floatplacement{figure}{H}
- \usepackage{natbib}
- \usepackage{pdflscape}
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Figures

```{r}
source(here::here("figures/closure_distribution.R"))
```

\begin{landscape}
```{r, fig.cap="\\label{closure_distribution}Distribution of moratoriums for 38 universities across the sample period (2014-2019). Length of moratoriums represent calendar-year days.", fig.align = "center",fig.width= 13, fig.height= 7, out.width= "100%"}
closure_distribution
```
\end{landscape}

```{r}
source(here::here(paste0("figures/triggerplot_bylength.R")))
```

\begin{landscape}
```{r, fig.cap= "\\label{trigger_plot}Average number of academic calendar days under moratorium by triggering event of moratorium.", fig.align = "center",fig.width= 44, fig.height= 36, out.width= "80%"}
trigger_plot
```
\end{landscape}

```{r}
source(here::here(paste0("Figures/map.R")))
```

```{r, fig.cap= "\\label{map}Map of the 38 univerisities included in the sample that experienced a fraternity moratorium. IFC fraternity populations are based on the data most recently available."}
map_of_schools
```

```{r}
source(here::here(paste0("figures/event_study_byday.R")))
```

```{r, fig.cap = "\\label{es_alc}Event study of effect of moratorium on alcohol offenses at the daily level. The x-axis represents weeks until moratorium, normalized by the week before. Weeks are 7 day periods. Fixed effects are university and day-by-month-by-year."}
es_alc_graph_day
```

```{r, fig.cap = "\\label{es_drug}Event study of effect of moratorium on drug offenses at the daily level. The x-axis represents weeks until moratorium, normalized by the week before. Weeks are 7 day periods. Fixed effects are university and day-by-month-by-year."}
es_drug_graph_day
```

```{r, fig.cap = "\\label{es_sex}Event study of effect of moratorium on sexual assaults at the daily level. The x-axis represents weeks until moratorium, normalized by the week before. Weeks are 7 day periods. Fixed effects are university and day-by-month-by-year."}
es_sex_graph_day
```


```{r}
source(here::here(paste0("figures/treatment_passing.R")))
```

```{r, fig.cap = "\\label{mpasssing_alc}Effect of moratorium on alcohol offenses broken down by time within moraotrium. Each category is mutually exclusive. Numbers below x-axis labels represent the number of schools the estimate is identified by since each university's moratorium length differs."}
mprogression_alc
```

```{r, fig.cap = "\\label{mpasssing_drug}Effect of moratorium on drug offenses broken down by time within moraotrium. Each category is mutually exclusive. Numbers below x-axis labels represent the number of schools the estimate is identified by since each university's moratorium length differs."}
mprogression_drug
```

```{r, fig.cap = "\\label{mpasssing_sex}Effect of moratorium on sexual assault offenses broken down by time within moraotrium. Each category is mutually exclusive. Numbers below x-axis labels represent the number of schools the estimate is identified by since each university's moratorium length differs."}
mprogression_sex
```

