---
title: "Tables"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(kableExtra)
```

# Tables

```{r}
source(paste0(here::here("Tables/matching_word_table.R")))
```

```{r}
kable(matching_table, booktabs = T, caption = "\\label{matching_table}Words/phrases used to pattern match on outcomes of interest.") %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "blue") %>%
  column_spec(2, width = "20em") %>% kable_styling(latex_options = "HOLD_position")
```


```{r university_characteristics}
source(paste0(here::here("tables/summary_stats_university.R")))
```

```{r}
university_characteristics
```

```{r}
source(paste0(here::here("figures/twfe_weights.R")))
```

```{r}
twfe_weights %>% 
  kable_styling(latex_options = "scale_down")
```


```{r}
source(here::here(paste0("tables/regressions_main.R")))
```

```{r}
main_table %>% 
  kable_styling(latex_options = "scale_down")
```

```{r}
weekend_table
```

```{r}
source(here::here(paste0("tables/regressions_lag_table.R")))
```

```{r}
lag_table 
  
```

