---
title: "Data"
output:
  pdf_document: default
---

# Data \label{section:data}

The main analysis uses data from a variety of sources. In particular, I construct a novel data set that links incident-level crime from university police departments to fraternity moratorium dates and university characteristics over a six-year period (2014-2019).

## Sample Construction \label{section:construction}

The 37 universities in the sample have a combined 44 moratoriums in the sample period (2014-2019). These moratoriums represent any moratorium that match the following criteria: first, the moratorium must prohibit alcohol from all fraternity social events campus-wide, and second, the moratorium must be identifiable by Google/Lexis Nexis searches. Appendix Table \ref{closure_table} lists all of the universities included with their corresponding moratorium dates. Importantly, these do not represent the universe of fraternity moratoriums that occurred from 2014-2019. In particular, there are six schools that are known to have experienced a moratorium in this time frame, but are excluded due to data issues or their definition of a moratorium.^[Miami University is excluded due to being unable to verify the end-date of their moratorium. Pennsylvania State University is excluded because they did not digitally release their Daily Crime Logs. University of Texas at Arlington is excluded because the crime logs are scanned images that can not be read reliably by any computer software. Cal State Northridge is excluded because it is unclear whether the moratorium includes a ban on alcohol. University of North Florida is excluded because of a discrepancy between public records information and newspaper articles: newspaper articles claim there is a moratorium beginning 12/4/17, but the public records department says this is untrue. The University of Vermont is excluded due to issues with the reliably of the data—crimes often are reported to have occurred in large intervals of days (or months) for nearly 40% of the data provided which is not suitable for the daily-level analysis in this paper. There may exist other universities that experienced a moratorium, but may not have had any sort of news coverage-these are also be excluded from the sample.] While there is a possibility that the sample period contains more moratoriums from other universities, the documents provided from various fraternity associations and conversations with experts in the field suggest that the sample covers the large majority. Furthermore, each moratorium's start and end dates are obtained through public records requests (20%), conversations with Fraternity and Sorority Life advisers (11%), and school newspaper articles (68%). All start and end dates are verified by at least one of these sources.^[There is one exception to this which is the first moratorium at San Diego State University. While the start date has been verified by a newspaper article, the exact end date is ambiguous. However, evidence shows that the moratorium ended before the start of the 2015 spring semester, and hence, this is the date used in the analysis. The newspaper article showing this evidence can be seen here: https://newscenter.sdsu.edu/sdsu_newscenter/news_story.aspx?sid=75357.]  

Daily reports of incidents are parsed from Daily Crime Logs maintained by the 37 universities' police departments resulting in approximately 500,000 distinct reports. The Daily Crime Log is an incident-level source of information; each crime log contains the date occurred, date reported, time occurred, time reported, a short summary of the incident, the general location of the incident, and a distinct case number (see Appendix Figure \ref{crime_log} for an example).^[While the date occurred is technically mandated under the Clery Act to include each of these categories, only 32 of the 37 universities contained the date occurred. However, these five schools contained the date reported. I use the date reported in lieu of the date occurred when the date occurred is missing.] The Daily Crime Log contains the universe of incidents that are reported to (or by) the university-specific police department. Hence, each of the incidents listed in these logs represent incidents that occurred on or nearby university property.^[Sometimes, university police may respond to calls slightly outside of university property. Based on conversations with university police, this is usually when a student is involved.] 

There are two main advantages of the Daily Crimes Logs over readily available crime data sources such as the National Incidence-Based Reporting System (NIBRS), Uniform Crime Reporting System (UCR), and the Campus Safety and Security Data (CSS). First, each university police department is mandated under the Clery Act to maintain and make available a Daily Crime Log. Crime logs must be kept for seven years, although this mandate is subject to each university's interpretation.^[For instance, if a crime log from 2014 is requested in year 2021, most police departments will have this information as it falls within 7 years. However, some police departments may consider seven-years to be inclusive of their current year, and hence, may only retain records for 2015-2021.] Hence, only one university is missing data from a complete calendar-year.^[Rollins College is missing data from 2014. North Carolina State University is also missing data, although their missing data spans from January 2014-August 2014.] Second, the Daily Crime Logs contain all daily incidences of alcohol offenses and sexual assaults reported to or by the police—the primary outcomes used in the main analysis. This is a major advantage as the UCR does not contain alcohol offenses and the NIBRS only contains alcohol violations that end in arrests. Since not all violations of underage drinking at universities result in arrests, the NIBRS data would under-report the prevalence of alcohol misuse. While the CSS data includes similar information as the Daily Crime Logs,^[There are important differences between these two sources. The CSS provides data on liquor violations that occur in residence halls that may not be reported to the police and therefore not appear in the Daily Crime Logs. Hence, an aggregated Daily Crime Log should not (and will not) match the CSS exactly.] the CSS data is aggregated to the calendar-year which makes the effect of moratoriums difficult to study given their short-lived nature. See Appendix Table \ref{data_used} for more details on the advantages of the Daily Crime Logs.


University characteristics such as total enrollment, student demographics, and academic calendars are obtained through the Integrated Postsecondary Education Data System (IPEDS) or directly from the corresponding university. However, not all academic calendars for each year in the sample are available. Therefore, only the most current academic calendar found on a university's website is utilized. To define the start of a semester, the first day of instruction is used while the finalized grade date is used to denote the end of a semester. Since there are small changes in academic calendars year-to-year, a seven-day window is subtracted from each start date and added to each end date of every semester. For instance, if a semester begins on August 20th and ends on December 16th, the sample period will be August 13th to December 23rd.

## Matching and Harmonization 

One of the challenges of using the Daily Crime Logs is their uniqueness to each university. While all crime logs contain daily reports of incidents, each university police department describes their incidents differently. For example, Indiana University's crime log describes driving under the influence as "driving under the influence" while Cal Poly San Luis Obispo's describes this as "dui". As such, there is a lack of harmonization between the crime logs—incidents do not have a standardized way of being reported between university police departments. To mitigate this issue, I use regular expressions to match on typical words, phrases, and abbreviations seen in each crime log for descriptions relating to alcohol offenses and sexual assaults.^[In particular, I found all unique descriptions of incidences in each Daily Crime Log, and then independently analyzed which descriptions matched to each offense.] For each offense, I use the following definitions for matching the incident descriptions:

* **Alcohol Offense** - Any incident description that refers to a public intoxication, underage drinking, or drinking in an unlawful manner. For instance, public drunkenness, a minor in possession, and driving while intoxicated refer to each of these definitions respectively. 
* **Sexual Assault** - Any incident description that refers to a sexual assault or sex crime including rape and fondling. This corresponds to the types of sex crimes that are reported in the CSS data: rape, statutory rape, incest, and fondling. However, incest sex crimes are omitted as these are infrequent and less likely to be associated between college students.

Table \ref{matching_table} shows the corresponding words, phrases, and abbreviations used to match each incident description to its corresponding offense. Importantly, each of these phrases is only a portion of an incident's description. For instance, the word "sex" is used as a word to match on sexual assaults. The advantage to this method is that the word "sex" will be matched to descriptions such as "sexual assault" or "sex offense" since the word "sex" appears in each of these descriptions. While this is an imperfect method, it is conservative—it is likely that this method is under-counting the true number of offenses in each category since there are incident descriptions where words are misspelled (e.g., "aclohol" vs. "alcohol"). Appendix Table \ref{top_categories} shows the results of this matching process with the most 15 most frequent descriptions matched to each offense. 

## Descriptive Statistics

Table \ref{summary_stats} summarizes the characteristics of the 37 universities and their corresponding distribution of offenses and fraternity moratoriums. Panel A shows descriptive statistics of the universities' demographics. On average, the universities are large with total enrollment exceeding 29,000. Undergraduates are the majority population with 61% of the student population being white. Graduation rates vary substantially between schools and there is particularly large variation in the selectivity of each university. For instance, graduation rates and the fraction of students admitted range between 39-95 percent and 14-94 percent respectively. Moreover, IFC fraternities represent a small fraction of the total enrollment with approximately 5% of students belonging to an IFC fraternity on average. Panel B shows summary statistics of the primary outcome measures: reports of alcohol offenses and sexual assaults. Each of these outcomes are measured as per-25,000 enrolled students per-academic-calendar day. Therefore, the average amount of alcohol offenses per-25,000 enrolled students in an academic-calendar day is approximately one-half. Lastly, Panel C describes characteristics of the 44 moratoriums in the sample. On average, each university undergoes approximately one moratorium, although universities can experience up to three. Furthermore, the moratoriums persist for an average of 64 academic-calendar days. Notably, there is significant variation in the length of the moratoriums. In particular, the minimum length of a moratorium is only six academic-calendar days while the maximum is 541. Due to this large range, it is important to note that a median moratorium lasts for approximately 46 academic-calendar days (approximately 1.5 months). 



