---
title: "Figures"
output: pdf_document
fontsize: 11pt
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = F, message = F, warning = F) -->
<!-- knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) -->
<!-- ``` -->

\FloatBarrier
# Figures
This page is intentionally blank. 

```{r}
source(here::here("figures/closure_distribution.R"))
```


```{=latex}
\begin{landscape}
\begin{figure}[t]
```
```{r, echo=FALSE, fig.align = "center",fig.width= 13, fig.height= 7, out.width= "100%"}
closure_distribution
```
```{=latex}
\caption{Distribution of Moratoriums Across the Sample Period for all Universities \label{closure_distribution}}
\textit{Note:} The sample period starts in 2014 and ends on the last day of 2019. The lengths of the moratoriums in this graph represent calendar-day lengths, not academic-calendar day lengths. Universities experience one to three moratoriums in the sample period.
\end{figure}
\end{landscape}
```



```{r}
source(here::here(paste0("figures/triggerplot_bylength.R")))
```

```{=latex}
\begin{landscape}
\begin{figure}[t]
```
```{r, echo=FALSE, fig.align = "center",fig.width= 16, fig.height= 9}
trigger_plot +
  theme(strip.text = element_text(size = 12))
```
```{=latex}
\caption{Number of Academic Calendar Days in Each Moratorium by Triggering Event\label{trigger_plot}}
\footnotesize{\textit{Note:} Lengths of moratoriums represent academic calendar days. Therefore, the lengths of moratoriums differ from Figure \ref{closure_distribution}. Blue shaded regions represent a moratorium that was imposed by the university, while red shaded moratoriums represent moratoriums that were imposed by the IFC. Each of the four categories represents the event that triggered a moratorium. Behavior violations is a catchall term for hazing, rule violations, offensive behavior, and other disorderly conduct. Death relates to a fraternity-related death that triggered a moratorium. Sexual assaults relate to a sexual assault case that triggered a moratorium. Lastly, the Unspecified category represents all moratoriums in which the moratorium triggering event is unknown or unclearly defined.}
\end{figure}
\end{landscape}
```

```{r}
source(here::here(paste0("figures/map.R")))
```

```{=latex}
\begin{figure}[t!]
```
```{r}
map_of_schools
```
```{=latex}
\caption{Locations of the Universities Included in the Sample \label{map_of_schools}}
\textit{Note:} There are a total of 37 universities in the sample, five of which are private universities. Data on both geographic location and private/public entity are obtained from the Integrated Postsecondary Education Data System (IPEDS).
\end{figure}
```



```{r}
source(here::here(paste0("figures/event_study_final_dec13.R")))
```

```{=latex}
\begin{figure}[t]
```
```{r, echo=FALSE}
es_alc_14_g
```
```{=latex}
\caption{Event Study for Alcohol Offenses \label{es_alc}}
\textit{Note:} The shaded area point estimate represents an entire moratorium period for each university. Hence, the shaded area point estimate has varying amounts of days within based on the university. For instance, Arkansas State University had a 39-day moratorium and therefore their shaded area point estimate would be identified by the 39 moratorium days. Point estimates not within the shaded region are 14-day periods. Number of days within a period are chosen to give approximately a median-length (46 days) moratorium on each side of the shaded area. All periods are normalized by the 14-day period before the moratorium. Alcohol offenses are defined as alcohol offenses per-25000 enrolled students. Controls include holiday, spring semester, day of the week, football game-days, and university-by-academic-year. Standard errors clustered by university. All errorbars represent 95\% confidence intervals. A joint-hypothesis F-test that each of the leading periods are zero shows that the p-value is 0.27 which is statistically insignificant.
\end{figure}
```


```{=latex}
\begin{figure}[t]
```
```{r, echo=FALSE}
es_sex_14_g
```
```{=latex}
\caption{Event Study for Sexual Assault Offenses \label{es_sex}}
\textit{Note:} The shaded area point estimate represents an entire moratorium period for each university. Hence, the shaded area point estimate has varying amounts of days within based on the university. For instance, Arkansas State University had a 39-day moratorium and therefore their shaded area point estimate would be identified by the 39 moratorium days. Point estimates not within the shaded region are 14-day periods. Number of days within a period are chosen to give approximately a median-length (46 days) moratorium on each side of the shaded area. All periods are normalized by the 14-day period before the moratorium. Sexual assault offenses are defined as sexual assaults per-25000 enrolled students. Controls include holiday, spring semester, day of the week, football game-day, and university-by-academic-year. Standard errors clustered by university. All errorbars represent 95\% confidence intervals. A joint-hypothesis F-test that each of the leading periods are zero shows that the p-value is 0.54 which is statistically insignificant. 
\end{figure}
```

```{r}
source(paste0(here::here("figures/difference_average_offenses.R")))
```


```{=latex}
\begin{figure}[t]
```
```{r, echo=FALSE, fig.height = 10, fig.width = 10}
gridExtra::grid.arrange(diff_average_offenses, left = textGrob("Average Difference in Moratorium Days and Non-Moratorium Days", 
                                                               rot = 90, gp = gpar(fontsize = 12)), bottom = textGrob("University", gp = gpar(fontsize = 11)))
```
```{=latex}
\caption{Difference in Average Offenses on Moratorium Days and Non-Moratorium Days \label{diff_average_offenses}}
\textit{Note:} The y-axis represents the average difference in offenses per-25000 enrolled students on moratorium days and non-moratorium days for each university. Negative y-axis values indicate that average offenses were lower on moratorium days than non-moratorium days. The x-axis denotes a unique university. The solid black line on the y-axis is 0, while the dashed black line denotes the average of the entire distribution.
\end{figure}
```


```{r}
source(here::here(paste0("figures/week_before_after.R")))
```


```{=latex}
\begin{figure}[t]
```
```{r, echo=FALSE, fig.height= 10, fig.width = 10}
gridExtra::grid.arrange(week_before_after_graph, left = textGrob("Coefficient Estimate and 95% Confidence Interval",
                                                               rot = 90), bottom = textGrob(""))
```
```{=latex}
\caption{Coefficient Estimates Including a Week Before and Week After Indicator \label{week_before_after}}
\textit{Note:} The x-axis represents three periods: the week before a moratorium, the moratorium itself, and the week after the moratorium. Indicators for week before and week after are added to specification (2) from Table \ref{main_table}. Controls include holiday, spring semester, day of the week, football game-days, and university-by-academic-year. Standard errors are clustered by university. Weekends represent Fridays, Saturdays, and Sundays. Weekdays represent Mondays-Thursdays. Errorbars represent 95\% confidence intervals.
\end{figure}
```

```{r}
source(here::here("referee_analysis/treatment_passing_weekly.R"))
```


```{=latex}
\begin{figure}[t]
```
```{r, echo=FALSE, fig.height= 10, fig.width = 10}
alc_passing_graph +
  theme(strip.text.x = element_text(size = 12))
```
```{=latex}
\caption{The Dynamics of a Moratorium (Alcohol Offenses) \label{alc_passing_graph}}
\textit{Note:} This figure shows how a moratorium progresses over time. Each point estimate represents a week within a moratorium, except Moratorium Weeks 10+, which pools moratoriums weeks 10 and above. The x-axis represents the week number the moratorium is currently in, while the parenthesis represents the number of universities that identify the point estimate. Recall that moratorium lengths differ across universities, and therefore some universities may not identify each weekly estimate. The y-axis represents the point estimates and 95\% confidence intervals. Panel A estimates include all universities in the sample using the preferred specification, while Panel B estimates include only universities that have moratoriums over two-months long (approximately the average length of a moratorium). Standard errors are clustered by university, and controls include holiday, spring semester, day of the week, and university-by-academic-year.
\end{figure}
```

```{=latex}
\begin{figure}[t]
```
```{r, echo=FALSE, fig.height= 10, fig.width = 10}
sex_passing_graph +
  theme(strip.text.x = element_text(size = 12))
```
```{=latex}
\caption{The Dynamics of a Moratorium (Sexual Assaults) \label{sex_passing_graph}}
\textit{Note:} This figure shows how a moratorium progresses over time. Each point estimate represents a week within a moratorium, except Moratorium Weeks 10+, which pools moratoriums weeks 10 and above. The x-axis represents the week number the moratorium is currently in, while the parenthesis represents the number of universities that identify the point estimate. Recall that moratorium lengths differ across universities, and therefore some universities may not identify each weekly estimate. The y-axis represents the point estimates and 95\% confidence intervals. Panel A estimates include all universities in the sample using the preferred specification, while Panel B estimates include only universities that have moratoriums over two-months long (approximately the average length of a moratorium). Standard errors are clustered by university, and controls include holiday, spring semester, day of the week, and university-by-academic-year.
\end{figure}
```


```{r}
source(here::here(paste0("figures/heteroeffects_trigger.R")))
```

```{=latex}

\begin{figure}[t]
```

```{r, fig.height = 12, fig.width  = 11}
gridExtra::grid.arrange(trigger_reg_graph, left = textGrob("Coefficient Estimate and 95% Confidence Interval", 
                                                               rot = 90), bottom = textGrob("", gp = gpar(fontsize = 11)))
```

```{=latex}
\caption{Heterogeneous Effects of Moratoriums by Triggering Event \label{trigger_reg_graph}}
\textit{Note:} The x-axis represents three periods: the entire sample (All Days), weekends only, and weekdays only.  Specification 2 (the preferred specification) from Table \ref{main_table} is used in estimation. Each of the four categories represent the event that triggered a moratorium. A behavior violation refers to hazing, rule violations, offensive behavior, and other disorderly conduct. Death relates to a fraternity-related death that triggered a moratorium. Sexual assaults relate to a sexual assault case that triggered a moratorium. Lastly, the Unspecified category represents all moratoriums in which the moratorium triggering event is unknown or unclear. Errorbars represent 95\% confidence intervals.
\end{figure}

```

```{r}
source(paste0(here::here("figures/game_day_moratorium.R")))
```


```{=latex}
\begin{figure}[t]
```
```{r, fig.height = 10, fig.width = 10}

gridExtra::grid.arrange(game_moratorium_plot, left = textGrob("Coefficient Estimate and 95% Confidence Interval",
                                                               rot = 90), bottom = textGrob(""))
```
```{=latex}
\caption{The Effect of Football Game-days and Football Game-days + Moratoriums \label{game_moratorium_plot}}
\textit{Note:} Game days include all football games occurring in the sample period. 34 of the 37 universities have football teams and corresponding game days. The y-axis represents coefficient estimates. Errorbars represent 95\% confidence intervals. Each panel is split into two effects: the first effect being the effect of only football game days on the outcome per-25000 enrolled students, and the second being the effect of a football game that occurs within a moratorium. The All Games category includes both home and away games. The effects of game days + moratorium is identified by 89 football games that coincide with moratoriums. Controls include holiday, spring semester, day of the week, and university-by-academic-year. Standard errors are clustered by university. 
\end{figure}
```
