---
title: "Heterogeneity"
output: pdf_document
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Heterogeneity \label{section:heterogeneity}

## Do Party Schools Exhibit the Strongest Effects? \label{section:party_schools}

Universities that have a reputation for partying may be more impacted by the restrictions of moratoriums than universities that party less. For example, past literature finds that party schools exhibit two times the increase in reports of rape on football game days than non-party schools [@lindo_college_2018]. To examine this possibility, I use Niche.com's Top Party Schools in America list.^[I use Niche.com over the Princeton Review since the Princeton Review no longer posts their party school rankings. For more details on the methodology see: https://www.niche.com/about/methodology/top-party-schools/.] The list assigns "party scene" scores based on criteria such as athletic department revenue, fraternity and sorority life statistics, access to bars, and student surveys. Using this list, a university is defined as a party school if it appears in the top 50 rankings. This amounts to 16 of the 37 universities in the sample being classified as a party school. 

As shown in Table \ref{party_school_table}, universities defined as party schools exhibit higher averages of alcohol offenses assaults relative to non-party schools. In particular, non-party schools experience approximately 49% less alcohol offenses on average. These differences are similar when excluding moratorium days (47%), although both party schools and non-party schools have relatively similar levels of sexual assaults.

Table \ref{party_school_table} also shows that party schools exhibit larger decreases in alcohol offenses than non-party schools during moratoriums. The point estimates in Panel A indicate that moratoriums decrease alcohol offenses on academic-calendar days by approximately 33% from the mean for party schools and 16% for non-party schools. Importantly, only the point estimates for party schools are statistically significant, thereby suggesting that the effects of the moratorium are driven by schools that have a stronger party culture. 

## Does the Triggering Event for a Moratorium Matter? \label{section:trigger}

As described in Section \ref{section:moratoriums}, moratoriums can be the result of a fraternity-related death, a prominent sexual assault, or a behavior violation. Given the differing salience of these events, it is possible that a triggering event affects a moratorium's effectiveness. As an illustration, a death may be more salient than a behavior violation, resulting in a behavior shock to the college campus. Moreover, both deaths and sexual assaults are exceptionally undesirable results of risky behavior—a moratorium may seem more justified under these outcomes rather than following an instance of hazing. 

Figure \ref{trigger_reg_graph} reports that the effect of moratoriums is more prominent when the corresponding trigger is a death or sexual assault rather than a behavior violation. In particular, alcohol offenses decline significantly when a fraternity-related death is the triggering event. To ensure that this is the result of the moratorium rather than the triggering death, I use an additional 15 universities that experienced a fraternity-related death in the sample period, but *did not* undergo a moratorium.^[These universities were found using Hank Nuwer's repository of hazing-related deaths in the US: https://www.hanknuwer.com/hazing-deaths/.] Hence, these supplemental universities are those whose students experience the effect of a fraternity-related death, but do not experience a moratorium. First, I exclusively analyze these 15 non-moratorium universities by creating a 64-day binary treatment variable, beginning with the date of the death. A 64-day period is chosen as it is the average length of a moratorium. Next, I estimate the preferred specification using the 64-day period after the death in lieu of the $InMoratorium_{u,t}$ treatment variable. Panel C of Appendix Figures \ref{alc_forest} and \ref{sex_forest} show that there is little evidence of declines in alcohol offenses or sexual assaults following a fraternity-related death without a moratorium. The point estimates for alcohol offenses are consistently positive, while both offenses exhibit insignificant estimates at the 10% level. To increase precision, I supplement this analysis in Panel D of Appendix Figures \ref{alc_forest} and \ref{sex_forest} by adding the 14 never-treated schools that are used in Section 5.3 as never-treated controls for the effect of a death. As shown, the point estimates remain consistent across both of these analyses and the statistical significance does not change. Taken together, there is little evidence suggesting that a fraternity-related causes a decrease in alcohol or sexual assault offenses rather than the moratorium itself. Instead, this points to the possibility that students may more seriously abide by the moratorium guidelines when the triggering event is a death.

Additionally, Figure \ref{trigger_reg_graph} shows significant decreases in sexual assaults when a triggering event involves either a sexual assault or behavior violation. However, the persistent shortcomings of estimating effects on sexual assaults, such as the under-reporting issue, may be exacerbated in this analysis since these estimates are based on a small subset of universities (19 universities for behavior violations and 10 for sexual assaults).^[Survey evidence shows that nearly 80% of sexual assaults go unreported. This is based on statistics from the AAU Campus Climate Survey on Sexual Assault and Sexual Misconduct. See here: https://ira.virginia.edu/sites/ias.virginia.edu/files/University%20of%20Virginia_2015_climate_final_report.pdf] Consequently, although the results indicate evidence of decreases in sexual assaults, this evidence is mostly speculative under the data limitations.


## Is the Share of Students in a Fraternity Important for Effectiveness?

In this subsection, I analyze whether universities with a higher fraction of their student body belonging to IFC fraternities exhibit larger effects during a moratorium. Each university in the sample has a different share of their student population attributed to IFC fraternities. Recall from Table \ref{summary_stats} that the fraction of enrolled students belonging to an IFC fraternity can range from 1% to as high as 10%. Presumably, a moratorium has a greater effect on student behavior when the restrictions apply to a greater share of students.

To conduct this analysis, I replace the $InMoratorium_{u,t}$ treatment variable in the preferred specification with an interaction of $InMoratorium_{u,t}$ and $FractionIFC_u$, where $FractionIFC_u$ is the most recent number of IFC fraternity members at university $u$, divided by the average total enrollment over the sample period. I use the most current count of IFC members since most universities do not hold semester-level records of this information. However, in the universities that do supply complete records, I do not find substantial semester-to-semester changes in IFC populations. Therefore, a recent one-year measure of the IFC population is a good approximation for the other corresponding years. In effect, the interaction of $InMoratorium_{u,t}$ and $FractionIFC_u$ creates a measure of moratorium intensity—universities with a higher fraction of IFC members receive a larger treatment than universities with lower shares.

Table \ref{ifc_share} reports that universities with a higher fraction of their student enrollment belonging to an IFC fraternity exhibit larger decreases in alcohol offenses during a moratorium. In Column 1 of Panel A, the point estimate shows that a 10% increase in the share of IFC members at a fraternity results in a 0.18 decrease in the number of alcohol offenses per-25000 enrolled students during a moratorium. This effect is statistically significant at the 5% level, and, similar to the main results, is strongest on the weekends. In Panel B, although not statistically significant, the point estimates for sexual assaults follow a similar pattern as alcohol offenses—universities with a higher fraction of IFC members in their study body exhibit larger decreases of sexual assaults. Taken together, a moratorium affects students' alcohol-behavior more when the restrictions apply to a greater share of the student body.

