---
title: "Introduction"
output: pdf_document
linkcolor: blue
bibliography: "references.bib"
link-citations: yes
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Introduction \label{section:introduction}

Over 800 universities in the United States have fraternities [@hechinger_true_2017]. Existing literature has documented benefits of membership which include higher future income [@mara_social_2018] and significantly more hours spent participating in community service and volunteering [@hayek_triumph_2002;@asel_effects_2009]. Moreover, according to a Gallup survey in 2021, over 80% of fraternity alumni agreed that they would join their fraternity again if they were to redo their college experience.

Despite these benefits, fraternity membership has been associated with risky behaviors. In particular, at least one hazing-related death has occurred each year in the US between 2000 and 2019,^[This is based on the online repository of hazing deaths from journalist Hank Nuwer. See here:https://www.hanknuwer.com/hazing-destroying-young-lives/] and studies have found that fraternity members binge drink and party more frequently than their non-member peers [@desimone_fraternity_2007;@routon_impact_2014]. While universities have regularly banned specific misbehaving fraternities from their campuses, the past decade popularized a new policy tool called *moratoriums*—campus-wide halts on fraternity social events with alcohol—as a way to change member behavior. 

This paper is the first to estimate the causal effects of moratoriums on campus-wide police reports of alcohol offenses and sexual assaults. Between 2010 and 2019, over 50 moratoriums have been enacted across university campuses, becoming a common policy used by school administrators. However, studying this topic is challenging for several reasons; moratorium dates are difficult to find/confirm and there does not exist a centralized data source for university-specific crime with enough detail to enable casual inference. Despite the lack of research surrounding the efficacy of moratoriums, administrators continue to implement moratoriums as a disciplinary action on fraternities.

Nonetheless, how these moratoriums affect student behavior, and thus on-campus crime, is theoretically unclear. On one hand, prohibiting alcohol from fraternity social events may reduce the incidence of crime. Fraternities are a source of alcohol for underage drinking, as fraternities are typically a mix of lower and upperclassmen [@armstrong_sexual_2006]. Given that the literature has documented that alcohol causes higher prevalence of crimes such as assaults and alcohol offenses [@carpenter_minimum_2015], road accidents and arrests [@francesconi_liquid_2019], and reports of rape [@zimmerman_alcohol_2007;@lindo_college_2018], prohibiting such events could reduce the incidence of on-campus crime—especially for underage students. On the other hand, moratoriums may have the opposite effect. Without alcohol-fueled fraternity parties, students may substitute away from consuming alcohol at fraternity houses to potentially riskier places off-campus where behavior is less regulated by the university. As a result, the net effect of moratoriums remains ambiguous. 

In this paper, I estimate the causal effect of 44 fraternity moratoriums across 37 universities over a six-year period (2014-2019) on university police reports of alcohol offenses and sexual assaults. I use a difference-in-differences identification strategy, leveraging the variation in timing of moratoriums. Intuitively, I compare academic-calendar days (excluding summer and winter breaks) with a moratorium to academic-calendar days without a moratorium while accounting for expected differences across days of the week and different times of the year. I construct a novel data set, merging two particularly unique data sources: university-specific Daily Crime Logs, which contain the universe of all incidents of crime reported to the university police at the incident-level, and moratorium start and end dates obtained through school newspapers and public records requests. 

Using these data, I find that moratoriums significantly decrease alcohol offenses campus-wide by 26%. This effect is driven by weekends (Fridays-Sundays) when college partying is most frequent and is robust across various specifications, estimation methods, and sensitivity tests. Furthermore, I find suggestive evidence that reports of sexual assaults decrease by 29% on the weekends. Both of these declines are concentrated only when a moratorium is in place, therefore suggesting that there are no persistent effects once a moratorium is lifted. In particular, the immediate and subsequent weeks following a moratorium show little evidence that alcohol offenses or sexual assaults significantly decline and this is consistent across moratoriums of different lengths. 

A key distinction of this work is that I am able to closely link changes in student behavior to a campus-wide policy that directly affects college partying. As a result, this study provides further evidence that stronger sanctions on alcohol decrease the number of alcohol-related incidents in college-aged individuals, consistent with @liang_go_2008 who study zero-tolerance drunk driving laws. However, unlike state or federal laws, moratoriums are unique in that university officials have the power to enact them immediately and indefinitely. This makes moratoriums an appealing policy tool as university officials can implement them at times when they see fit. Moratoriums therefore represent an understudied policy lever that university officials can readily use to reduce campus-wide partying, which in-turn, may affect alcohol and sexual assault incidence.

More broadly, this paper adds to the literature in several bodies of work, the first of which is the effect of college partying. While the literature shows that college partying increases daily reports of rape and alcohol offenses when using football game variation [@lindo_college_2018], this study more directly focuses on a policy tool that reduces college partying. I later analyze in Section \ref{section:football} whether moratoriums have mitigating effects on college partying behavior when coinciding with college football game-days, although I find no clear evidence in support of this. Second, this paper contributes to an emerging body of economic work relating to the effectiveness of university policy, and more specifically, fraternity policy. Although university policies such as academic probation [@lindo_alcohol_2013] and financial aid [@dynarski_does_2003] have been found to be effective in improving GPA and recruiting students respectively, there are only two studies as of this writing that analyze fraternity-targeted policies—both of which study the effects of deferring fraternity recruitment from freshman to sophomore year  [@de_donato_effects_2017;@even_greek_2020]. Moratoriums, in contrast, alter a university’s party culture instantly, since unaffiliated undergraduates also attend fraternity parties [@harford_attendance_2002]. However, as discussed in Section \ref{section:progression}, the moratorium effects diminish following the first month of implementation, making them ill-suited as a long-term solution for mitigating excessive partying. Currently, only one related study has examined the relationship between fraternities and university crime [@raghav_greek_2021], although this study focuses on how the size of a fraternity population affects campus crime rather than the effect of a typical fraternity policy. I explore a similar idea in Appendix \ref{asection:fraction} which shows suggestive evidence that universities with higher shares of fraternity members exhibit larger moratorium effects. Last, this paper adds to the literature relating to the effects of alcohol on college-aged individuals which include health effects, such as increases in mortality [@carpenter_effect_2009], emergency room visits [@francesconi_liquid_2019], and adolescent brain development [@silveri_adolescent_2012], and behavioral effects, such as increases in crime [@carpenter_minimum_2015] and hindering academic performance [@carrell_does_2011;@ha_legal_2019]. 

This paper proceeds as follows: Section \ref{section:background} discusses the background on fraternities and moratoriums. Section \ref{section:data} describes the construction of the data. Section \ref{section:strategy} describes the empirical strategy used to estimate causal effects. Section \ref{section:results} presents the main results. Section \ref{section:heterogeneity} explores the differences in effectiveness between different types of schools and moratoriums. Section \ref{section:discussion} analyzes possible implications. Section \ref{section:conclusion} concludes.

# Fraternities in the US \label{section:background}

## Fraternity Demographics and Oversight \label{section:fraternities}

On average, fraternities consist of students from families of higher-than-average educational attainment and income; they are predominantly white, and prior research has linked fraternity membership to positive outcomes such as increases in graduation rates [@routon_impact_2014], future income [@mara_social_2018],  and social capital formation [@mara_social_2018]. On the other hand, fraternity members spend approximately two more hours per-week partying than non-members [@routon_impact_2014], binge drink on approximately two additional days per-month [@desimone_fraternity_2007], and membership has been found to decrease GPA [@de_donato_effects_2017;@even_greek_2020]. Additionally, other research finds that membership causes students to select into easier courses and complete fewer course credits [@even_greek_2020]. While not causal, there is also survey evidence that fraternity members are more accepting of sexual violence than nonmembers [@seabrook_examining_2019] and that sorority women, who frequently interact with fraternity men, are four times more likely to be victims of sexual assault than nonmembers [@minow_sorority_2009].

This paper focuses on the Interfraternity Council (IFC) fraternities which are a type of social fraternity. These fraternities are the most common at universities and differ from professional, academic, or service fraternities. IFC fraternities engage in philanthropy and professional development, and according to their creed, they “exist to promote the shared interests and values of our member fraternities: leadership, service, brotherhood and scholarship” [@hechinger_true_2017]. Importantly, IFC fraternities are the fraternities that are restricted by moratoriums in the sample.

Each IFC fraternity chapter^[A chapter, otherwise known as a *house*, is a unique fraternity. A fraternity can have many chapters across the US, with usually one per-school.] has three sources of oversight: the chapter national headquarters, the parent university, and the parent university’s own IFC council—a group of student representatives from each recognized IFC fraternity chapter whom regularly meet with university staff to discuss rules/boundaries. Failure to abide by the rules outlined by these overseers' policies can result in a fraternity being unrecognized by the university which is costly—a fraternity relies on the university for new students to recruit.  

## Moratoriums \label{section:moratoriums}

A moratorium is defined as a temporary ban on social events with alcohol for IFC fraternities.^[This is the minimum requirement for a moratorium in this paper. Some universities ban alcohol at social events for all IFC fraternities in addition to the rest of their Fraternity and Sorority Life. However, IFC fraternities are generally the main focus.] This can include the cancellation of new member recruitment, philanthropy activities, tailgates, or third party vendor events, although the scope of restrictions differs by university. For example, some universities may allow philanthropy events provided no alcohol is present. Importantly, moratoriums differ from individual chapter suspensions. While universities may temporarily suspend individual fraternity chapters each year, moratoriums apply to all IFC fraternities. Moreover, the timing and length of a moratorium varies substantially. Figure \ref{closure_distribution} shows the start and end dates of each moratorium over time. Moratoriums in the sample can range from as short as six calendar-days to as long as 848 calendar-days.^[Note the distinction between calendar-days and academic-calendar days. A calendar day represent the entire calendar, whereas an academic-calendar represents only the fall/spring semesters of the university school year.] Additionally, moratoriums are generally implemented due to triggering events (see Appendix Table \ref{reasons_table}). These events can be a prominent sexual assault allegation, a fraternity-related death (usually due to alcohol poisoning), or an extreme behavior violation.^[A behavior violation refers to hazing, rule violations, offensive behavior, and other disorderly conduct that results in a moratorium.] Figure \ref{trigger_plot} shows the distribution of the triggering events: 19 are triggered by behavior violations, 10 by sexual assaults, nine by a fraternity-related death, and six are unspecified. As alluded to in the introduction, moratoriums are enacted across the US. Figure \ref{map_of_schools} shows the locations of the 37 universities in the sample (see Section \ref{section:construction} for further details on sample construction). Most universities are located in the Midwest and South, although there are several universities from both the West and East Coast. 

Moratoriums can be implemented by two sources of jurisdiction: the university or the IFC council.^[Note that the fraternity's chapter headquarters cannot impose a moratorium. Since chapter headquarters are unique to a fraternity chapter, they only have jurisdiction over one specific fraternity.] When a moratorium is implemented by the university, the university sets the guidelines that fraternities must abide by during the moratorium. On the other hand, an IFC-implemented moratorium is student-enforced. This means that the IFC council is responsible for producing both the guidelines and oversight of the moratorium. Figure \ref{trigger_plot} shows that IFC-implemented moratoriums are less frequent (17) than university-implemented moratoriums (27), and Section \ref{section:enforce} explores the potential differences in oversight.


