---
title: "Proposed Route"
author: 
  - Michael Topper
date: "Last Updated: `r Sys.Date()`"
output: 
  pdf_document:
    number_sections: true
    citation_package: natbib
    # latex_engine: xelatex # If i hashtag it out my code works? I'm not sure
indent: true
header-includes:
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{amsmath}
- \usepackage[english]{babel}
- \usepackage{bm}
- \usepackage{float}
- \usepackage[fontsize=12pt]{scrextend}
- \usepackage{graphicx}
- \usepackage{indentfirst}
- \usepackage[utf8]{inputenc}
- \usepackage{pdfpages}
- \usepackage[round,authoryear]{natbib}
- \usepackage{setspace}\doublespacing
- \usepackage{subfig}
- \theoremstyle{definition}
- \newtheorem{definition}{Definition}[section]
- \newtheorem{assumption}{Assumption}
- \newtheorem{theorem}{Theorem}[section]
- \newtheorem{corollary}{Corollary}[theorem]
- \newtheorem{lemma}[theorem]{Lemma}
- \newtheorem*{remark}{Remark}
- \newcommand{\magenta}[1]{\textcolor{magenta}{#1}}
- \newcommand{\indep}{\perp \!\!\! \perp}
- \floatplacement{figure}{H}
- \usepackage{natbib}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## R Markdown

```{r}
source("Figures/triggerplot_bylength.R")
```

\begin{landscape}
```{r, fig.cap= "\\label{trigger_plot}Average number of academic calendar days under moratorium by triggering event of moratorium.", fig.align = "center",fig.width= 44, fig.height= 36, out.width= "80%"}
trigger_plot
```
\end{landscape}


```{r}
library(tidyverse)
library(kableExtra)

data_used <- tibble(attributes = c("Source","Reporting Mandate", "Level of Aggregation", "Fraction of Sample Reporting Consistently", "Alcohol Violations", 
                      "Sexual Assaults", "Drug Offenses", "Residence Hall Information" ,"Analysis in Paper"),
       daily_crime_log = c(" Clery Act Requests", "By-law", "Incident-level", "1", "All Incidences Reported",
                           "All Incidences Reported","All Incidences Reported", "No", "Main Analysis"),
       clery = c("US Department of Education", "By-law", "Yearly", "1", "All Incidences Reported", "All Incidences",
                 "All Incidences Reported","Yes", "Secondary"),
       nibrs = c("FBI", "Voluntary", "Incident-level", as.character(round(14/38,3)), "Arrests Only", "All Incidences Reported",
       "All Incidences Reported", "No", "Not Used"),
       ucr = c("FBI", "Voluntary", "Monthly", as.character(round(30/38, 3)), "None","Hierarchy Rule",
               "None", "No", "Not Used"))
kbl(data_used, booktabs = T, digits = 3,
    col.names = c("Characteristics", "Daily Crime Logs", "Campus Safety and Security", "NIBRS", "UCR")) %>%
  kable_styling(latex_options = "scale_down") %>%
  # add_header_above(c(" " = 1, "Main Analysis" = 1, "Secondary Analysis" = 1, "Unused" = 2)) %>% 
  add_header_above(c(" " = 1, "Data Source" = 4)) %>% 
  footnote(list("Hierarchy Rule is where only the most serious crime in an incident is reported.",
                "While over 50 percent of UCR data is displayed to be reported consistently, it is actually truly unknown since NAs and 0s are the same.")) %>% 
  row_spec(8, hline_after = T) %>%
  column_spec(1, italic = T) %>% 
  landscape()

```

