---
title: "Discussion and Conclusion"
output: pdf_document
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Discussion \label{section:discussion}

## Do Moratoriums Mitigate the Effects of Football Games?

Both @lindo_college_2018 and @rees_college_2009 show that college football games cause higher instances of rape and alcohol offenses respectively. While football games cause negative outcomes, universities are reluctant to suspend football games—college football is popular among students and alumni in addition to being a major source of revenue. Therefore, finding an effective policy that can mitigate the detrimental effects of football games while maintaining the benefits is important for university administrators. This subsection analyzes whether moratoriums are the policy tool that can accomplish this.

Of the 37 universities in the sample, 34 have football teams. This results in over 2000 football games, 89 of which coincide with a moratorium. Using a similar model as the preferred specification,^[In this case, I use a model that is nearly identical to the preferred specification although using an indicator variable for whether or not a football game occurred as the explanatory variable. The controls include days of the week, university, holiday, and academic-year by semester—similar to the preferred specification.] Figure \ref{game_moratorium_plot} shows that football game days cause a significant increase in alcohol offenses and sexual assaults. These effects are largest on home games rather than away games which are consistent with @lindo_college_2018 and @rees_college_2009. Furthermore, Figure \ref{game_moratorium_plot} also shows the combined effect of a game day that occurs during a moratorium. In each of these estimations, the point estimates remain consistent with the effect of non-moratorium game-days although the point estimates are less precise. This may be caused by a lack of identifying variation—the point estimates are identified by 89 occurrences of game days that coincide with moratoriums. As a robustness check, I broaden the definition of game-days to "game-weekends" (e.g., Fridays/Saturdays/Sundays in which a football game occurs during one of these days) in Appendix Figure \ref{game_weekend_plot}. Although this nearly triples the amount of identifying variation,^[Not all game-days occur on a weekend, so the expanding the definition to a game-day weekend does not quite triple the number.] the results remain similar; the point estimates of the effect of game-day weekends with a moratorium are similar to a game-day weekend without a moratorium although also less precise. Taken together, it is uncertain whether moratoriums mitigate the effects of game-days. On one hand, these results offer the possibility that fraternities are not an integral component to college partying on game-days—students can substitute away from fraternity parties to other alternatives on game-days. On the other hand, it may be that moratoriums restrict the amount of dangerous partying that occurs during football games and produce a safer environment. Since the estimates are imprecise, it is unclear whether moratoriums can act as an effective policy tool to mitigate alcohol offenses or sexual assaults on football game-days. 


## Crime Displacement and Substitution of Partying \label{section:substitution}

One potential caveat to these results is that the observed decreases of alcohol and sexual assault shown in the Daily Crime Logs are being displaced to potentially riskier areas. For instance, while campus-wide alcohol is decreasing, it may be that fraternity members and other students are substituting their behaviors on-campus to off-campus areas that are less regulated. If this is true, the net effect of a moratorium may be worse than never implementing a moratorium. Unfortunately, there does not exist a perfect data source to explore such mechanism directly; the National Incidence-Based Reporting System (NIBRS) only reliably^[In this case, I consider a data source to be reliable if reporting of crime is consistent in the sample period. NIBRS features only nine schools that continually report data without large missing periods.] covers 24% of the sample universities' neighboring police departments and includes alcohol arrests rather than all incidences. Furthermore, the Campus Safety and Security (CSS) data, while possessing all incidences of crime reported on university campuses, is aggregated to the yearly level. 

Despite these challenges, I perform two sets of analysis using each of these data sets. First, to identify whether crime incidence is displaced into nearby areas, I use the NIBRS data to compare the reported incidence of crimes at nearby police departments with the crimes reported at university-specific police departments using the Daily Crime Logs. Nearby police departments are defined as police departments that serve the surrounding area, but are not affiliated directly with a university.^[The neighboring police departments were identified using @lindo_college_2018 public access data files in addition to Jacob Kaplan's NIBRS data tool available here: https://jacobdkaplan.com/nibrs.html#state=Colorado&agency=Denver%20Police%20Department&category=murder_nonnegligent_manslaughter&rate=false] In sum, this amounts to a comparison of a subset of 9 universities from the main sample and their corresponding university/nearby police departments. To harmonize the NIBRS data with the Daily Crime Logs, I define each offense from NIBRS as per-25000 enrolled students at the corresponding university and limit the panel to only academic-calendar days. Both alcohol offenses and sexual assaults are restricted to incidences involving college-aged individuals (e.g., 17-22), although the results are consistent when broadening the definition to include all ages. Moreover, I define sexual assaults in the NIBRS data to include fondling, rape, and sexual assault with an object to align with the definition using the Daily Crime Logs. 

Table \ref{spillover_table} shows that there is little evidence of heightened alcohol offenses at nearby police departments. In both Panels A and B, alcohol offenses and sexual assaults have a negative point estimate at nearby police departments, although insignificant from the standardized mean. However, the university-specific police departments continue to show large and significant effects of the moratorium for alcohol offenses despite being a small subset of the main sample. This gives confidence to the interpretation that moratoriums are decreasing alcohol offenses on university campuses and students are not taking their risky behaviors off-campus.

As the second set of analysis, I analyze the CSS data to examine if students substitute from partying at fraternity houses to different on-campus locations during moratoriums. The CSS data contains all violations of liquor, drug, and sexual assaults that occur in a calendar-year. The main advantage to using the CSS data is that it delineates between crimes that occur within a residence hall or a different on-campus location. Moreover, the CSS data includes liquor violations that may not have been reported to the police (thus not in the Daily Crime Logs) if they were handled internally by university staff. For instance, if a liquor violation occurred in a residence hall, the Daily Crime Logs will not have record of this if the citation was handled by university officials. However, the biggest disadvantage to this data is that all incidences are aggregated to the calendar-year level. Since moratoriums can last for as few as six days and can progress through multiple calendar-years, the analysis should be taken only as speculative, not causal.  See Appendix \ref{section:spillovers} for a more detailed discussion of the CSS data and the corresponding model used.

Despite these shortcomings, there is evidence that moratoriums significantly move drinking from fraternity houses to residence halls. Residence halls show a 28% *increase* in alcohol offenses relative to the mean when a proportion of a calendar-year is in a moratorium. This is accompanied by a large 82% *decrease* from the mean in residence hall sexual assaults. These results point to the possibility that moratoriums cause a substitution effect of partying behavior; students substitute drinking from fraternity houses to residence halls. Since residence halls are far more regulated than fraternity houses, problematic alcoholic behavior is intervened (e.g., the increases in alcohol violations) before it can become dangerous to others (e.g., the decreases in sexual assaults). 



# Conclusion \label{section:conclusion}

In this paper, I estimate the causal effect of temporary restrictions of fraternity social events with alcohol (moratoriums) on campus-wide reports of alcohol offenses and sexual assaults across 37 universities in the US. I construct a novel dataset which includes daily-level incidence reports from each university-specific police department. Using these data, I compare academic-calendar days with a moratorium to academic-calendar days without a moratorium while controlling for expected differences in the days of the week, holidays, semesters (spring/fall), academic years, football game-days, and universities. I find that moratoriums decrease the average reports of alcohol offenses on a given academic calendar day by approximately 26%. This result is most prominent on the weekends when partying is most frequent (28% reduction) while nonexistent on the weekdays. Moreover, I find suggestive evidence of decreases in reports of sexual assaults on the weekends with a 29% reduction from the mean, although only significant at the 10% level. Notably, moratoriums show no lasting effects; including an indicator for the week before and week after a moratorium shows a significant dip during the moratorium, but immediately returns to previous levels after the moratorium is lifted. These results demonstrate that moratoriums are only effective when active; despite the motivation that moratoriums allow time for members to reevaluate and change their systematic behavior, the effects do not persist. Taken together, these results support the notion that moratoriums are only effective in temporarily reducing campus-wide crime.

Given that moratoriums are unable to create permanent changes in student behavior, it is unclear whether they should continue as active policy. On one hand, moratoriums may move college partying behavior to safer areas (residence halls) as speculated in Section \ref{section:substitution} whereby risky behavior can be intervened more quickly. In addition, moratoriums may alleviate the detrimental health effects that alcohol causes in college students such as hindering academic performance and costly emergency room visits. On the other hand, moratoriums do not change student behavior; while moratoriums have large effects during enforcement, moratoriums are an unproductive policy to systematically reduce college partying behavior. Hence, school administrators should understand that moratoriums are a transient solution and should therefore look for other methods to promote long-term change. Unfortunately, there is a lack of research in such methods. For instance, several universities have implemented restrictions on fraternity recruitment strategies in their students' first semester. In particular, Duke University has implemented a deferred recruitment system in which students may not join fraternities until their sophomore year. Yet, as of this writing, there are only two studies that evaluate such policy and these papers focus on academic benefits rather than crime [@de_donato_effects_2017; @even_greek_2020]. Moreover, another understudied policy is the barring of specific misbehaving fraternity chapters from universities rather than IFC moratoriums. Although this policy alleviates the criticism that moratoriums are punishing even well-behaving fraternities, it is unclear whether this truly propagates behavior change—members of a poor behaving fraternity may choose to substitute to a new fraternity and thereby negatively influence its members. 

It is important to understand that this paper does not provide evidence advocating for the removal of fraternity life. Within this study, none of the universities removed fraternity life, only restricted one component: social events with alcohol. Hence, this paper does not provide support for national movements such as "Abolish Greek Life"; recall that prior research has linked membership to beneficial outcomes such as increased income, higher graduation rates, and more hours spent in volunteering and community service. However, this study *does* quantify the effects that fraternities have on university-wide partying behavior. More specifically, this paper is the first to show that restricting fraternity social events with alcohol significantly decreases campus-wide reports of alcohol offenses and sexual assaults.
