---
title: "Heterogeneity"
output: pdf_document
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

# Heterogeneity \label{section:heterogeneity}

In this section, I analyze four types of heterogeneous effects. First, I analyze whether moratoriums are more effective at schools with a reputation for partying and show that moratoriums are more effective in reducing alcohol offenses at party schools than non-party schools. Second, I examine which type of triggering event of a moratorium causes the most significant decreases of offenses and find that fraternity-related deaths exhibit the strongest results for alcohol offenses. Third, I estimate the required length for a moratorium to show the largest effects. While there is no clear answer to this, the estimates show that moratoriums should last at least a month to exhibit decreases in alcohol offenses. Last, I show that moratoriums are most effective when overseen by the university rather than the fraternity members themselves. 

## Party Schools

Universities that have a reputation for partying may be more impacted by the restrictions of moratoriums than universities that party less. For example, @lindo_college_2018 find that party schools exhibit two times the increase in reports of rape on football game days than non-party schools. To examine this possibility, I use Niche.com's Top Party Schools in America list.^[I use niche.com over the Princeton Review since the Princeton Review no longer posts their party school rankings.] The list assigns "party scene" scores based on criteria such as athletic department revenue, fraternity and sorority life statistics, access to bars, and student surveys.^[For more details on the methodology see: https://www.niche.com/about/methodology/top-party-schools/.]  Using this list, a university is defined as a party school if it appears in the top 50 rankings. This amounts to 16 of the 37 universities in the sample being classified as a party school. 

Table \ref{party_school_table} shows that party schools exhibit larger decreases in alcohol offenses than non-party schools. The point estimates in Panel A indicate that moratoriums decrease alcohol offenses on academic-calendar days by approximately 33% from the mean for party schools and 16% for non-party schools. Importantly, only the point estimates for party schools are statistically significant, thus showing that the effects of the moratorium are driven by schools that have a stronger party culture. 

## Triggering Event

As described in Section \ref{section:background}, there are several reasons why a moratorium is triggered: a fraternity-related death, a prominent sexual assault, or a behavior violation. There is little reason to expect that each of these cause similar effects. As an illustration, a death may be more salient than a behavior violation,^[Recall that a behavior violation includes hazing, offensive behavior, rule violations, and other disorderly conduct.] resulting in a stronger belief among fraternity members that their behaviors need to be modified. Moreover, both deaths and sexual assaults are less subjective results of risky behavior—a moratorium may seem more justified than an instance of hazing. 

Figure \ref{trigger_reg_graph} demonstrates that when a moratorium occurs due to a fraternity-related death or sexual assault, the effects of the moratorium are most prominent. Alcohol offenses decline significantly when a fraternity-related death is the triggering event. However, this may be due to a shock mechanism in which students across campus are changing their behavior in response to the death rather than the moratorium. For instance, students may be mourning the death of a student and partying behavior is reduced in response. This effect would contaminate the effect of a moratorium, as it would be unclear whether the moratorium is changing behavior or the death itself. To mitigate this issue, I separately analyze a sample containing the universities that experienced a fraternity-related death and underwent a moratorium with an additional 15 universities that experienced a fraternity-related death in the sample period, but *did not* undergo a moratorium.^[These universities were found using Hank Nuwer's repository of hazing-related deaths in the US: https://www.hanknuwer.com/hazing-deaths/.]. Hence, these additional universities are those whose students experience the effects of a fraternity-related death, but do not experience a moratorium. If the shock of death is the mechanism which produces decreases in alcohol offenses, then the effects of a moratorium on alcohol offenses should be insignificant when including these universities as a control group. However, with the inclusion of these universities, alcohol offenses maintain similar results—alcohol offenses are still significant at the 10% level. Although the statistical significance is weaker than the main results, this nonetheless signals that the moratorium itself is temporarily changing behavior rather than the occurrence of a death.

Additionally, Figure \ref{trigger_reg_graph} also shows significant decreases in sexual assaults when a triggering event involves either a sexual assault or behavior violation. However, the shortcomings of the estimations underlying these results must be carefully considered. Specifically, sexual assaults are a significantly under-reported offense—survey evidence shows that nearly 80% of sexual assaults go unreported.^[This is based on statistics from the AAU Campus Climate Survey on Sexual Assault and Sexual Misconduct. See here: https://ira.virginia.edu/sites/ias.virginia.edu/files/University%20of%20Virginia_2015_climate_final_report.pdf] Because of this, sexual assaults are relatively rare in police reports, thus resulting in small amounts of observations needed for identification. In addition, these estimates are based on a small subset of universities (19 universities for Trigger: Behavior and 10 for Trigger: Sexual Assault). Taken together, the results indicate evidence of decreases in sexual assaults, although more evidence is needed to substantiate this claim.

## Length of Moratorium

Each moratorium varies in its length. As shown in Table \ref{summary_stats}, the average length of a moratorium is 64 academic calendar days, with a minimum of 6 days and a maximum of 541 days. This is a large discrepancy, and to inform best practices, it is important to know at which length a moratorium will be effective; short-lived moratoriums may not be effective since there is little time for behavior to change, although longer moratoriums' benefits may diminish if imposed too lengthy. 

In an ideal dataset, a model that shows the effects of a moratorium along each day/week of enforcement would be estimated. More specifically, the model would show the number of days/weeks that produces the strongest effects. Unfortunately, it is challenging to model such regression since every moratorium has a different length; only the longest moratoriums will identify the later days/weeks' effect since short moratoriums will have ended. 

In light of these shortcomings, I analyze the heterogeneous effects of length by binning each moratorium into three percentiles based on length (33rd, 66th, 100th). The three percentiles correspond to [0-32], [33-59], and [60-541] academic-calendar day intervals under a moratorium respectively. Panel A of Table \ref{quantile_table} shows that when moratoriums are under 33 days, there is little effect on any of the offenses. On the other hand, Panel B exhibits the strongest effects among the three quantiles. In particular, alcohol offenses decrease significantly by an approximately 34% from the mean. Notably, the magnitude of both alcohol offenses and sexual assaults are the largest among the three panels although sexual assaults are not significant. Panel C shows weaker evidence of significant decreases in alcohol offenses from the moratoriums that last between 58 and 541 days with alcohol offenses decreasing 28% from the mean. Overall, this evidence shows that moratoriums need to be implemented for at least a month's worth of academic-calendar days to have effects across campus while there is evidence of diminishing returns if imposed for too long. On the contrary, short moratoriums have no effect on student behavior.

## University vs. IFC Enforcement

Recall that there are two sources of enactment/oversight for campus-wide moratoriums—the university itself and the university-specific IFC council. In the sample, 27 of the 44 (61%) moratoriums are enacted by a university. While a university-enacted moratorium is overseen by the university, an IFC-enacted moratorium is only overseen by the fraternity members themselves. More specifically, an IFC-enacted moratorium is purely an agreement among fraternity members to restrict their behavior. Hence, there is reason to suspect differences between these two sources of jurisdiction since IFC moratoriums may lack the incentive structure that university moratoriums have. For instance, a university can permanently suspend a fraternity chapter from its campus for failure to abide by moratorium guidelines which may damage the fraternity chapter's membership and reputation—two components necessary to guarantee longevity of the fraternity. This would give gravity to the university's enforcement, therefore showing that the moratorium is not strictly political. On the other hand, IFC councils have little incentive to permanently suspend or impose additional sanctions as fraternity chapters rely on each other to create a thriving social life and community. As such, further disciplinary measures by the IFC-council directly affects the council members themselves, thus creating a system that may incentivize IFC council members to look away from any deviations from the  guidelines set forth.

In Table \ref{ifc_uni_table} alcohol offenses have suggestive evidence of a decline when a university imposes the moratorium as shown in Panel A. Consistent with the main results, the largest effects are on weekends rather than weekdays. The point estimates for sexual assaults are insignificant across both university-imposed and IFC-enacted moratoriums, likely due to the infrequent reporting of sexual assaults. These results show evidence that university-imposed moratoriums are likely more effective than the IFC-enacted moratoriums.
