---
title: "Results"
output: pdf_document
---

# Results \label{section:results}

In this section, the causal effects of a fraternity moratorium on alcohol offenses and sexual assaults are estimated using OLS. To reduce potential noise in the estimates, the sample is restricted to only the academic-calendar days unique to each university.^[See the Data section for more details.] Furthermore, I analyze dynamic effects and perform numerous robustness and sensitivity checks—each resulting in estimates that are consistent with the main findings discussed above. Figure \ref{diff_average_offenses} serves as a preview of the main results by plotting the distribution of differences between the number of offenses per-25000 enrolled students on moratorium days and non-moratorium days. On average, most universities observe less alcohol offenses and sexual assaults on moratorium days as displayed by the dashed line.

## Main Results

Table \ref{main_table} reports that fraternity moratoriums lead to substantially lower alcohol offenses across university campuses while showing weaker evidence of decreases in sexual assaults. Column (1) shows the baseline specification from Equation \ref{main_model}. This baseline specification includes day of the week, holiday, semester, and academic year fixed effects. Moreover, columns (2) and (3) show results from progressively adding more flexible fixed effects. In Panel A, alcohol offenses decrease during moratorium days relative to non-moratorium days in the academic calendar. In particular, an average moratorium day exhibits between 24 to 28 percent less alcohol offenses in comparison to an average academic calendar day as shown in the point estimates. These estimates are statistically significant across each specification, maintaining that moratoriums decrease campus-wide alcohol offenses. Although alcohol offenses are robust, sexual assaults fail to achieve statistical significance across each specification and the magnitude of each effect varies considerably; sexual assaults show a 16-18 percent reduction from the mean. One reason for this discrepancy in magnitude may be that the inclusion of the university by academic year fixed effect (column (2)) changes the comparison groups; intuitively, a university by academic year fixed effect allows only for comparisons of moratorium days to non-moratoriums within a particular university's academic calendar. Similarly, interacting university, academic year, and semester fixed effects (column (3)) only allows for comparisons of moratorium days to non-moratorium days within a particular university's semester in a particular academic year. While the controls in column (3) are the most flexible, I use the controls in column (2) in all further analysis for two reasons. First, the results in column (2) are the most conservative. Second, 24 of the 45 moratoriums (53%) have moratorium days that span across at least two semesters, while only 6/45 (13%) have moratoriums days that span across at least two academic years. Hence, since the specification (3) only compares moratorium days to non-moratorium days within a university-academic-year-semester, there is far less variation than specification (2). In particular, some universities may have very few moratorium days within a university-academic-year-semester (column (3)) in comparison to a university-academic-year (column (2)). Thus, using column (2) as the preferred specification, only alcohol offenses are significantly reduced in moratorium days when considering the entire sample period.

The effects of moratoriums are most evident during the weekends (Friday-Sunday), consistent with the literature that most college partying occurs on weekends rather than weekdays [@lindo_college_2018]. Table \ref{weekend_table} shows column (2) from Table \ref{main_table} separated by weekends, and weekdays; the column "All Days" corresponds to the estimates of column (2) from Table \ref{main_table}. During the weekends, alcohol offenses decrease by 27% relative to an average academic-calendar weekend as shown in Panel A. On the other hand, weekdays show no statistically significant decreases. Likewise to alcohol, sexual assaults show larger decreases on the weekend in comparison to weekdays in Panel B. A weekend during a moratorium can expect 26% fewer sexual assaults relative to an average academic-calendar weekend.

While both alcohol offenses and sexual assaults decrease significantly on the weekends, these effects are concentrated only within a moratorium. Figure \ref{week_before_after} shows estimates from specification (2) in Table \ref{main_table} with the inclusion of an indicator variable for the week after and week before a moratorium. When considering the entire sample, each offense exhibits decreases that persist only during the moratorium period. This pattern persists when restricting the sample to weekends where the effects of the moratorium are most prominent. 


## Robustness

### Inclusion of Never-Treated Universities

Given the low number of universities in the sample (38), the results shown above lack precision—while both alcohol and sexual assault offenses show statistically significant decreases on the weekend, the standard errors can only rule out weekend reductions greater than 41 and 42 percent from the mean with 95% confidence for alcohol offenses and sexual assaults respectively. To address this issue and increase power, I include 14 additional universities in the sample that never underwent a moratorium in the period of analysis. This amounts to 52 total universities for a total of approximately 75,000 academic calendar days. Each of the additional universities was chosen from the Colleges with the Best Greek Life list on Niche.com.^[I use Niche.com since it is the top search result on Google when searching for the ``best fraternity colleges''. The Princeton Review, notable for its annual list of party schools, does not a list regarding fraternity life.] Never-treated universities were selected if they were regarded as a top 50 Greek Life school.^[Notably, it is known that at least one university (Chico State) had a moratorium outside of the sample period (2013). This, however, only further validates the selection of the never-treated universities.] However, 17 of these universities were already included in the sample due to experiencing a fraternity moratorium. As such, 14 of remaining 33 universities were able to provide Daily Crime Logs for the 2014-2019 period. Table \ref{weekend_table_allschools} shows the effects of moratoriums when including these never-treated universities. Overall, the results remain similar, with weekend decreases of alcohol of approximately 18 percent reduction from the mean and sexual assault decreases at approximately 25 percent. Although weekend offenses of alcohol may appear slightly less significant, it is noted that the p-value is only a hair above .05. Notably, the standard errors encapsulate the point estimates from the main results in Table \ref{weekend_table} and the stability of the estimates and significance instill further confidence in the results of the model.

### Leave-one-out Estimation

Figures \ref{loo_alc_ols} and \ref{loo_sex_ols} show leave-one-out coefficient estimates for each corresponding offense. This analysis ensures that the results described above are not driven by a single university. In particular, 38 unique regressions are estimated for every offense, omitting one university within each iteration. This exercise is repeated for the entire sample in addition to weekends and weekdays only. In each figure, the results remain consistent with the estimates shown in Table \ref{weekend_table}; alcohol offenses significantly decline overall (with particularly strong effects on the weekends) while there is weaker evidence of declines in sexual assaults on the weekends. This analysis verifies that the effect of the moratorium is not driven by only one particularly stringent university.

### Poisson Estimation

Given the non-negative count nature of the offense data and the sensitivity of OLS estimation to outliers,  Tables \ref{main_table_p} and \ref{weekend_table_p} show Tables \ref{main_table} and \ref{weekend_table} using poisson estimation in lieu of OLS.^[Despite these advantages of poisson estimation, OLS is the preferred method since the results are more conservative.] The results are consistent with Table \ref{weekend_table} showing the preferred specification leading to 27 and 28 percent average reductions for alcohol offenses and sexual assaults on the weekends respectively. 

### Robustness to Negative Weights

Lastly, several recent journal articles have found that using OLS in a two-way-fixed-effects (TWFE) difference-in-differences design can cause problematic issues with the coefficient estimates when there are heterogeneous treatment effects between groups over time [@de_chaisemartin_two-way_2020; @sun_estimating_2021; @athey_design-based_2022]. In particular, the parameter of interest (e.g., the coefficient on the treatment variable) is a weighted sum of average treatment effects where some of the weights may be negative. This negative weighting issue can potentially lead to coefficient estimates switching signs. For instance, a negative-signed treatment effect implicating reductions may actually be positively-signed once corrected for the problematic negative weights. While this paper's research design is not a typical TWFE design since the preferred specification uses interacted fixed effects and university's switch between moratorium days and non-moratorium days (and in some cases multiple times), there maintains a possibility that the negative weights issue could extend to the preferred model used in this paper. Appendix \ref{section:twfe} analyzes a typical TWFE design in this setting using university and day by month by year fixed effects. I show that this design does not contain negative weights and that the coefficient estimates are consistent with the results described earlier. 



