---
title: "Referee Notes"
output: pdf_document
date: "2022-10-31"
linkcolor: blue
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
- \usepackage{subfig}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Main Regressions

```{r}
source(paste0(here::here("referee_analysis/forest_plot_update.R")))
```

```{=latex}
\begin{figure}[t]
```

```{r, fig.width = 9.5, fig.height = 6}
alc_forest
```

```{=latex}
\caption{Robustness Across Samples (Alcohol Offenses) \label{alc_forest}}
\textit{Note:} This graph depicts the coefficient estimates and 95\% confidence intervals for different subsets of the sample. The y-axis on the left is the sample selection used, while the y-axis on the right is the point estimate. All estimates use the preferred specification from Table \ref{main_table} Column 2, and all outcomes are in terms of per-25000 enrolled students. Standard errors are clustered at the university level. Panel A uses the main sample as shown in the main results, while Panel B uses the main sample in addition to 14 never-treated schools (see Section \ref{section:mainresults} for more details). Panel C analyzes 15 universities which undergo a fraternity death, but do not undergo a moratorium. A 64-day binary treatment period is given to each of these universities, beginning on the date of the death. Panel D extends the analysis in Panel C by adding in the 15 never-treated universities as controls, analogous to Panel B in reference to Panel A. See Section \ref{section:trigger} for more details.
\end{figure}
```
