---
title: "Fraternities Update"
subtitle: ""
author: 
  - Michael Topper
date: "Last Updated: `r Sys.Date()`"
output: 
  pdf_document:
    number_sections: true
    # latex_engine: xelatex # If i hashtag it out my code works? I'm not sure
indent: true
header-includes:
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{amsmath}
- \usepackage{bbm} ##for indicator
- \usepackage[english]{babel}
- \usepackage{bm}
- \usepackage{float}
- \usepackage[fontsize=11pt]{scrextend}
- \usepackage{graphicx}
- \usepackage[utf8]{inputenc}
- \usepackage{pdfpages}
- \usepackage[round,authoryear]{natbib}
- \usepackage{subfig}
- \floatplacement{figure}{H}
bibliography: "references.bib"
link-citations: yes
linkcolor: blue
abstract: Fraternities remain a ubiquitous, and longstanding tradition across the US with chapters maintaining a presence at over 800 universities and some existing since the mid-1800s. While fraternity membership has positive outcomes, it has also been linked to high rates of alcohol, partying, and toxic masculinity. In this paper, I exploit the variation from temporary university-wide halts on all fraternity activity with alcohol (moratoriums) across 38 universities. I construct a novel data set using webscraping, pdf extracting, and Freedom of Information Act requests to present the first causal evidence of what could happen across university campuses if fraternities were prohibited from serving alcohol at social events and faced stricter regulations. In particular, I find strong and robust evidence that fraternity moratoriums lower alcohol violations campus-wide by 25%. These effects are driven by large decreases on the weekends rather than weekdays and when a university enforces the moratorium rather than the fraternity members themselves. Moreover, I find weak evidence that moratoriums decrease reports of sexual assault on the weekends and when moratoriums are triggered by sexual assault allegations. 
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning= F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(kableExtra)
library(tidyverse)
library(lubridate)
library(modelsummary)
library(maps)
theme_set(theme_minimal())
```

```{r, echo = F}
number_of_universities = 53
```

\newpage
\pagenumbering{arabic}
```{r, child = "writing.Rmd"}

```

\newpage
```{r, child = "figures.Rmd"}

```

\newpage
```{r, child = "tables.Rmd"}

```

